### ISSUE TITLE
Problems with message archiving

### ISSUE THREAD

**Issue by MetalZoa0** [processone/ejabberd#1013]
The user messages are saved in the database with the activation of mod_mam, however, when the chat is finished messages are not displayed in the client tool, but still saved in the bank, what's wrong? I'm using ejabberd 15:10 with client Jappix.

**Comment by MetalZoa0** [comment]
the module `mod_mam` is enabled with the following parameters:
  `mod_mam:`
  `iqdisc: one_queue`
  `default: always`
  `cache_size: 1000`
  `cache_life_time: 3600`

**Comment by badlop** [comment]
If your client doesn't display the old messages, maybe it is because your client is designed or configured that way?

**Comment by MetalZoa0** [comment]
when I set it up to work with internal database mnesia client tool returns messages normally.

**Comment by badlop** [comment]
The stored messages are retrieved correctly in my test using ejabberd 16.02, MySQL, and manual MAM queries (Tkabber does not support MAM itself, so I perform queries as specified in http://xmpp.org/extensions/xep-0313.html#query )

I see in the git logs that there were many changes in mod_mam.erl between 15.10 and 16.02, so maybe it's a bug already fixed. You should try ejabberd 16.02 and check if your problem is still present.
