### ISSUE TITLE
Timeout on handle sync

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1038]
What version of ejabberd are you using?
    15.04

    What operating system (version) are you using?
    Fedora 22

    How did you install ejabberd (source, package, distribution)?
    source

Hello  I am adding some of my code for which i need updated user subscribers so i am using 
`NewList = ejabberd_c2s:get_subscribed(pid())
`
This works well if i am getting data for other sessions or pid  but if i try to get using own pid it fails on timeout  NewList = ejabberd_c2s:get_subscribed(self())

How can get the data for self()?

**Comment by nOmi7** [comment]
@mremond @mathiasertl  sorry guys to mention you directly but was really looking for pointers on this .
I really appreciate your help and time for the community .

**Comment by nOmi7** [comment]
Can anyone please help me here :/

**Comment by mremond** [comment]
You do not need a call. Self is your process and you already have access to your process state in the context of your OTP gen_server / gen_fsm.
If you try doing a synchronous call to yourself, then you are creating a deadlock: a process cannot wait for a reply from itself, because a process is a single thread of execution.
