### ISSUE TITLE
Using iq handler ejabberd_sm in all modules is making ejabberd latency worse

### ISSUE THREAD

**Issue by LucianoBernal** [processone/ejabberd#1040]
Hi, I'm using ejabberd 15.04, in a EC2 Amazon Linux AMI, and had installed ejabberd from source.
I have made my own modules and run ejabberd in a cluster of 3 erlang nodes, behind an Elastic Load Balancer (of amazon). The machines have 4 cores and 30GB ram each.
The thing is that I have 80k users connected concurrently and sometimes the server doesn't respond or does it with high latency.
In the ejabberdctl.cfg file of each node I've put the following:
ERL_MAX_PORTS=360,000
ERL_PROCESSES=15,000,000
ERL_MAX_ETS_TABLES=20,000
Besides, I have written all my custom erlang modules than handle iq's with 'ejabberd_sm', is that right?
The system is working very slow and erratically.

Thanks a lot in advance,

Luciano Bernal

**Comment by ppolv** [comment]
Hi,
is the problem with core ejabberd or with your custom module?,  what had you done to debug the issue?
I'm closing this as for the information given seems a problem with your module rather than ejabberd.

I'd start by checking the message queue size / memory use  of the processes to try to spot where the bottleneck is.   If you are accessing an external service on your custom module you probably will need to adjust the # of concurrent handlers you use (see the iqdisc  option in https://docs.ejabberd.im/admin/guide/configuration/) to compensate for the latency of each interaction, etc.

**Comment by LucianoBernal** [comment]
Thousands of greetings ppolv!!!!!
