### ISSUE TITLE
ejabberd  how to push_alltoall

### ISSUE THREAD

**Issue by hamedice** [processone/ejabberd#1056]
> What version of ejabberd are you using?
2.1.11

> What operating system (version) are you using?
ubuntu

> How did you install ejabberd (source, package, distribution)?

apt-get

my ejabberd server is working fine with my open-ldap server as authentication . 
i need to config , all ldap users after authentication can see all ldap users in their budies.
I found the command ejabberdctl push_alltoall and it seems the right option for me but i cant work with it .
ejabberdctl push_alltoall example.com engi

another thing in my webamdin page I have nothing to config! no choice is there !!
any on can help me ??

**Comment by badlop** [comment]
> in my webamdin page I have nothing to config! no choice is there !!

This is probably because the account credentials that you provided do not have admin rights in the ejabberd configuration file.

> ejabberdctl push_alltoall example.com engi

This command works correctly for me using ejabberd 16.03, mod_roster mnesia storage, and internal storage. In your case, which is a very old version, maybe the command does not support LDAP auth, or you store mod_roster in ODBC and the command doesn't support it, or it may have a bug.

> i need to config , all ldap users after authentication can see all ldap users in their budies.

I don't remember if your ejabberd version already supports it, but you can see in your ejabberd Guide if mod_shared_roster supports @all@, and try it to see if it works with LDAP auth (I guess that will NOT work).

You can also see if there is some module like mod_shared_roster_ldap available for your ejabberd 2.1.11 version, which I also suspect isn't available.
