### ISSUE TITLE
mod_irc: Not closing connections to IRC server

### ISSUE THREAD

**Issue by iwalkalone69** [processone/ejabberd#1089]
> What version of ejabberd are you using?

2016.02

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

Distribution.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Despite users disconnect from ejabberd server, this keeps the nick connected to IRC network. When connection from client is lost, it should disconnect nick on IRC network too.

**Comment by iwalkalone69** [comment]
I've managed to understand that irc connection is closed on mod_irc_connection.erl, function terminate:

`gen_tcp:close(Socket),`

So I understand that terminate is not always called. Hope it helps to fix it.

**Comment by iwalkalone69** [comment]
Just to give more information, as a temporary solution, we are sending a PRIVMSG to this "zombie" nicks and then they get disconnected. It works also with CTCP.

**Comment by badlop** [comment]
mod_irc is not maintaned anymore. The code was moved to ejabberd-contrib in June (3a5d2dbed8f089b112eba7998e2ad0d2508f01cb), so that it doesn't get lost. If this problem is still present and somebody wants to fix it, a new ticket in [ejabberd-contrib](https://github.com/processone/ejabberd-contrib) can be created, referencing this old one.
