### ISSUE TITLE
Ejabberd 16.03 (with some modules installed) crashes while trying to access web portal

### ISSUE THREAD

**Issue by pkarn** [processone/ejabberd#1096]
> What version of ejabberd are you using?
16.03

> What operating system (version) are you using?
Ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?
package

> What did not work as expected? Are there error messages in the log?
> was the unexpected behavior? What was the expected result?

I have ejabberd 16.03 with one module installed using "ejabberdctl module_install". Server works fine untill I try to access web admin interface (localhost:5280/admin). Ejabberd crashes, generated crash dump and will have to restarted.

Crash dump has following error: "eheap_alloc: Cannot allocate 2277966824 bytes of memory (of type "old_heap", thread 1)", it seems like erlang crashes with out of memory error. I attached dump file too.

I think this only happens when HTTP endpoints are called.

Also please note that this does not happen when there are no user modules installed in ejabberd. I doubt this has anything to do with module itself because it has been working on 16.01.

**Update:** it seems to happen when SCRAM is enabled.
```auth_password_format: scram```

[erl_crash.dump.zip](https://github.com/processone/ejabberd/files/241517/erl_crash.dump.zip)

**Comment by cromain** [comment]
did you installed a module from ejabberd-contrib ?

**Comment by badlop** [comment]
Looking at your crash dump, an erlang process gets crazy when is calling some crypto or scram functions. Maybe it enters an endless loop, but looking at the code this isn't possible.

Does it happen by just opening the webadmin page? Or only after entering the admin credentials? If you provide credentials of another admin account, does it crash? And if you change the password of the admin, and retry to enter webadmin? What auth method are you using: internal, sql...? What module did you install?

If you install this in another machine: that ejabberd version, and that module, and configure like you did, does the problem reproduce? It would be nice if I can reproduce the problem myself...

**Comment by pkarn** [comment]
This issue reproduces with 16.04 release. I do not have any modules installed from ejabberd-contrib, this occurs on fresh install when password format is SCRAM.
Crash happened after credentials of admin account was entered. I haven't tried with different admin account.
Auth method was set to odbc (now sql).
I was able to reproduce this issue on 3 different machines.

**Comment by badlop** [comment]
I can reproduce the problem. It appears when auth is ODBC, SCRAM is configured, an account is provided to login into WebAdmin, but the auth credentials in the 'users' SQL table are still plain, instead of scrammed.

When a new account is created, its credentials are stored scrammed already, and trying to login with that into WebAdmin does not crash.

Quick workaround solution for you: create a new admin2 account so that it's stored scrammed already, and use that one temporarily to login WebAdmin until a proper fix is found.

Two tasks remain:
* find and document a way to convert mnesia and odbc databases from plain to scrammed passwords.
* fix WebAdmin so it doesn't enter an endless loop when scram is enabled but the actual credential is not.

**Comment by pkarn** [comment]
Yeah I was pointing to existing MySQL database which already has data stored in plain text, even though it has SCRAM columns there. Thanks for looking into this. 

As long as server does not crash and auth returns 'not authorized' indicating something went wrong with auth module, it should be good.
