### ISSUE TITLE
[Enhancement] shared roster management

### ISSUE THREAD

**Issue by thundergreen** [processone/ejabberd#1121]
> What version of ejabberd are you using?
16.04

> What operating system (version) are you using?
Debian Jessie (armhf)

> How did you install ejabberd (source, package, distribution)?
Built from source 

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

managing shared roster members is a bit  complicated. Would be nice having a multiple selection for the users on the virtual hosts (virtual host selection via drop down ) to put them in a shared roster.at this moment u have manually to copy the users to put them into a shared roster.this could be done by selecting them from a user list and add them into a selected shared roster.would be nice if in the same window the possibility would be given to create the shared roster if needed 

Thanks for this amazing work!

**Comment by badlop** [comment]
You are thinking in a server with 20 or 50 users, right? With more than that, the drop down list would be unusable, and would require some Javascript thing to complete words.

I expect there are fewer groups than users, so it would make more sense to add that element to the user page. In theory, that would be more usable even with many users, as long as there are few groups.

But notice that, in that case, you probably have to perform a lot of those tasks. Doing them manually in a web browser is a good idea? mod_admin_extra provides several commands that you can run in the shell, like srg_user_add, so that you can write a simple script to add many users to groups.

**Comment by thundergreen** [comment]
Are there perhaps some nice scripts already?  I have to admit I'm not that
familiar with this. But u could be right with your opinion

Thorsten Fröhlich
Am 17.05.2016 20:34 schrieb "badlop" <notifications@github.com>:

**Comment by badlop** [comment]
This small Bash script gets the list of registered accounts in "localhost", then filters the account names that contain the word "user", and those ones are added to the group "group1":
```
$ for U in `ejabberdctl registered_users localhost | grep user`; do
  ejabberdctl srg_user_add $U localhost group1 localhost; done
```

So, this is the result:
```
$ ejabberdctl srg_get_members group1 localhost
user1@localhost
user2@localhost
user3@localhost
user4@localhost
user5@localhost
user6@localhost
user7@localhost
```
