### ISSUE TITLE
 Development methodology Ejabberd

### ISSUE THREAD

**Issue by MetalZoa0** [processone/ejabberd#1127]
Could someone enlighten me if you used any development methodology (software development methodology) in Ejabberd if so what were they?

**Comment by badlop** [comment]
No software is strictly required. Many developers (in ejabberd and other erlang projects) use Emacs, because it includes many erlang support (indenting, file skeletons, debugging and many more). In my case I use old-school Vim, which includes some basic erlang support. I imagine other software environments include erlang support, and follow more or less Emacs standard indenting...
