### ISSUE TITLE
ejabberd_http crash 

### ISSUE THREAD

**Issue by Nitin3589** [processone/ejabberd#1133]
> What version of ejabberd are you using?

ejabberd 15.11

> What operating system (version) are you using?

ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

deb.package 

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

in our production, we got some errors like below several times a day :

```
CRASH REPORT====
crasher:
    initial call: ejabberd_http:init/2
    pid: <0.14610.61>
    registered_name: []
    exception exit:
 {{noproc,{gen_fsm,sync_send_all_state_event,
[<0.5960.370>,{http_put,4106211421,[{<<"xmlns">>,<<"http://jabber.org/protocol/httpbind">>},
{<<"rid">>,<<"4106211421">>},{<<"sid">>,<<"9423d433837317899ff50dee003c2691bb6a187b">>}],
[],115,1,<<>>,{{58,68,3,107},62928}},30000]}},
[{gen_fsm,sync_send_all_state_event,3,[{file,"gen_fsm.erl"},{line,242}]},
{ejabberd_http_bind,http_put,7,[{file,"src/ejabberd_http_bind.erl"},{line,785}]},
{ejabberd_http_bind,handle_http_put,7,[{file,"src/ejabberd_http_bind.erl"},{line,751}]},
{ejabberd_http,process,5,[{file,"src/ejabberd_http.erl"},{line,360}]},
{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,448}]},
{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,290}]},
{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,210}]},
{ejabberd_http,init,2,[{file,"src/ejabberd_http.erl"},{line,163}]}]}
 ancestors: [ejabberd_http_sup,ejabberd_sup,<0.38.0>]
 messages: []
 links: [#Port<0.1062857>,<0.381.0>,#Port<0.1062807>]
 dictionary: []
 trap_exit: false
 status: running
 heap_size: 2586
 stack_size: 27
 reductions: 1950
 neighbours:
=SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_http_sup}
     Context:    child_terminated
     Reason:     {noproc,{gen_fsm,sync_send_all_state_event,[<0.5960.370>,
{http_put,4106211421,[{<<"xmlns">>,<<"http://jabber.org/protocol/httpbind">>},
{<<"rid">>,<<"4106211421">>},{<<"sid">>,<<"9423d433837317899ff50dee003c2691bb6a187b">>}],
[],115,1,<<>>,{{58,68,3,107},62928}},30000]}}
Offender:   [{pid,<0.14610.61>},{name,undefined},{mfargs,{ejabberd_http,start_link,undefined}},
{restart_type,temporary},{shutdown,1000},{child_type,worker}]
```

**Comment by Nitin3589** [comment]
This is an already reported issue which was previously closed , i am sharing the link  for it here 

[](https://github.com/processone/ejabberd/issues/259)

**Comment by badlop** [comment]
I am not BOSH expert, just looking at the crash report, it apparently happens when processing a client HTTP query, sent to another ejabberd node in the cluster, and the erlang process that handles that Jabber connection is not found (the error is 'noproc'). Maybe the client disconnected, but the other node in the cluster didn't know yet...

**Comment by Nitin3589** [comment]
i was assuming this error raised cause of client i am using , but now i am frequently getting this  please help me solve this .

**Comment by prefiks** [comment]
Most likely scenario for this to happen is that your client is sending session termination request, and immediately after it sends another requests. Since those two are run in parallel, it's possible that the second request tries to send information to session that was deleted by first request, and this generates this error.

Since this doesn't lead to some broken behaviour, you shouldn't worry about seeing this too much. If you have loglevel set to debug level (5) you can verify if this deduction is correct by checking if you have log entry for "Looking for session <session id>" followed by "terminate: Deleting session <session id>" and then that error.

**Comment by Nitin3589** [comment]
Could this lead into complete server breakdown , because this is what happen in my scenario.

**Comment by prefiks** [comment]
Not likely, this should cleanup all resources.
