### ISSUE TITLE
we need a logout button for the web admin interface

### ISSUE THREAD

**Issue by suexcxine** [processone/ejabberd#1163]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

ubuntu 14.04

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

there is no logout button in the web admin interface, namely, like http://localhost:5280/admin,
if I close the tab, and reopen, there is no need to enter password,
this is considered unsafe.

**Comment by mremond** [comment]
The password is requested from the server standpoint. It is just that your browser is caching it and sending it automatically. Close your browser and reopen it and password will be required again (unless you checked the mark to store the password it browser password keychain)

**Comment by suexcxine** [comment]
There are web applications with logout button,
Is that possible to provide a logout button? Then there will be no need to close browser.

**Comment by mremond** [comment]
ejabberd is using basic authentication. It is not using cookie / session based authentication.

In basic auth, the server requires you authenticate on all pages. To avoid asking the authentication details every time, the browser cache the login / pass for a while. So, all happen client side. I do not think server has a standard way to trigger clean up of the client site.

So bottom line is that you are not asked again for authentication because client browser retains it for a while.
