### ISSUE TITLE
How-to match mobile agenda with Ejabberd users

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd#1182]
Hi,

I'm registering the users of my application with the mobile number as _jid_:

_666666666@domain.com_

Which is the best way to match all my mobile agenda (mobile contacts) in order to see which contacts are users in the service?

I saw some things related with a search service, but I think that this service is only available for admins.

Options?

Thanks :)

**Comment by badlop** [comment]
Right, in Jabber, the existence of an account is considered private information.

You can enable mod_vcard and enable search, and tweak your clients so they publish a small vCard, so they can be found.

Or you could somehow reveal the list of accounts to any registered user. Or allow registered users to check if an account exists or not.

Or, the solution that may be easier if you can modify the clients that your users use:
- Tweak the client so, when the application is installed, or each time it's started, the client sends subscription requests to all the numbers that aren't yet contacts.
- Tweak the client so, it always accepts subscription requests, without asking the user.

This way, all the numbers in the phone would be Jabber contacts. There is only one thing to do in ejabberd: remove periodically the subscription requests that were not processed (probably because the destination account does not exist); this can be done using mod_admin_extra, ask me for details if necessary.
