### ISSUE TITLE
Multiple MUC invitations are not processed correctly

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1285]
> What version of ejabberd are you using?

16.08

> What operating system (version) are you using?

CentOS Linux release 7.2.1511

> How did you install ejabberd (source, package, distribution)?

RPM

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When creating mediated invitation messages for MUCs only the first user in the invitations list get's invited.

```xml
<message from="alice@example.com/resource" to="chatroom@conference.example.com" id="18b1b516-63bd-4e6a-b547-22b8fdb1bc84" xmlns="jabber:client">
    <x xmlns="http://jabber.org/protocol/muc#user">
        <invite to="bob@example.com" />
        <invite to="charlie@example.com" />
    </x>
</message>
```

only bob@example.com receives the invitation.

According to the [XML schema in XEP-0045](http://xmpp.org/extensions/xep-0045.html#schemas-user), multiple `invite` elements are allowed.

However, [mod_muc_room](https://github.com/processone/ejabberd/blob/3803a8de3c2ad70ef967bb6d7a47f20fcf82f859/src/mod_muc_room.erl#L4916) only seems to read the first `invite` element.

**Comment by badlop** [comment]
Right, the source code is quite explicit: only the first Invite is used. It is so by design, so it isn't a bug, but a misfeature that has been there since the code was first written. When Tkabber client is said to send an invitation to several users, in fact it splits it into individual invitations.

I'll try to improve it to support multiple destinations.

**Comment by marcphilipp** [comment]
Thanks! 👍
