### ISSUE TITLE
crossdomain.xml is not found

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#1299]
> What version of ejabberd are you using?
> latest version
> 
> What operating system (version) are you using?
> windows 7
> 
> How did you install ejabberd (source, package, distribution)?
> distribution

Dears,

Kindly that i installed ejabberd on my local network and it was working just fine but when i tried to access it using strophe.js from another pc on the network I get the error crossdomain.xml not found.

is there any solution for this, please help

Thank you,

**Comment by badlop** [comment]
There was a very old patch to provide that file to Flash clients: https://support.process-one.net/browse/EJAB-960
But it has been three years since that was last commented, so the patch is no longer usable.
In fact, according to this ticket, there is another way to change domain, not using crossdomain file: https://support.process-one.net/browse/EJAB-1168

**Comment by vijayaa** [comment]
Do we need to apply this patch to ejabberd 16.09 also? i am getting cors error on my chrome browser when we try to proxy the requests using HAProxy

**Comment by badlop** [comment]
The old crossdomain patch (EJAB-960) was not included in ejabberd. The CORS patch (EJAB-1169) was included in ejabberd 16.09.

It may happen that there was some bug, fixed in a later version, that you can solve by upgrading ejabberd. In that case, you can try to install a recent ejabberd in a test machine, test if this is fixed, and in that case upgrade the server machine. Or it may be a yet unknown bug. Or there's some specific problem in your setup.
