### ISSUE TITLE
Store Data in SQL

### ISSUE THREAD

**Issue by maseruka** [processone/ejabberd#1307]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

ubuntu 15.04 x64

> How did you install ejabberd (source, package, distribution)?

using a .run package

> was the unexpected behavior? What was the expected result?

I enabled odbc storage (mysql) in .yml but only the users who signup and offline messeges are stored in the database and also after the offline messeges have been deliverd, they get deleted... How can i store the instant messages and also store messages deliverd in mysql database

**Comment by badlop** [comment]
> I enabled odbc storage (mysql) in .yml but only the users who signup and offline messeges are stored in the database

You can configure each individual module where you want it to store its data. So, in each module you add the option db_type and set it to sql.

> and also after the offline messeges have been deliverd, they get deleted... 

Right, this is how offline messages work: they are stored if the user is offline, they are sent to the user, and then they are deleted because the user already received it. See http://xmpp.org/extensions/xep-0160.html

> How can i store the instant messages and also store messages deliverd in mysql database

You want persistent storage of all the messages a user sends or receives... so you want to use mod_mam.

**Comment by zinid** [comment]
No response from the reporter, I close the issue.
