### ISSUE TITLE
http request in ejabberd, and so many tcp connection

### ISSUE THREAD

**Issue by nonexu** [processone/ejabberd#1335]
> What version of ejabberd are you using?

ejabberd-2.0.3   erlang:OPT 17

> What operating system (version) are you using?

Linux version 3.2.0-61-virtual  Ubuntu

> How did you install ejabberd (source, package, distribution)?
> source 
> 
> What did not work as expected? Are there error messages in the log? What

Hi,  expert
     I added a new mod in ejabberd to send http request to verify account id.

Code:

```
     application:ensure_started(inets),
     application:ensure_started(ssl),
     _Url = "http://10.0.3.8:33601/account/verify" ,
     Url = lists:flatten(_Url),
     httpc:request(put, {Url,[],[],[]}, [],[] ).
```

I verified this code in erlang terminate, and the http keep alive was working, and there is only one tcp connection.
    But in my mod, every http request , it started a new tcp connection, and it was not reused. So there were so many tcp connection to my account server and it cost too much tcp resource.
   How can I reuse the one TCP connection in ejabberd mod?  It works in erlang terminate,but not in ejabberd terminate.

> was the unexpected behavior? What was the expected result?

New tcp connection is established when new request. And there is so many tcp connection when there is so much http request to same server

Thank you very much! 
Wait for your reply.

**Comment by badlop** [comment]
According to the httpc documentation:
>  persistent connections without pipelining are used

But I guess, for that to work, you must perform the requests from the same Erlang process. This happens when you make several requests in an Erlang shell, but does not happen if your module performs this from time to time when another Jabber client asks for it, for example.

If I am right in this idea, how to keep the TCP connection alive? Keeping one (or several) Erlang processes just to perform those TCP queries.
