### ISSUE TITLE
How to compile with custom OpenSSL version statically?

### ISSUE THREAD

**Issue by rugk** [processone/ejabberd#1367]
How can I e.g. compile ejabberd with OpenSSL 1.1.0 statically (i.e. not using the OpenSSL version installed on the system)?

**Comment by rugk** [comment]
@zinid Any tips? Is there a parameter for the configure file I can use?

**Comment by zinid** [comment]
@rugk no idea, probably playing with environment variables, some of them should be passed to configure script of [fast_tls](https://github.com/processone/fast_tls)
Something like
```
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CFLAGS="-I/usr/local/opt/openssl/include/"
export CPPFLAGS="-I/usr/local/opt/openssl/include/"
```

**Comment by rugk** [comment]
Thanks for your tip. I'll try it out.

**Comment by rugk** [comment]
Thanks for your help, I got it compiled, but I don't know whether it really used the static OpenSSL version. Is there an command for `ejabberdctl` showing the used modules or so?

**Comment by zinid** [comment]
There should be fast_tls.so file created, you can try `ldd` on it or something like that.

**Comment by rugk** [comment]
Where should it be created (in the compile dir) or somewhere else?

**Comment by zinid** [comment]
```
$ cd ejabberd-source
$ ./configure && make
$ ls deps/fast_tls/priv/lib
fast_tls_drv.so  p1_sha.so
```

**Comment by rugk** [comment]
Thanks. So it tells me this:

```console
$ ldd fast_tls_drv.so
	libssl.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0 (0xb6eed000)
	libcrypto.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0 (0xb6dc7000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6cd7000)
	/lib/ld-linux-armhf.so.3 (0xb6f4b000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6cc4000)
```

1.0.0 is the version of fast tls AFAIK, so I do not see the OpenSSL version directly. However is it right that the `/lib` dir shows me that Fast TLS is using it's own libraries?

**Comment by weiss** [comment]
> However is it right that the /lib dir shows me that Fast TLS is using it's own libraries?

No.  You could either set `LIBS` and/or `LDFLAGS` [appropriately][1], or just move OpenSSL's `.so` files out of the way during fast_tls compilation.  Of course, both solutions require `libssl.a` and `libcrypto.a` to be available, which depends on your distribution.

Either way, this is a usage question rather than an ejabberd bug, so I'll close this issue.  If you need additional help, you could ask on the [ejabberd mailing list][2], for example.

[1]: https://stackoverflow.com/questions/4156055/gcc-static-linking-only-some-libraries
[2]: http://lists.jabber.ru/mailman/listinfo/ejabberd
