### ISSUE TITLE
support all XEP expected by Conversations (android app)

### ISSUE THREAD

**Issue by falsefifth** [processone/ejabberd#1368]
"out of the box"?

**Comment by weiss** [comment]
XEP-0352 support is currently being worked on.  All other XEPs expected by Conversations are well supported by the last several ejabberd releases without additional modules.

I don't think they should all be _enabled_ "out of the box", though.  Things such as the MAM and HTTP(S) upload setup should be done consciously by the admin, due to their specific requirements and privacy implications.
