### ISSUE TITLE
Question: Does MUC/SUB require persistent rooms?

### ISSUE THREAD

**Issue by genexp** [processone/ejabberd#1385]
> What version of ejabberd are you using?

latest

> What operating system (version) are you using?

Ubuntu Xenial

> How did you install ejabberd (source, package, distribution)?

ProcessOne distribution

We use SQL to store history, and other bits of information generated by eJabberd.  We plan to use it to store subscriptions as well.  Our rooms are all set to temporary, but each rooms name is deterministic.  When everyone leaves a room, the room is destroyed, however, when the same user reconnects the room is recreated with the same name.

We'd like to understand more how subscriptions work with temporary rooms.  IF we save subscriptions in SQL, leave the room to temporary, the data will persist even after the room process is stopped.  When a user joins a new room with the exact same JID, will the new room use the same subscriptions?  Is there a way to reload them from SQL if not?

We'd like to avoid the need for permanent rooms, as we create hundreds of thousands of them and they cause a significant performance issue (32gb nodes were dying daily), while leaving them set to temporary keeps ejabberd at a cool 5% of memory :)

**Comment by badlop** [comment]
The list of subscribers is kept in the room process state for all rooms. For persistent rooms, which are stored in the muc_room Mnesia or SQL tables, the field 'subscribers' is filled accordingly. So, the subscriptions are not kept in an independent table, it's just another record in an existing table, and you can't separate recovering subscriptions from persistence, because they aren't independent steps when creating a room.

A solution is that you take care to store subscriptions yourself for temporary rooms. The necessary changes in the source code I can think are:
1. Create a custom table that stores for each roomjid the list of subscribedjids.
2. In mod_muc_room:store_room/1 function, when room is temporary it does nothing. Add code so it stores the list of subscribers in your table
3. In destroy_room/2, when room is temporary it does not remove it from database. Add code so it removes the entry from your table.
4. In init function for temporary rooms, get your list of subscribers and use it too feed the new room. Example code for this:
```
diff --git a/src/mod_muc_room.erl b/src/mod_muc_room.erl
index 5b00054..821a5e6 100644
--- a/src/mod_muc_room.erl
+++ b/src/mod_muc_room.erl
@@ -108,6 +108,24 @@ start_link(Host, ServerHost, Access, Room, HistorySize, RoomShaper, Opts) ->
 %%% Callback functions from gen_fsm
 %%%----------------------------------------------------------------------
 
+get_subscribers_stored(Room) ->
+    Names = get_subscribers_sql(Room),
+    List = [make_sub(Name) || Name <- Names],
+    {subscribers, List}.
+
+%% TODO: Get this from database
+get_subscribers_sql(Room) ->
+    [<<"user2">>, <<"user3">>].
+
+make_sub(Name) ->
+    {jid:make(Name,<<"localhost">>,<<"">>),
+     <<"mynick">>,
+     [<<"urn:xmpp:mucsub:nodes:messages">>,
+      <<"urn:xmpp:mucsub:nodes:affiliations">>,
+      <<"urn:xmpp:mucsub:nodes:subject">>,
+      <<"urn:xmpp:mucsub:nodes:config">>]
+    }.
+
 init([Host, ServerHost, Access, Room, HistorySize,
       RoomShaper, Creator, _Nick, DefRoomOpts]) ->
     process_flag(trap_exit, true),
@@ -119,7 +137,7 @@ init([Host, ServerHost, Access, Room, HistorySize,
 		   jid = jid:make(Room, Host, <<"">>),
 		   just_created = true,
 		   room_shaper = Shaper}),
-    State1 = set_opts(DefRoomOpts, State),
+    State1 = set_opts([get_subscribers_stored(Room) | DefRoomOpts], State),
     store_room(State1),
     ?INFO_MSG("Created MUC room ~s@~s by ~s",
 	      [Room, Host, jid:to_string(Creator)]),
```

**Comment by genexp** [comment]
Thanks @badlop this is absolutely wonderful.  We'll open source the changes and reference the ticket.

/cc: @tquackenbush

**Comment by Polidore22** [comment]
@badlop One more question related to this if you have a sec!

We want to have a module that is able to capture messages sent to these room subscribers when they are offline. Is there a hook for this? Will they be sent as normal offline messages?

We wrote a custom module for push notifications for one to one offline messages (with the offline hook) that works great and we're trying to do something similar for certain MUC rooms.

Thank you!

**Comment by badlop** [comment]
> Is there a hook for this?

From what I see, none specific for mucsub notifications sent to offline subscribers.

> Will they be sent as normal offline messages?

From my test, yes.

**Comment by genexp** [comment]
Thanks again!  We'll open source _all_ the things :)
