### ISSUE TITLE
question: mod_http_upload

### ISSUE THREAD

**Issue by xi1976github** [processone/ejabberd#1386]
> What version of ejabberd are you using?
16.09
> What operating system (version) are you using?
Linux alarmpi 4.1.12-1-ARCH #1 PREEMPT Tue Oct 27 19:16:04 MDT 2015 armv6l GNU/Linux
> How did you install ejabberd (source, package, distribution)?
package from arch-aur
> What did not work as expected? Are there error messages in the log? What
following error:
2016-11-20 16:22:37.643 [error] <0.467.0>@mod_http_upload:handle_info:383 Got unexpected info: {route,{jid,<<"user1">>,<<"myserver.com">>,<<"Thunderbird">>,<<"user1">>,<<"myserver.com">>,<<"Thunderbird">>},{jid,<<"user2">>,<<"myserver.com">>,<<>>,<<"user2">>,<<"myserver.com">>,<<>>},{xmlel,<<"presence">>,[{<<"type">>,<<"unavailable">>}],[]}}

my config is:

    -
      port: 5443
      module: ejabberd_http
      request_handlers:
        "upload": mod_http_upload

    mod_http_upload:
      host: "myserver.com"
      docroot: "/srv/http/upload"
      put_url: "http://@HOST@:5443/upload"
      access: local

I expect to transfer files from conversations or gajim via http upload.
Any ideas? 
Thank you

**Comment by weiss** [comment]
host: "myserver.com"

Removing that line will fix your issue.

**Comment by ar4121** [comment]
@weiss 
I know this issue is closed, I'm attempting to get my config figured out and resolve some issues using this module.  

Would you mind explaining why removing that line will fix the issue above?  I am having a similar issue, and notice that in the logs, when you comment the 
`host: "myserver.com"`
it does work. However, the server seems to then default to the lserver "upload.myserver.com" according to the logs at least.  
So does the upload need to be on another subdomain?
When you do this, do you need to add a dns entry for "upload.myserver.com"?  Or is this an example of when s2s_route_subdomains is needed?

If you want, I can open a new issue, but I'm attempting to do as much as I can.

**Comment by weiss** [comment]
> So does the upload need to be on another subdomain?

Yes, this service needs a dedicated JID (just like e.g. MUC or PubSub) so that stanzas can be addressed to it.

> When you do this, do you need to add a dns entry for "upload.myserver.com"? 

Only if you want to allow remote users to use your upload service.  Your local server doesn't perform a DNS lookup for routing stanzas to "upload.myserver.com".

**Comment by ar4121** [comment]
Thanks!!!

Should these have their own SRV records then?

**Comment by weiss** [comment]
> Should these have their own SRV records then? Probably no as well, since it doesn't preform any lookup at all

Right, no records required.  (If you *did* want to allow remote users to talk to your upload service, a CNAME `upload.myserver.com -> myserver.com` would do the trick, but you *could* use SRV records instead.)
