### ISSUE TITLE
nick-change presence is not reflected if both old and new nicks are already used.

### ISSUE THREAD

**Issue by cburschka** [processone/ejabberd#1392]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

debian jessie

> How did you install ejabberd (source, package, distribution)?

distro (ejabberd 16.09-2)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

1. Create two client instances (same account) and send a presence to `test@conference.example.org/nick1` from both.

2. Create a third client instance (same account) that sends a presence to `test@conference.example.org/nick2`.

3. From one of the first two clients, attempt to change your nickname to `nick2` by sending a presence to `test@conference.example.org/nick2`.

Expected: There is no `unavailable` presence (as the old nick remains active) but the client that sent the nick change receives a reflected presence from `test@conference.example.org/nick2` with a 110 status code to acknowledge the nick-change.

Actual: There is no response at all. The only way to tell that the server has received the presence is to send a groupchat message, and see it come back from `nick2` instead of `nick1`.

This only happens when both nicks are in use by other resources. For example, if the old nick isn't used anymore, then you correctly get an unavailable *and* a new presence, regardless of whether the new nick is already in the room.

**Comment by badlop** [comment]
Support to use the same nick in a room by the same account from two different resources is bordering the XEP, and supported just because a kind person wrote the patch to support that feature. It is to be expected that there are more edge cases and problems related to that feature. I don't expect the problem you mention to attract more interest, so I'll close the ticket. You can reopen if you are able to find a solution, or any other relevant information.
