### ISSUE TITLE
Question : How to connect to GCM/FCM

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1400]
How do you S2S connect to GCM on 5269 for persistant xmpp connection ?
S2S out does not provide any direct api to connect without statedata / existing c2s session .

**Comment by weiss** [comment]
Your question makes no sense to me.  I'm not aware of GCM offering an XMPP s2s interface.

I found e.g. [this GCM module][1] on GitHub, but I haven't tested it.

[1]: https://github.com/mrDoctorWho/ejabberd_mod_gcm

**Comment by nOmi7** [comment]
@weiss  https://firebase.google.com/docs/cloud-messaging/server
says you can connect via XMPP for push notifications

**Comment by weiss** [comment]
Ah, FCM.  This is a new API that you can use on top of an XMPP c2s connection, see _Implementing the XMPP connection server protocol_ in the document your referenced.  I'm not aware of an existing implementation, and I doubt the fact that it uses XMPP is of any help to you.  Compared to GCM, this API offers additional features which you probably don't need.

**Comment by nOmi7** [comment]
even if there is something for GCM is ok for me start with @weiss  i need to know how to connect to GCM using XMPP
currently i get error in connection

Trying to open s2s connection: swinnyp.co.in -> gcm.googleapis.com with TLS=true
21:34:56.571 [debug] open_socket: {<<"swinnyp.co.in">>,<<"gcm.googleapis.com">>,true,false}
21:34:57.873 [debug] srv lookup of 'gcm.googleapis.com' failed: nxdomain
21:34:58.077 [debug] inet of gcm.googleapis.com resolved to: [{74,125,200,188}]
21:34:58.077 [debug] s2s_out: connecting to {74,125,200,188}:5236
21:34:58.209 [debug] Received XML on stream = <<21,3,1,0,2,2,70>>
21:34:58.209 [debug] Error in gen_tcp:send: {error,closed}
21:34:58.209 [debug] terminated: {normal,wait_for_stream}

**Comment by weiss** [comment]
> even if there is something for GCM is ok for me start with

The only suggestion I currently have is trying out the third-party module I mentioned above.  Apart from that, the Business Edition has GCM support.

**Comment by nOmi7** [comment]
Business Edition does connection over HTTP or XMPP ?

**Comment by weiss** [comment]
I don't know.  Why do you care?  I think the main advantage of using XMPP is that it's bidirectional, i.e. the client can send back messages to the server *via GCM*.  An XMPP client doesn't need that, because it would just send messages to the XMPP server directly.

You sound a bit as if you could open an XMPP *s2s* connection to Google, and as if that would somehow magically generate push notifications.  That's not how it works.

**Comment by nOmi7** [comment]
actually i thought this is how it works ..
Client opens connection to ejabberd server --- ejabberd in trun open s2s permanant connection to GCM @ 5236  any oflline message then is sent by peer is then directed over s2s to GCM which then pushes to offline client.

thanks @weiss  ill try to do more home work on this may be i am confused ...

**Comment by weiss** [comment]
Google offers a JSON API, and you can access this API via HTTP or via an XMPP c2s (not s2s) connection.  The module I mentioned [above][1] uses that API.

Also note that generating notifications requires credentials that Google will only give you for apps you published on the Play Store yourself.

[1]: https://github.com/processone/ejabberd/issues/1400#issuecomment-263607976

**Comment by andreabenini** [comment]
I have developed a custom module for GCM/FCM notifications to google. I'm guess there're no XMPP connections (c2s/s2s) available from them, as @weiss noted there's just a documented json api (http) you can use to talk with them. You need to store your server key (got from google api console) and keep client public keys in a table in order to push info to them.
XEP-0357 is nice but unfortunately it lacks information and a possible implementation on the server side seems to be vague and it's left to your own decisions.
There's a similar problem with Apple devices (IOS) where you need to talk to Apple by using http2 (spdy) or SSL [I have chosen ssl] but unfortunately no c2s/s2s in this case as well.

**Comment by nOmi7** [comment]
@andreabenini thanks I spent almost a day and did found out the FCM/GCM supports that .. 
I have started writing down custom module for ejabberd to talk to FCM / GCM using XMPP once complete will definately put for public for updates and improvements.
its faster than HTTP and you dont have to auth it again for all the request you can have 1000 concurrent connections long lived so that you dont compromise on speed and message delivering reliablity . Thanks @weiss  to confrim it was c2s that actually cleared manythings for me .

**Comment by nileshbacancy** [comment]
Hello
any one know how to FCM pushnotification in ejabberd same like below GCM link:
https://github.com/joanlopez/ejabberd-mod-gcm
https://github.com/joanlopez/ejabberd-mod-gcm/blob/master/src/mod_gcm.erl

Please help me if there is any mod_fcm.erl file
I have installed 16.09 ejabberd version.

**Comment by andreabenini** [comment]
@nileshbacancy I'm still on ssl for Google (GCM) and Apple as well. I haven't ported nor developed new things for FCM but I guess I need to do that when GCM becomes obsolete. Same goes with SSL on Apple side, they're pushing you to adopt SPDY/HTTP2/...   My work started from (https://github.com/mrDoctorWho/ejabberd_mod_gcm), Dr.Who [cool name] practically implemented something to circumvent XEP 0357 lacks on server side where much is left to sysadm willingness.
