### ISSUE TITLE
ejabberd info required

### ISSUE THREAD

**Issue by PH-F** [processone/ejabberd#1488]
We need 1-on-1 chat, group chat, photo/file support etc. All the basic stuff a messenger has.
I also want to see my message archive from all devices: iOS,Android and Web. 
And it should be secure.
Is this all possible with ejabbard?

Last question, what if we have 2 different applications on our server do we need to install ejabberd twice?

I hope somebody can give me some advice. Thx!!

**Comment by badlop** [comment]
> We need 1-on-1 chat, 

Yes, that is basic in Jabber/XMPP

> group chat, 

Yes, this is MUC, implemented in mod_muc

> photo

If you mean user's photo or avatar, I think it is supported by mod_vcard

> /file support etc. All the basic stuff a messenger has.

Clients can send files between them, ejabberd does not need to implement anything for this.

> I also want to see my message archive from all devices: iOS,Android and Web.

If you enable mod_mam, clients that support MAM can query it.

> And it should be secure.

ejabberd supports encryption client-to-server and server-to-server. In addition to that, clients can use client-to-client encryption if they implement it, of course.

> Last question, what if we have 2 different applications on our server do we need to install ejabberd twice?

Of course not needed. You install ejabberd in the server machine, and the people connect to it using their clients, mobile clients, web clients from everywhere.

If you have several domains like a company "ph.com" and independently an organization "werule.org", then you can use the virtual hosts support in ejabberd: https://docs.ejabberd.im/admin/configuration/#host-names

**Comment by zinid** [comment]
I would like to clarify some points:
> Yes, this is MUC, implemented in mod_muc

Although there is groupchat support in ejabberd, you cannot build Whatsapp-like groupchat without using additional non-standard extensions (such as mucsub, which ejabberd supports though).

> Clients can send files between them, ejabberd does not need to implement anything for this

This is not quite true, because the current trend is to share file via HTTP upload. ejabberd supports this in `mod_http_upload` module.

> clients can use client-to-client encryption

Make no mistake: client-to-client encryption (aka end-to-end encryption, or 'e2e' for short) introduces several constraints: you will not be able to search through server archived messages, or, what's worse, if you lose you private key (for example, if you lose a phone) then access to archived messages will be lost (even though you still have access to the account), because you won't be able to decode messages. You should consider these before you make a decision to use e2e.

**Comment by PH-F** [comment]
Thx for your answers, I'm very exited to start using ejabberd for our messenger!.
I will install it and if have any questions I will post them.

**Comment by zinid** [comment]
> if have any questions I will post them

Sure. But please create a new issue for this ;)
I'm closing this one.
