### ISSUE TITLE
Best practice for iq_handlers

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1501]
> What version of ejabberd are you using?
17.01.45

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
src

IQDisc describes how concurrent IQ are handled:
    no_queue: no thread is created to run the handler
    one_queue: one thread is dedicated to run the handler
    {queues, N}: N threads are created to run the handler
    parallel: one thread is created for each IQ received

While above description gives idea on concurrency I would like to the know usecases of above handlers 
for eg 
I have a custom IQ .. it does custom operations like setting profile pics , changing group names , adding members getting URL webpage preview etc.... based on IQ_Type.

In this case what should be my approach for add_iq_handler - IQDisc?

If I Use parallel will it improve the performance but consume more ram . if i use N thread on what basis should i choose the value of N 

Merci.

**Comment by zinid** [comment]
50 is pretty good for almost any task and doesn't have memory impact.

**Comment by zinid** [comment]
Also, make sure multiple handlers will not create race conditions. In some rare cases there can be a problem with concurency. In order to figure this out just check if the handler doesn't need to share a single resource. It it does, make sure the access is serialized (via transaction or something like that) or operations are atomic (like basic ets operations).

**Comment by nOmi7** [comment]
@zinid thanks for the info however in most of the ejabberd out of the box modules either its Noqueu or oneque I wanted to the criteria on which this is chosen why they are diff in diff modules 
Also when I choose 50 does it not matter how many cpu I have or impact of number vs cpu

**Comment by zinid** [comment]
> I wanted to the criteria on which this is chosen why they are diff in diff modules

This is mostly for historical reasons. Looking at the code at the moment, I don't see a big difference between `no_queue` or `one_queue`.

> Also when I choose 50 does it not matter how many cpu I have or impact of number vs cpu

Even if you have more than 50 CPUs, setting this value to more than 50 will have performance impact (on ejabberd community edition), because picking the worker from the queue has `O(N)` complexity. The same is true for sql pool by the way.

From our practice (high loaded productions systems): we always set `{queue, N}` for mod_privacy or mod_roster modules, e.g. for the modules performing a lot of database lookups. Furthermore, it's almost pointless to set this `N` more than `sql_pool_size`, because messages will be accumulated in sql processes instead: so you move bottleneck from from iq_handlers queues to sql processes queues. Simply put, I don't think creating pool of handlers for modules which simply compute some values (without database lookups) make sense.

**Comment by nOmi7** [comment]
Awesome so now i get the point .. to summerize if the IQ does some db work then its good to have parallelism with N = number of cores / sql_pool_size  however if module is just doing some no-db work mostly computational queuing would not make much of the diff .

**Comment by zinid** [comment]
Right
