### ISSUE TITLE
question: user_send_packet hook and module state

### ISSUE THREAD

**Issue by andreabenini** [processone/ejabberd#1507]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

AMD64

> How did you install ejabberd (source, package, distribution)?

installer

I'm using the `user_send_packet` hook to detect what the user does with an handler like this:
```
myMessageHandler(Packet, _C2SState, _Source, _Destination) -> Packet.
```
`Source` and `Destination` are `#jid` records, `Packet` is `#xmlel` record (mostly) and C2SState is of type `#state` (where is it defined ?). Is it possible to get module current state (what init/2 returns) inside this kind of handler ?
I know I can raise a `gen_server:call/2` to myself inside `myMessageHandler/4` to get something handled from a `handle_call/3` functions but is there a better way or a fast method to achieve it ?
I need to manipulate Packet with some params coming from the my module state

**Comment by zinid** [comment]
If you only want to get module's option, then you can use `gen_mod:get_module_opt()` function (see `gen_mod.erl` for details). Otherwise you, indeed, need to craft `gen_server:call()` or store your values in ETS table.

PS. `#state{}` is defined inside `ejabberd_c2s.erl`. This has been changed in current `master` branch: the record is replaced by a map().

**Comment by andreabenini** [comment]
Thanks,
replies are helpful and fast, as usual.
I guess I'll leave the `#state{}` where it is, I already have a lot of mess for the planned migration and I guess I'll use something else to avoid other legacy troubles. I'll take a look at the `get_module_opt()`, there're many samples around but I have always skipped them (rookie's fault)
