### ISSUE TITLE
Commands documentation lack arguments when policy=user

### ISSUE THREAD

**Issue by themaverick777** [processone/ejabberd#1514]
> What version of ejabberd are you using?

17.01

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Using deb package

**Documentation** update required for **get_roster** api:

According to the documentation from https://docs.ejabberd.im/developer/ejabberd-api/admin-api/
When calling get_roster, it does not make sense, since there is no argument to be supplied
and hence I get the response:
> "Missing POST data"

When checking the logger, I get:
> 2017-02-04 13:29:11.558 [debug] <0.2060.0>@mod_http_api:process:176 Bad Request: no data

So a simple trial and error landed me supplying the arguments, "user" and "server" and I get the expected results. Please kindly update the documentation in case anyone stumbles into the same problem.

:-)

**Comment by badlop** [comment]
That documentation page is built by ejabberd_commands_doc.erl from the command definition. And there are three commands that require arguments but they aren't declared, because they are of "policy = user", which implicitly means they require user and Host as arguments.

This affects commands user_resources, get_roster and get_offline_count

**Comment by badlop** [comment]
Fixed the source code that generates the documentation. I guess the page online will be updated for the next release.
