### ISSUE TITLE
MUC room membership revocation behavior must not depend on kicked user's status

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1577]
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

CentOS Linux release 7.2.1511

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When the MUC room owner in a members-only room revokes membership of an offline user, ejabberd sends a `message` stanza instead of a `presence` stanza.

[XEP-0045, 9.4 Revoking Membership](https://xmpp.org/extensions/xep-0045.html#revokemember) states:

> The service MUST then send updated presence from this individual to all occupants, indicating the loss of membership by sending a presence element that contains an `<x/>` element qualified by the 'http://jabber.org/protocol/muc#user' namespace and containing an `<item/>` child with the 'affiliation' attribute set to a value of "none".
> […]
> If the room is members-only, the service MUST remove the user from the room, including a status code of 321 to indicate that the user was removed because of an affiliation change, and inform all remaining occupants

When the user who's being kicked is online everything behaves according to the spec, i.e. ejabberd sends a presence stanza to all occupants (including the kicked user):

```xml
<presence from="some_room@conference.vhost/kicked_user" type="unavailable"
    to="some_user@vhost/resource">
  <x xmlns="http://jabber.org/protocol/muc#user">
    <item affiliation="none" role="none" jid="kicked_user@vhost/resource">
      <actor nick="owner"/>
    </item>
    <status code="321"/>
  </x>
</presence>
```

However, when the kicked user is offline, ejabberd only sends a message stanza to all occupants:

```xml
<message from="some_room@conference.vhost" to="some_user@vhost/resource" id="some_id">
  <x xmlns="http://jabber.org/protocol/muc#user">
    <item affiliation="none" role="none" jid="kicked_user@vhost"/>
  </x>
</message>
```

Expected behavior: The server sends a presence stanza regardless whether the user is online or offline, as stated in the XEP.

**Comment by badlop** [comment]
> Expected behavior: The server sends a presence stanza regardless whether the user is online or offline, as stated in the XEP.

Are you sure the XEP says that? It says so if reading only 9.4, but if you read the other sections related to revoking affiliations, I suspect there's an inconsistency in the XEP. Let's review the sections for revoking member, owner and admin:
 
* In 9.4 revoking member, it simply says (as you pointed):
> The service MUST then send updated presence

* In 10.4 revoking owner, it adds a condition, but says nothing when the condition isn't met!
> If the user is in the room, the service MUST then send updated presence

* In 10.7 revoking admin, it adds that condition, and also says what to do when the condition isn't met:
> If the user is in the room, the service MUST then send updated presence
> If the user is not in the room, the service MAY send a message

So, considering those undefinitions, ejabberd behaves in all cases following the more detailed instructions, because the XEP itself leaves some cases without explanation.

On the other hand, does it make sense to receive presence from a non-existing occupant?
