### ISSUE TITLE
Usage of new ets_cache api

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1694]
> What version of ejabberd are you using?
17.x

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
src

Not able understand how to insert into cache.
creating cache using 
   ets_cache:new(push_token,cache_opts()).
but not able to understand how to insert into this cache ? can you please help ?

There is no function to update the cache element can this be taken as feature request to update the cache content for an Id . for now way is to do lookup then delete and then insert again.
cache_missed = false is not updating the content for the primary key.

**Comment by zinid** [comment]
The new value is inserted automatically on lookups (via `ets_cache:lookup/2,3`). There are `insert/3,4` functions in recent `ets_cache` version, however, its usage is not recommended. The problem with explicit inserts is cache atomicity/consistency: you need somehow to serialize access to the cache in order to avoid race condition (between lookup-insets, inserts and deletes), and since the new cache is designed to be efficient, thus, only lookups and deletes are to be used.
