### ISSUE TITLE
Hint/Suggestion on developing modules (loading/reloading/testing)

### ISSUE THREAD

**Issue by andreabenini** [processone/ejabberd#1782]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

amd64.CentOS 6.x

> How did you install ejabberd (source, package, distribution)?

binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,
I'm just looking for an hint/suggestion from your daily experience. I have several xmpp domains inside the same host, few of them are production ready domains and few others are for debugging purposes. I'm using the remote host from my workstation with git+hooks+bash scripting (No C.I. tools or containers)
Let's say I'm developing mod_XX and I'd like to port it to this host, here are my common steps:
- transfer it on remote with git, use hooks and few scripts to copy it in a specified dir
- check it (ejabberdctl module_check mod_XX)
- uninstall previous version (ejabberdctl module_uninstall mod_XX)
- install new one (ejabberdctl module_install mod_XX)

And my module is stopped and reloaded as requested. I still have a local machine where I make some tests (experimental features, alpha testing, ...) but I usually install production ready modules there to make further tests (with real data) on these debug domains only.
Is there a way to install/test a module on a specific domain only without affecting others ?
I can avoid to use uninstall/install method but how can I load my code just in one xmpp domain ? erlang hot code loading ? As a developer I change code often and sometimes I'd like to test (or debug) on a specific xmpp domain without affecting others. Any hints or suggestions ?

Thanks
Ben

**Comment by badlop** [comment]
> how can I load my code just in one xmpp domain ? 

Code loading is an erlang matter; xmpp domain is an ejabberd thing. As those concepts operate in different levels, there isn't relation between them and I doubt you can pair them magically... you'll have to do it explicitly.

While the module is in test phase, you can call it mod_whatever_test, use whatever_test table names, _test process names, etc... so that module can live together with its ancestor mod_whatever. Then enable each one in a different vhost.

Or you could setup two ejabberd nodes in the machine, one with production vhosts, and the other with development vhosts and modules.

**Comment by andreabenini** [comment]
Thanks, you gave me some interesting hints.
There's no secret sauce between ejd and beam but I can mix something from the language and mod_whatever approach to solve it.
