### ISSUE TITLE
Broken links and doc

### ISSUE THREAD

**Issue by andreabenini** [processone/ejabberd#1783]
On page https://docs.ejabberd.im/developer/hooks/ I guess you have something broken.
Probably your doc generator is missing something and page goes wrong: no content and broken DIVs.
Tested out with all major browsers: Chrome/Chromium/Firefox/Safari

it's a low priority task but somewhat important
Cheers

**Comment by andreabenini** [comment]
Referer https://docs.ejabberd.im/developer/extending-ejabberd/modules/

**Comment by badlop** [comment]
The links to Hooks and IQHandler in that referer page return me 404 not found. In fact, those two pages were deleted in March this year because they were obsolete. I wonder how can you view it nowadays. The useful content is now in https://docs.ejabberd.im/developer/guide/#adding-new-functionality

Anyway, as the Hooks page (and the other one) no longer exist, the task now is to remove those two broken links in the referer page.

**Comment by andreabenini** [comment]
From: 

- Ejabberd for developers (https://docs.ejabberd.im/developer/)
- Extending ejabberd link on the left (https://docs.ejabberd.im/developer/extending-ejabberd/)
- Modules development link on the left (https://docs.ejabberd.im/developer/extending-ejabberd/modules/)
- Event and Hooks link on the bottom page (https://docs.ejabberd.im/developer/hooks/)

and there it goes..
hope it helps

**Comment by badlop** [comment]
Ok, thanks. I've fixed in doc's git those two links to point to https://docs.ejabberd.im/developer/guide/#adding-new-functionality. The fixed html will be online in the next html compilation, don't worry if right now it's still old.
