### ISSUE TITLE
mod_http_upload - service url

### ISSUE THREAD

**Issue by molochmike** [processone/ejabberd#1786]
> What version of ejabberd are you using?
17.04

> What operating system (version) are you using?
CentOS 6.5

> How did you install ejabberd (source, package, distribution)?
Binary installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi,

I just create a bucket on aws s3 and give the bucket a name as xmppstore.  I setup the permission to the bucket to allow read and write for public.

I went into ejabberd.yml config file under "mod_http_upload" module section to add in service_url and then i define the endpoint for the s3 into this location.  Later i got some error and i temporary disable "put_url" and "get_url" line.  However I still encounter problem.

The error i obtain are as below.

2017-06-19 07:33:34.392 [error] <0.26661.1>@mod_http_upload:create_slot:613 Can't parse data received for mikegajim@localhost/Gajim from <https://s3-ap-southeast-1.amazonaws.com/xmppstore>: [<<"<?xml version=\"1.0\" encoding=\"UTF-8\"?>">>,<<"<ListBucketResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Name>xmppstore</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>sample.jpg</Key><LastModified>2017-06-19T07:19:10.000Z</LastModified><ETag>&quot;8613ffdf686a00456c6bae96bb800410&quot;</ETag><Size>28084</Size><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>">>]

@weiss has mention before that to use django framework to build in order to support media on aws s3 but then due to unfamiliar of me on django, is there other alternatives that I can do to allow media to be upload and download from aws s3?

**Comment by weiss** [comment]
> @weiss has mention before that to use django framework to build in order to support media on aws s3 but then due to unfamiliar of me on django, is there other alternatives that I can do to allow media to be upload and download from aws s3?

If you specified e.g. `service_url: "http://localhost:1234/upload.php"` and a client requests a slot, `mod_http_upload` will issue an HTTP GET request such as:

    http://localhost:1234/upload.php?jid=bob%40example.com&name=cat.jpg&size=512&content_type=image%2Fjpeg

That's all that happens.  You'd have to write the `upload.php` script yourself.  You might or might not be able to implement AWS S3 storage that way (I never used it, so I don't know the requirements).

If you want to have a go at writing such a script: In order to accept the request, the script must return an HTTP status code of 200 and two lines of text/plain output.  The first line is forwarded to the XMPP client as the PUT URL, the second line as the GET URL.

Forget the [Django thing][1].  I just mentioned it as an example of such a "script" which handles requests against the `service_url`.  You can simply write your own instead.

[1]: https://github.com/mathiasertl/django-xmpp-http-upload
