### ISSUE TITLE
Add support for XEP-0308

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1801]
Are there any plans to implement [XEP-0308: Last Message Correction](https://xmpp.org/extensions/xep-0308.html)?

**Comment by weiss** [comment]
This is an extension for clients, the server is not involved with that.

**Comment by marcphilipp** [comment]
Well, shouldn't the message be changed in the MAM archive?

**Comment by weiss** [comment]
No.

**Comment by weiss** [comment]
> shouldn't the message be changed in the MAM archive?

No.  I think this should become obvious from reading the extension.  See the [Business Rules][1] or the [Security Considerations][2], for example.

Apart from that, MAM can't collapse the original message and the correction(s) into a single (corrected) message, because clients who already received the original message should retrieve the correction(s) from MAM.

[1]: https://xmpp.org/extensions/xep-0308.html#rules
[2]: https://xmpp.org/extensions/xep-0308.html#security

**Comment by marcphilipp** [comment]
Ok, got it. Thanks for the explanation!
