### ISSUE TITLE
/etc/ssl/certs as a ca_path on CentOS doesn't work

### ISSUE THREAD

**Issue by sander85** [processone/ejabberd#1833]
> What version of ejabberd are you using?
17.06

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

Package from Your homepage.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

2017-07-04 22:06:07.638 [warning] <0.348.0>@ejabberd_pkix:check_ca_dir:386 CA directory /etc/ssl/certs doesn't contain hashed certificate files; configuring 'ca_path' option might help
On CentOS 7 there is no such hashed certificates. CentOS is using a bundle file. You can see more info @ https://www.happyassassin.net/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/

It would be nice if I could point ca_path to that bundle file.

**Comment by zinid** [comment]
The problem with a bundle file is that it's not very effective to parse it.
Also, I think new versions of ca-certificates packet in CentOS provide hashed certfiles, see this link: https://www.happyassassin.net/2015/01/14/trusting-additional-cas-in-fedora-rhel-centos-dont-append-to-etcpkitlscertsca-bundle-crt-or-etcpkitlscert-pem/

**Comment by sander85** [comment]
This post shows how to add new certs into bundle. c_rehash is suggested for CentOS 5, that's a legacy system. There are no hashed files on my CentOS 7.

**Comment by zinid** [comment]
Anyway, for s2s SASL EXTERNAL authentication you can set `s2s_cafile` top-level option pointing to your bundle.

**Comment by zinid** [comment]
I will take a look into CA files location a bit later.

**Comment by zinid** [comment]
For the record, this requires [fast_tls](https://github.com/processone/fast_tls) update and we don't want to do this in 17.08, so this is scheduled to 17.09.

**Comment by sander85** [comment]
@zinid Thanks for the update!

**Comment by syntafin** [comment]
CentOS 7, 17.09, problem is still here.

**Comment by vladuk** [comment]
Hey, 
the same issue on CentOS7, ejabberd-17.11-0 

2017-11-27 06:58:51.069 [warning] <0.274.0>@ejabberd_pkix:check_ca_dir:551 CA directory /etc/ssl/certs doesn't contain hashed certificate files; configuring 'ca_path' option might help
2017-11-27 06:58:51.136 [error] <0.279.0> backend port not found: inotifywait
2017-11-27 06:58:51.142 [warning] <0.274.0>@ejabberd_pkix:build_chain_and_check:363 Failed to validate certificate from /opt/ejabberd_online/conf/ejabberd.pem: certificate is signed by unknown CA

- letsencrypt certificate could not be verified due to unknown CA 
in config tried wildcard from let'sencrypt dir and concatination to single pem file (key,cert and chain) 

certfiles:
 - "/opt/ejabberd_online/conf/ejabberd.pem"
## - "/etc/letsencrypt/live/<domain>.com/*.pem"

with above live dir permission fixed.

So, what part handles CA verification ?

**Comment by zinid** [comment]
> So, what part handles CA verification ?

In s2s code. So, you need to set `s2s_cafile` option and ignore the warning so far (it will be fix by 17.12).

**Comment by cromain** [comment]
@zinid i think this is completely covered now, right ?

**Comment by zinid** [comment]
@cromain yes, but not automated (still need to put `ca_file` in the config).
This can be done later though and is not urgent.
