### ISSUE TITLE
Connections to Google are broken

### ISSUE THREAD

**Issue by centromere** [processone/ejabberd#1942]
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

FreeBSD 11.0-RELEASE

> How did you install ejabberd (source, package, distribution)?

FreeBSD Ports

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The following error occurs when connecting to Google:

```
2017-08-14 07:33:16.866 [info] <0.436.0>@ejabberd_s2s_out:process_closed:161
 Failed to establish outbound s2s connection foo.com -> gmail.com:
 Stream closed by us: unsupported-version; bouncing for 28 seconds
```

**Comment by zinid** [comment]
Do you have `mod_s2s_dialback` loaded?

**Comment by centromere** [comment]
That was it, thank you.

**Comment by GigabyteProductions** [comment]
So, if I understand this correctly: Google's XMPP server is running weak authentication on the s2s port, so our servers close the Google-initiated connections out of lack of acceptable authentication, and enabling mod_s2s_dialback uses the idea that connections instead initiated from our servers to Google's servers is a valid form of authentication (based on the idea that DNS is secure or that things are not being intercepted at the IP level). Is this correct?

I just think this is an important thing to be aware of, since it does not validate that whatever DNS tells us to connect to, or whatever actually takes up the connection on the other end, is the intended server.

See: https://xmpp.org/extensions/xep-0220.html#intro-why
See: https://web.archive.org/web/20171126010922/https://xmpp.org/extensions/xep-0220.html#intro-why

**Comment by zinid** [comment]
So you're now aware, congrats
