### ISSUE TITLE
 【17.08】conf , bin and logs folder are not in the same application folder

### ISSUE THREAD

**Issue by jhaoheng** [processone/ejabberd#1943]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

ubuntu

> How did you install ejabberd (source, package, distribution)?

package
Linux x86 64-bits DEB PACKAGE

---
17.08 have two ejabberd folder
- `/opt/ejabberd`
- `/opt/ejabberd-17.08`

1. ejabberd.yml is set in `/opt/ejabberd/conf/ejabberd.yml`
2. start : `/opt/ejabberd-17.08/bin/ejabberdctl start`
   - ejabberd-17.08 have `./conf/ejabberd.yml`, but it look like unuseful.
3. and if i need to watch logs , must return to `/opt/ejabberd/logs`

Could make 17.07 and 17.08 ejabberd application have the same folder structure?
It will help us more clear and no confuse.
Thank you so much.

![screen shot 2017-08-15 at 10 34 44 am](https://user-images.githubusercontent.com/1822475/29300296-2b7703e8-81a7-11e7-92aa-e5d6f37fdc3f.png)

**Comment by cromain** [comment]
since 17.08, when installing as root (from rpm/deb) ejabberd's home is set to /opt/ejabberd and we put here runtime files (conf database and logs). /opt/ejabberd-17.08/database remains empty, /opt/ejabberd-17.08/logs contains only installation logs, /opt/ejabberd-17.08/conf keeps the default configuration for the record, but is not used anymore.

this change allows to be able to upgrade ejabberd without loosing your config and database. see #1828 for details.

If duplication of conf is confusing, we can remove /opt/ejabberd-xx.yy/conf

**Comment by cromain** [comment]
To avoid duplication of tickets, i close this one and keep discussion about conf duplication on #1971
