### ISSUE TITLE
[RIAK] OTP release 20 does not match required regex R15|R16|17|18|19

### ISSUE THREAD

**Issue by erdna1982** [processone/ejabberd#1957]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

debian:jessie

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I've customized the Dockerfile from rroemhild to the version 17.08 and while compiling i get the follwing error:

_==> ezlib (compile)
Compiled src/ezlib_sup.erl
Compiled src/ezlib_app.erl
Compiled src/ezlib.erl
Compiling c_src/ezlib_drv.c
==> meck (pre_compile)
==> meck (compile)
**ERROR: OTP release 20 does not match required regex R15|R16|17|18|19**
**ERROR: compile failed while processing /tmp/ejabberd/deps/meck: rebar_abort**
Makefile:90: recipe for target 'deps/.built' failed
**make: *** [deps/.built] Error 1**_

**Comment by zinid** [comment]
This is generated by riak-client dependency

**Comment by zinid** [comment]
As a work-around, if you don't need Riak, compile with `--disable-riak` flag.

**Comment by erdna1982** [comment]
:) Thx Zinid. That's how I'm gonna do it.

cheers
Andre

**Comment by zinid** [comment]
This should be fixed by 350827f8f425270b476ecef3ef0925ea07a3287c

**Comment by zinid** [comment]
The fix didn't help because of lack of `crypto:rand_bytes/1` in OTP20.0
I reopen the issue

**Comment by zinid** [comment]
There are more problems with Riak than I thought. The main problem is that you cannot compile Riak itself against OTP20, but some Erlang modules from ejabberd (e.g. `ejabberd_riak.beam`) are required to be added to the code path of Riak in order to perform map-reduce requests. However, older versions of Erlang don't understand BEAM files of OTP20.0.
This is a quite severe problem as any solutions I can think about are either hacky (e.g. always compiling `ejabberd_riak.erl` against OTP17-19) or complex (forking, fixing and maintaining Riak repositories).

**Comment by cromain** [comment]
We still package 17.09 with OTP19, so I suggest to remove this issue from 17.09 milestone as fix will not be easy.

**Comment by zinid** [comment]
Agreed. This Riak stuff requires more attention anyway.

**Comment by Neustradamus** [comment]
for information: http://www.erlang.org/news/115 :)

**Comment by zinid** [comment]
Riak support is removed so this issue is not relevant anymore.
