### ISSUE TITLE
Two Config folders after installation

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#1971]
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

CENTOS 7

> How did you install ejabberd (source, package, distribution)?

RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Now there are two ejabberd folders:
```
**/opt/ejabberd**
                       /conf
                       /database
                       /logs
                       .erlang.cookie
**/opt/ejabberd-17.08**
                       /bin
                       /conf
                       /database
                       /doc
                       /lib
                       /logs
```
What are them for? There are 2 confs, etc.
Which one should I use to change the configuration?
Any  advice?

**Comment by cromain** [comment]
since 17.08, when installing as root (from rpm/deb) ejabberd's home is set to /opt/ejabberd and we put here runtime files (conf database and logs). /opt/ejabberd-17.08/database remains empty, /opt/ejabberd-17.08/logs contains only installation logs, /opt/ejabberd-17.08/conf keeps the default configuration for the record, but is not used anymore.

this change allows to be able to upgrade ejabberd without loosing your config and database. see #1828 for details.

If duplication of conf is confusing, we can remove /opt/ejabberd-xx.yy/conf

**Comment by Emilio-Gonzalez** [comment]
Thanks, understood.
I suppossed that.

At the very beginning could be a bit confusing, but I think it's ok.

**Comment by cromain** [comment]
We'll keep it like it's now. I added a note in ejabberd's documentation
https://docs.ejabberd.im/admin/installation/#installing-ejabberd-with-binary-installer

**Comment by mmehrle** [comment]
I find it confusing as hell to be honest. Have been attempting to get ejabberd to run but configuration is a nightmare as some settings seem to be picked up in the ejabberd-xx folder and others in the ejabberd folder. You just don't deploy a distro with two config files - ever. And if you do then you make it extremely clear which is the active path for configuration.

You may sneer at criticism such as this but problems like these are exactly why XMPP/Jabber has remained relegated to the domain of nerds and perhaps a core group of die-hard sys admins. Installing ejabberd ought to include the basic configuration via queries instead of having to dig my way through pages of instructions and having to sort through duplicate conf files. My 2 cents for anyone who cares.
