### ISSUE TITLE
Document auth cache options

### ISSUE THREAD

**Issue by JDiPierro** [processone/ejabberd#1982]
The documentation says that `auth_use_cache` supersedes the old `extauth_cache` option but doesn't mention the `auth_cache_size`, `auth_cache_life_time`, or `auth_cache_missed` options.

**Comment by badlop** [comment]
Yes, right now only this is documented:
```
**`auth_use_cache: false|true`**:   Starting in *ejabberd 17.06*,
 caching has received a complete overhaul.
 Instead of `extauth_cache`, a set of new variables describes cache behaviour
 (see `auth_cache_missed`, `auth_cache_size` and `auth_cache_life_time`),
 and the default value is now `true`. Note that caching
 interferes with the ability to maintain multiple passwords per
 account. So if your authentication mechanism supports
 application-specific passwords, caching must be disabled.
```
This should be added, with the corresponding explanations:
```
**`auth_cache_missed: false|true`**:

**`auth_cache_size: Integer|infinity`**:

**`auth_cache_life_time: Milliseconds|infinity`**:

```

**Comment by zinid** [comment]
There is a bunch of cache options in ejabberd, but they follow the same pattern. Note that there are global options like `use_cache`, `cache_missed`, `cache_size` and `cache_life_time` which are used as fallback.
- `*_use_cache`: enable/disable cache. The default is `true`.
- `*_cache_missed`: whether or not to cache missed lookups. When there is an attempt to lookup for a value in a database and this value is not found and the option is set to `true`, this attempt will be cached and no attempts will be performed until the cache expires. Usually you don't want to touch it. Default is `true`.
- `*_cache_size`: a maximum number of items (not memory!) in cache. The rule of thumb, for all tables except rosters, you should set it to the number of maximum online users you expect. For roster multiply this number by 20 or so. If the cache size reaches this treshold, it's fully cleared, i.e. all items are deleted, and the corresponding warning is logged. You should avoid frequent cache clearance, because this degrade performance. The default value is 1000.
- `*_cache_life_time`: the time (in *seconds*) of a cached item to keep in cache. Once it's expired, the corresponding item is erased from cache. The default is 3600 (one hour).

**Comment by zinid** [comment]
Also, all these options can be changed in runtime, so don't be overthinking about them. Keep the defaults (i.e. configure nothing) and only change it if you see warnings.

**Comment by badlop** [comment]
Ok, I've added those explanations to the Guide's git repo, and referenced to them in the related modules. I guess it will be published for the next release.
