### ISSUE TITLE
Adding support for XEP-0333

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1988]
I'm wondering how to implement support for XEP-0333. From the discussion in #863, it could be implemented as a client-only protocol by using MAM to store and retrieve all chat markers (they would need to include the `store` hint). However, that would be really inefficient, in particular for MUC rooms with a lot of users as described by @weiss in https://github.com/processone/ejabberd/issues/863#issuecomment-162897253:

> FTR, my main concern with the suggestion was the idea of having the client that sent the original message extract the XEP-0333 status from his own outgoing message as returned by `mod_mam`. That's non-standard, and it's inefficient to have clients query the same set of MAM messages repeatedly just to get their current XEP-0333 status.

Thus, I think the server should only store the last chat marker for received, displayed, and acknowledged per user for each 1-on-1 chat and MUC room. I think that should be implemented on top of MAM to allow other users to retrieve their and other user's chat markers.

Would you store every chat marker for each category in the MAM archive, delete the obsolete ones when a new one comes in, or use a completely different approach?

**Comment by zinid** [comment]
Frankly, I don't understand the usage and why something needs to be stored in server.

**Comment by marcphilipp** [comment]
@weiss Would be great to also get your opinion on this. 🙂

**Comment by weiss** [comment]
The suggestion I [commented][1] on was to let `mod_mam` store the chat marker(s) you receive for an outgoing message *within* the outgoing message stanza.  That's a bad idea, I think.

Now you're suggesting to let chat markers work as usual from the client's point of view (i.e. the client won't notice that the server is messing with them), but `mod_mam` would drop superseded chat marker stanzas in order to save some DB storage space and/or reduce the MAM traffic, right?

Sounds like a hacky alternative to a proper extension for server-side syncing of chat states; but it should work, yes.

> Would you store every chat marker for each category in the MAM archive, delete the obsolete ones when a new one comes in, or use a completely different approach?

Messing with this within the proper MAM table sounds potentially expensive to me, so I'd use a separate table for this.

[1]: https://github.com/processone/ejabberd/issues/863#issuecomment-162897253

**Comment by marcphilipp** [comment]
> Now you're suggesting to let chat markers work as usual from the client's point of view (i.e. the client won't notice that the server is messing with them), but `mod_mam` would drop superseded chat marker stanzas in order to save some DB storage space and/or reduce the MAM traffic, right?

Yes, exactly.

> Sounds like a hacky alternative to a proper extension for server-side syncing of chat states; but it should work, yes.

XEP-0333 is very vague on how to implement a proper extension for server-side syncing of chat states. On the one hand, it advises to use MAM "to support offline updating of chat markers". On the other hand, it recommends that "to avoid sending redundant Chat Markers while retrieving archived messages, Chat Markers SHOULD only be sent after retrieving the most recent message for a chat".

What if we wouldn't store chat markers in the MAM archive but append them to the MAM result or the last page of the results? Could this be achieved by hooking into `mod_mam`?

One thing, XEP-0333 is very clear about, is that the server needs to advertise that it supports `urn:xmpp:chat-markers:0`. So, there seems to be the expectation of XMPP servers to implement this protocol beyond just supporting MAM. Is this something that would be interesting for ejabberd or maybe even something you have already on your roadmap?

**Comment by zinid** [comment]
From what I understood we have to store these chat markers, i.e. to trigger database backend on very stanza? We do this for MAM, now we need to add additonal database request?

**Comment by marcphilipp** [comment]
Is there a requirement to store every chat marker in the MAM archive? I think we only need to store the latest one for each of the three statuses and return those as part of the MAM result.

**Comment by zinid** [comment]
This chat marker is a part of a message and it's stored in mam, why do we need to store them explicitly?

**Comment by marcphilipp** [comment]
The chat marker is part of a message without a body and will only stored in MAM when the message also includes a `store` hint, right?

**Comment by zinid** [comment]
Seems so

**Comment by weiss** [comment]
> What if we wouldn't store chat markers in the MAM archive but append them to the MAM result or the last page of the results? Could this be achieved by hooking into mod_mam?

Yes, that would be my idea (but you'd need to add such a hook to `mod_mam`).

> One thing, XEP-0333 is very clear about, is that the server needs to advertise that it supports `urn:xmpp:chat-markers:0`.

You mean because a server JID is used in the [example][1]?  I think that's an obvious mistake.

[1]: https://xmpp.org/extensions/xep-0333.html#disco

**Comment by weiss** [comment]
> From what I understood we have to store these chat markers, i.e. to trigger database backend on every stanza? We do this for MAM, now we need to add additonal database request?

We currently *don't* store these markers in MAM.  (XEP-0333 says we [should][1], XEP-0313 says we [shouldn't][2], it's the usual mess.)

The suggestion is to change this, i.e. to store the markers, in order to make XEP-0333 work reliably.  The idea is to not store tons of outdated markers though, but only the most recent ones, as they superseed the older markers anyway (as per XEP-0333).  Which makes some sense to me.

[1]: https://xmpp.org/extensions/xep-0333.html#requirements
[2]: https://xmpp.org/extensions/xep-0313.html#sect-idm139055517134736

**Comment by jovanpreet** [comment]
Any update on this. Currently I use `store` hint and then make cron job to delete older markers every 24 hours. Just saw this issue and curious if ejabberd supports it natively.
