### ISSUE TITLE
ejabberd.yml update about security "TLS" and add "no_tlsv1_2" option

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#2004]
Can you add all options for connections in file?
note that some distro has already removed sslv2... but it is better to have in config file
```yaml
##      - "no_sslv2"
##      - "no_sslv3"
##      - "no_tlsv1"
##      - "no_tlsv1_1"
```

Some other options are missing, look https://blog.process-one.net/securing-ejabberd-with-tls-encryption/
```yaml
...
tls_compression: false
...
```

Add a no_tlsv1_2 because new TLS 1.3?

And update this page: https://blog.process-one.net/securing-ejabberd-with-tls-encryption/ and https://docs.ejabberd.im/admin/configuration/ ^^

**Comment by badlop** [comment]
I've added the no_* values as you mentioned, because they are recommended in the blog post, so it's good to make easy to enable them.

Regarding tls_compression:false, as this is the default and recommended value, I think few people in the future will want to use that option; and no need to increase the config file with mostly useless options.

Regarding no_tlsv1_2, it is already implemented in ejabberd. But I imagine it is still early to require clients to support TLS 1.3, so better to not put that in the config file yet.

Regarding the blog post, I think it's quite good, nothing to update. Regarding the Guide, it lacks some explanations, maybe it should link to the blogpost that explains the details?

**Comment by Neustradamus** [comment]
Thanks @badlop !
If no_tlsv1_2 exists, it will be nice to inform users ^^
Not possible to add with a warn for example?

**Comment by mathiasertl** [comment]
Please don't inform "users" (they are server operators, no less) about `no_tlsv1_2`. It means clueless operators will enable it, and larger servers get tons of support requests from users about non-interacting servers. We've had enough of those problems in the past, I'm sure you all remember.

**Comment by Neustradamus** [comment]
OpenSSL 1.1.1 with TLS 1.3 out!

Need an adding of
##      - "no_tlsv1_2"

in file, doc for have only TLS 1.3 connections :)

**Comment by weiss** [comment]
As I said in the room, I agree with @mathiasertl.
