### ISSUE TITLE
17.11 does not compile as embedded mix project

### ISSUE THREAD

**Issue by jonni-larjomaa** [processone/ejabberd#2170]
> What version of ejabberd are you using?

17.11

> What operating system (version) are you using?

ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

{:ejabberd, github: "processone/ejabberd", tag: "17.11"}

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

runnin mix deps.get and then mix compile fails (version 17.08 works perfectly but not 17.09 and 17.11)

==> ejabberd
Compiling 3 files (.erl)
src/mod_muc_room.erl:3620: undefined macro 'NS_MAM_2'
src/mod_muc_room.erl:3823: undefined macro 'NS_MUCSUB_NODES_SUBSCRIBERS'
src/mod_muc_room.erl:4058: undefined macro 'NS_MUCSUB_NODES_SUBSCRIBERS'
src/mod_muc_room.erl:292: function process_iq_disco_info/3 undefined
src/mod_muc_room.erl:1599: function send_subscriptions_change_notifications/4 undefined
src/mod_muc_room.erl:1854: function get_subscription_nodes/1 undefined
src/mod_muc_room.erl:3593: spec for undefined function process_iq_disco_info/3
src/mod_muc_room.erl:3730: function get_subscription_nodes/1 undefined
src/mod_muc_room.erl:3746: function get_subscription_nodes/1 undefined
src/mod_muc_room.erl:3777: function send_subscriptions_change_notifications/4 undefined
src/mod_muc_room.erl:3813: spec for undefined function get_subscription_nodes/1
src/mod_muc_room.erl:3830: function get_subscription_nodes/1 undefined
src/mod_muc_room.erl:4055: spec for undefined function send_subscriptions_change_notifications/4
src/mod_muc_room.erl:3631: Warning: function iq_disco_info_extras/2 is unused
src/mod_mam.erl:228: undefined macro 'NS_MAM_2'
src/mod_mam.erl:241: undefined macro 'NS_MAM_2'
src/mod_mam.erl:457: undefined macro 'NS_MAM_2'
src/mod_mam.erl:37: function disco_sm_features/5 undefined
src/mod_mam.erl:81: function register_iq_handlers/2 undefined
src/mod_mam.erl:146: function unregister_iq_handlers/1 undefined
src/mod_mam.erl:196: function register_iq_handlers/2 undefined
src/mod_mam.erl:214: spec for undefined function register_iq_handlers/2
src/mod_mam.erl:233: spec for undefined function unregister_iq_handlers/1
src/mod_muc.erl:519: undefined macro 'NS_MAM_2'
src/mod_muc.erl:37: function process_disco_info/1 undefined
src/mod_muc.erl:508: spec for undefined function process_disco_info/1
could not compile dependency :ejabberd, "mix compile" failed. You can recompile this dependency with "mix deps.compile ejabberd", update it with "mix deps.update ejabberd" or clean it with "mix deps.clean ejabberd"
==> moimoi_ejabb
** (Mix) Encountered compilation errors

using Erlang/OTP 20.1 and elixir 1.5.2 from esl repos

**Comment by zinid** [comment]
Yes, see https://github.com/processone/fast_xml/issues/30 and https://github.com/processone/xmpp/issues/22

**Comment by leeicmobile** [comment]
@mremond can you give an ETA on when the hex packages for fast_xml and xmpp can be published? currently reviewing if we are going to fork multiple repos in the meantime.

Cheers,

Lee

**Comment by cromain** [comment]
we can maintain mix.exs to get correct versions of deps, and checkout git when hex package is not available yet. This change is usefull as xmpp and tls libs has fixes quite often.

**Comment by leeicmobile** [comment]
@cromain I don't understand your comment...the route of the issue with the XMPP dependnecy is not MIX being out of date but actually that rebar attempts to get the XMPP dependencies from hex rather than form git, therefore when an fast_xml version in rebar.config is defined which is > fast_xml hex version elixir compilation hit's an issue.

I think the route issue is there is a large lag between git releases and them being packaged into hex for a lot of the @p1bot packages, I'm not sure if the real fix is an internal review of what the priority/process in supporting hex packaging is and wither there should be a minimal lag between making the git release and making the hex package available. I don't mean that to come across negatively you must have other competing priorities I'm sure.

To solve this issue I forked XMPP so it didn't fail hex package resolution (by downgrading the fast_xml version to 1.1.24) then overrode the fast_xml versions int he app project to take it from github 1.1.25
