### ISSUE TITLE
Error while starting ejabberd

### ISSUE THREAD

**Issue by Veerbhadra277** [processone/ejabberd#2193]
> What version of ejabberd are you using?

17.2 rmp

> What operating system (version) are you using?

CentOS7

> How did you install ejabberd (source, package, distribution)?

Package

Getting error on ejabberd start in 
> sed: can't read /opt/ejabberd-17.12/conf/ejabberd.yml: No such file or directory

Installed ejabberd using cmd 
> sudo yum install https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/17.12/ejabberd-17.12-0.x86_64.rpm

and configured yml file from /opt/ejabberd/conf/ejabberd.yml
and trying to start ejabberd ./bin/ejabberdctl start

can anyone help me in this?

Regards,
Veer

**Comment by cromain** [comment]
ejabberd is installed as root, and must be run as ejabberd user (ejabberdctl will be called by root and su to ejabberd)
check you have ejabberd user, with home set to /opt/ejabberd
then call 'ejabberdctl start' or '/etc/init.d/ejabberd start' as root.

**Comment by cromain** [comment]
Your problem is you don't run ejabberdctl as root or as ejabberd user
either ejabberd user is not created or does not have HOME set to /opt/ejabberd
you can still force read the right config file passing -f /opt/ejabberd/conf/ejabberd.yml to ejabbertctl, but this is not the right solution as your error result of misuse or wrong ejabberd user config.
