### ISSUE TITLE
Recommended permissions of LetsEncrypt certificates for Ejabberd

### ISSUE THREAD

**Issue by dhiru1602** [processone/ejabberd#2211]
> What version of ejabberd are you using?

17.12

> What operating system (version) are you using?

Debian Stretch

> How did you install ejabberd (source, package, distribution)?

https://apt.jabber.at

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I was trying to make use of **certfiles:** parameter in **ejabberd.yml** to specify the LetsEncrypt SSL certificates for my domain which are in **/etc/letsencrypt/live/www.example.com/**. The certificate *.pem files are owned by root and ejabberd is unable to access the directory. What is the recommended way of granting ejabberd access to these certificates?

**Comment by mdinter** [comment]
as root:

**mkdir /opt/ejabberd/conf/certs/
cp /etc/letsencrypt/live/www.example.com/*.pem /opt/ejabberd/conf/certs/.
chown --recursive ejabberd:ejabberd /opt/ejabberd/conf/certs/**

and change ejabberd.yml:

```
## List all available PEM files containing certificates for your domains,
## chains of certificates or certificate keys. Full chains will be built
## automatically by ejabberd.
##
certfiles:
  - "/opt/ejabberd/conf/certs/*.pem"
```

**Comment by zinid** [comment]
I would rather create a group, let's say `certs` and put ejabberd and friends (HTTP server, MTA, etc) into this group, then set this group to all files and directories of `/ets/letsencrypt` (with `r--` access for files and `r-x` access for directories) and also remove all permissions from others.

**Comment by debalance** [comment]
Why don't you use the native ACME support of ejabberd 17.12 ?

**Comment by xekon** [comment]
For anyone that stumbles upon this thread while using google, here was my solution:

    sudo su
    mkdir /opt/ejabberd/conf/certs/
    cat /etc/letsencrypt/live/example.com/privkey.pem /etc/letsencrypt/live/example.com/fullchain.pem > /opt/ejabberd/conf/certs/server.pem
    chown -R root:ejabberd /opt/ejabberd/conf/certs/
    chmod 550 /opt/ejabberd/conf/certs/
    chmod -R 640 /opt/ejabberd/conf/certs/*
    exit

The reason for the chown and chmod is so that only user root can write to the certs directory or certs file, and only user ejabberd can read from the file:
https://chmod-calculator.com/

Then just add this to the end of your cert renewal cron job:

    cat /etc/letsencrypt/live/example.com/privkey.pem /etc/letsencrypt/live/example.com/fullchain.pem > /opt/ejabberd/conf/certs/server.pem

**Comment by zinid** [comment]
@xekon concatenating PEM files into a single one is not required at all, you can just list all your files in `certfiles` option.

**Comment by xekon** [comment]
Ah! excellent, thanks for that info, will revise my post for others that find it.

**Comment by arendtio** [comment]
Today I came across this issue too. I liked the 'create a cert group' solution better, but since I have only 2 processes using those files (nginx and ejabberd) and nginx seems to be running as root anyway (by default) I did the following to solve the issue:

```
chgrp ejabberd /etc/letsencrypt/{archive,live}
chmod g+rx /etc/letsencrypt/{archive,live}
```

That way, only ejabberd and root should have access to the files and you will not have to copy around the certificates every time they change. I wonder, however, that there is no such thing like a cert group by default.
