### ISSUE TITLE
Public Chatrooms

### ISSUE THREAD

**Issue by ahmedqandil** [processone/ejabberd#2302]
Hello Guys,

Is it possible to build public chat rooms using ejabbered? What I mean by public is that anyone can join these rooms without necessarily being invited to it? 

If it is possible, how scalable is this? A room can take how many users? hundreds, thousands, millions?

**Comment by zinid** [comment]
Yes, it's possible, there is a lot of public chatrooms in the jabber server network.
Regarding scalability: no. A room can take a few thousands of users, but that's it. Please note that a bottle-neck most likely will be a client joining such a room, because it's typically unable to process the storm of presences when joining such room. Also, there is #2271

**Comment by myluckyapps** [comment]
@zinid, 

I have a query on public groups too , I was able create public groups using (conversations client + ejabberd). But how to make this group discover-able to public without any invite? At this moment only invite url is being used to join group. 

what is best way to find different public groups by category (similar to viber) etc? Do we need a separate web for maintain these again? Can you please provide few pointers or any reference to read or go through.

**Comment by cromain** [comment]
building your own room directory is what you need, but this is out of ejabberd scope. I'm closing this issue.
