### ISSUE TITLE
feature [xep-0292]

### ISSUE THREAD

**Issue by zh99998** [processone/ejabberd#2413]
[XEP-0292: vCard4 Over XMPP](https://xmpp.org/extensions/xep-0292.html) looks great as it support more vcard field, use vCard official XML format, subscribe-able and defines migration method.

**Comment by zinid** [comment]
We will pay the price for implementing this because vCard4 is not backward compatible with vCard, and this will break compatibility between clients (if no converters are developed/deployed on every server). So, in my opinion, it will create more problems than solves. Also, seems like there is a reason the XEP is deferred.
