### ISSUE TITLE
HTTP file upload slow on Linux

### ISSUE THREAD

**Issue by antonyablonsky** [processone/ejabberd#2433]
> What version of ejabberd are you using?

Ejabberd 18.04

> What operating system (version) are you using?

Ubuntu MATE 18 latest, Linux Mint 17.3 

> How did you install ejabberd (source, package, distribution)?

Installer from official site

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When I use ejabberd on Linux operating systems I have very slow HTTP file upload speed (60 kB/s). But my connection with internet very fast. Speedtest tests shows 70 Mb/s upload/download (which is 8.75 MB/s or 8750 kB/s). I tried two distros mentioned above.
BUT! After I installed Windows 10 to this computer and installed ejabberd 18.04 with absolutely the same ejabberd.yml and etc, I have much bigger speeds (380 kB/s).
I have no problem when the phone I send files from and computer with ejabberd connected to same router - upload speed is excellent (both on Linux or Windows). It starts on Linux as soon as phone disconnected from router. On Windows upload speed is much higher and I think this is the maximum speed I can get through the internet -> have no problems on Windows. 

What is that? Ejabberd problem, Linux problem, router problem?

**Comment by zinid** [comment]
Not sure what you expect us to reply. We don't know where the problem is. Maybe in router, maybe in ejabberd, maybe in your computer, maybe in your uplink. Is this answer you expected? To make it clear: it's up to an admin to detect where data channel has a bottle-neck. Please report the bug (this is a bugtracker after all) when you absolutely sure the problem is on ejabberd side. I close the ticket till then.
