### ISSUE TITLE
Feature Request: Default bookmarks (aka default MUCs)

### ISSUE THREAD

**Issue by stevenroose** [processone/ejabberd#2476]
I think this is a known feature request, but I couldn't find an issue for it.

Basically would be nice to be able to set one or more default MUCs that all (new) users have bookmarked by default. F.e. like a "home" or "landing" MUC for support.

**Comment by stevenroose** [comment]
That's awesome! Didn't know members could be chatrooms! 

For the record, though, it's **`@all@`** in lowercase.

**Comment by badlop** [comment]
The solution I provided in a previous comment (to use mod_shared_roster), is problematic because not all clients will handle that.

A similar request was posted in #2649, and the solution there was to use send_stanza and send a full PEP stanza, but that works only with newer clients that support that.

Another solution would be to write a command that builds a room bookmark (XEP-0048) and stores it in private storage (XEP-0049) and in PEP (XEP-0163) to accommodate all kind of clients.

**Comment by stevenroose** [comment]
I was thinking about having my custom invitation tool (a tiny web server that handles a form with invitation codes) to just use the API to send a MUC invitation. Is it possible to add bookmarks with the API? I know these are only half-solutions for the actual problem of this issue, because they require custom code.

**Comment by badlop** [comment]
See the recently mod_default_rooms in: https://github.com/processone/ejabberd-contrib/commit/d60fa5e9b3f3093f7d5cec22ff71117f8c0b7b31
