### ISSUE TITLE
Ejabberd doesn't compile as mix umbrella project dependency

### ISSUE THREAD

**Issue by pdorofiejczyk** [processone/ejabberd#2540]
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Elixir docker image

> How did you install ejabberd (source, package, distribution)?

hex package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have created basic mix umbrella project [https://github.com/pdorofiejczyk/elixir_umbrella_hello_world](https://github.com/pdorofiejczyk/elixir_umbrella_hello_world). It contains one elixir application which have ejabberd as dependendency. When I'm trying to compile, I'm getting error ```src/mod_muc_log.erl:47: can't find include file "xmpp.hrl"```. Everything works fine if it is not umbrella project.

**Comment by artospaj** [comment]
After closer look I can say that the problem is in mix.exs of ejabberd application.
Method `erl_options()` doesn't accept erl_options from main mix.exs file. 

There is some logic, though, which adds include paths to (hardcoded) list of dependencies.
The problem lays in that logic - it accepts either building ejabberd alone, or building ejabberd from inside the project that has it as direct dependency. When ejabberd is a "dependency of dependency" that logic fails and makes a false assumption it's being built as standalone application.

**Comment by Freyskeyd** [comment]
I'm also unable to compile when using it in an umbrella project :x

**Comment by fernandomrm** [comment]
I'm also unable to use it in an umbrella project.
