### ISSUE TITLE
Upgrade to Elixir 1.7.4?

### ISSUE THREAD

**Issue by paradisaeidae** [processone/ejabberd#2653]
Environment
-----------
- ejabberd version: 18.09
- Erlang version: 20
- OS: Linux (Debian)
- Installed from: source
-------------------------------
No errors

Bug description
---------------
Elixir version could do with a bump?
Is the embedded Elixir a current future direction?
The 1.4 version is behind with the Elixir 1.7.4.
Which means the basic examples of Elixir are broken when attempting to use the 'use' verb-macro.
The rebar borks when attempting a build/install as the 1.7 omits ebin/elixir.app

**Comment by cromain** [comment]
rebar2 (which is still used) is not able to cope with this change: it should check lib/elixir/src/elixir.app.src instead of src/elixir.app.src.
as src/elixir.app.src moved away, current rebar check fails which also breaks jenkins tests.

options: use rebar3, or drop rebar completely to rely only on mix.
but we have to move milestone for now.

**Comment by cromain** [comment]
we need to keep rebar for integration in tools like buildroot

**Comment by badlop** [comment]
I've just committed a dirty workaround that allows rebar2 to get, compile and use Elixir 1.12.0: https://github.com/processone/ejabberd/commit/937e1c2e373e360fe47e455886d186492248f31f

Unfortunately, rebar3 doesn't compile the files in lib/, because that task in rebar2 was done by rebar_elixir_plugin, and there is no equivalent for rebar3.

The good news is that, anybody interested in Elixir development, can install a recent Elixir version in the system and use it to compile ejabberd:
```
./configure --with-rebar=mix
```
