### ISSUE TITLE
Remove user data with external auth (when whole domain/vhost is gone)

### ISSUE THREAD

**Issue by duritong** [processone/ejabberd#2793]
While using the external auth mechanism, I might have jabber domains that are getting deleted/removed in the external database, this a removes all jids from that domain in the external auth system, but also removes the domain from the vhost in the ejabberd config.

However, I'd like to also remove the user data on ejabberd, so the user data is really gone.

The issue is that if you try to unregister a jid, from a domain that has no vhost, the external auth integration is failing completely and thus an error is raised:

```
2019-02-13 23:44:37.210 [error] <0.1542.0>@ejabberd_auth_external:failure:103 External authentication program failed when calling 'remove_user' for jid@deleted.example.com: disconnected
```

The only solution is to temporarily re-add the vhost (of the deleted domain), cleanup all jids and then remove it again.

How should one safely remove user data (also from jids where the whole domain is gone).

**Comment by mremond** [comment]
In my view, ejabberd behaviour is correct. It seems normal to prevent operations to happen on non existing. It should even be prevented before it reached that place in the code, I think.
You should not delete domains if you still want to perform operations on them.

**Comment by duritong** [comment]
In general I would agree, though on the other hand: I can still delete user data of jids that do not exist anymore in the external auth. So there is some inconsistency there.

From what I understand the error with the removed domain, comes because the vhost has been removed and so no ext-auth process is running anymore and that's why we see the error.

But then also: Why is communication with the external-auth process required, if - as we can see with still existing vhosts - userdata of deleted jids can be removed without any issues, although the ext-auth script would return that the user does not exist.

Sidenote: For the removal of userdata for a configured vhost there is no difference if a user exists, got removed but has still data in ejabberd, has been deleted and data got removed or never existed at all.

**Comment by mremond** [comment]
Well, I do not understand your point. To know which backend to use, you need to check the config of that Vhost. Backend is defined per Vhost. Maybe there is an inconsistency, but I think it should be that the command should ensure that the vhost exist. For example, to delete some data from Vhost using MySQL data, to know on which db it should be removed, ejabberd need to read which database is configured for that vhost. If you do not have a Vhost, there is no way to get the associated backend.
So, I think it is not clean to allow deleted data from a backend without properly ensuring that the configuration of the Vhost is correct. Otherwise you may end up deleting the wrong data.

So, if we change something, it should be about making that check more consistent and strict.

**Comment by duritong** [comment]
I fully understand all the details of why it is likely how it is at the moment. I am just trying to point out how I feel it's inconsistent in usage.

BUT what I would find awesome is that there is a way to delete any kind of not anymore used data from the database(s).

**Comment by mremond** [comment]
Which database schema are you using ? The older, with one database per vhost, or the newer with one database able to handle several vhost ?

**Comment by badlop** [comment]
I close as there isn't feedback in two months.
