### ISSUE TITLE
WARN:  Missing plugins: [rebar3_hex]

### ISSUE THREAD

**Issue by jameskentTX** [processone/ejabberd#2800]
system: debian 10, testing version
erlang: Erlang/OTP 21 [erts-10.2.3], Eshell V10.2.3

problem: 

1. I cloned ejabberd from github
2. cd ejabberd
3. ./autogen.sh
4. ./configure --enable-user=ejabberd --prefix=/opt/ejabberd --enable-stun --enable-sip --enable-debug --enable-pgsql --enable-zlib
5. make

make fails with message WARN:  Missing plugins: [rebar3_hex]
the last few lines of make command:

Compiled src/ejabberd_router_multicast.erl
Compiled src/extauth_sup.erl
Compiled src/node_mix.erl
Compiled src/mod_adhoc.erl
/usr/lib/erlang/bin/escript rebar skip_deps=true compile
WARN:  Missing plugins: [rebar3_hex]
==> rel (compile)
==> ejabberd (compile)

I tried to compile stable version of ejabberd (18.12.1), the same result.
In fact, compiling is not a problem imo.
"make deps" fails and I don't know why

**Comment by prefiks** [comment]
Hello,

You don't need to worry about it, you can safely skip that warning, everything compiled properly. This plugin is only used by rebar3 but you are using rebar so it doesn't matter in that case.

**Comment by jameskentTX** [comment]
@prefix:

Thanks. There is no "build" folder after "make", so I thought something went wrong.

**Comment by Virendra-Varma** [comment]
Hi after compiling when I hit `make install` I am getting this error
make[1]: Entering directory '/home/ubuntu/Downloads/ejabberd-19.02'
/usr/bin/install -c -d /usr/local/lib/base64url-0.0.1/ebin
/usr/bin/install -c -m 644 deps/base64url/ebin/base64url.beam /usr/local/lib/base64url-0.0.1/ebin/base64url.beam
/usr/bin/install: cannot remove '/usr/local/lib/base64url-0.0.1/ebin/base64url.beam': Permission denied
Makefile:174: recipe for target '/usr/local/lib/base64url-0.0.1/ebin/base64url.beam' failed
make[1]: *** [/usr/local/lib/base64url-0.0.1/ebin/base64url.beam] Error 1
make[1]: Leaving directory '/home/ubuntu/Downloads/ejabberd-19.02'
Makefile:197: recipe for target 'copy-files' failed
make: *** [copy-files] Error 2

since in documentation, you guys suggest not to use sudo I don't know how can I solve this issue please help

**Comment by licaon-kter** [comment]
@Virendra-Varma then how to install without access? Run `make install` as root or with ``}sudo make install`

**Comment by Virendra-Varma** [comment]
Hi, thanks for the reply I installed the Ejabberd using  `sudo make install` after successfully installing the Ejabberd I made required changes in `ejabberd.yml` file and when I am trying to run `sudo /sbin/ejabberdctl start` I am getting this error in error log `
2019-05-07 11:38:06.019 [error] <0.88.0>@ejabberd_config:get_plain_terms_file:306 Cannot load /usr/local/etc/ejabberd/ejabberd.yml: permission denied
` why any idea

**Comment by licaon-kter** [comment]
@Virendra-Varma `sudo -u ejabberd /usr/local/etc/ejabberd/ejabberd.yml` ?

You have an ejabberd user, right? It needs permissions to read/write in some places...

**Comment by Virendra-Varma** [comment]
Hi, @licaon-kter thanks for the replies after changing the permission of file it works. thanks a lot.
