### ISSUE TITLE
delete_old_mam_messages causes badarg Error

### ISSUE THREAD

**Issue by 1resu** [processone/ejabberd#2836]
I want to delete the mam messages older than x days. Whatever argument I use (chat, groupchat, all) it fails with the following output:

```/usr/sbin/ejabberdctl --no-timeout delete_old_mam_messages all 30```

```Problem 'exit {aborted,{badarg,[archive_msg]}}' occurred executing the command.
Stacktrace: [{mnesia,abort,1,[{file,"mnesia.erl"},{line,318}]},
             {mod_mam_mnesia,delete_old_messages,3,
                             [{file,"src/mod_mam_mnesia.erl"},{line,90}]},
             {lists,map,2,[{file,"lists.erl"},{line,1239}]},
             {mod_mam,delete_old_messages,2,
                      [{file,"src/mod_mam.erl"},{line,541}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,352}]},
             {ejabberd_ctl,try_call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,321}]},
             {ejabberd_ctl,process2,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,271}]},
             {ejabberd_ctl,process,2,
                           [{file,"src/ejabberd_ctl.erl"},{line,249}]}]
```

I'm using ejabberd 18.12.1

**Comment by badlop** [comment]
I try that, and works correctly, so you'll have to provide more details:
* That stacktrace is the only error message you get in the logs? Nothing else before that?
* How do you have mod_mam configured?
* What if you provide a very large number, like 60000 (so that nothing is going to be deleted)?
* Does MAM work correctly (store and rerieve messages), and is that the only problem you found?
