### ISSUE TITLE
Docker Container Web Admin 

### ISSUE THREAD

**Issue by irvingwa** [processone/ejabberd#2886]
When running 
`docker run --name ejabberd -d -p 5222:5222 -p 5280:5280 ejabberd/ecs`

and then adding an admin user with 
`docker exec -it ejabberd bin/ejabberdctl register admin localhost passw0rd`

I am able to login to the admin page but only Virtual Host is available for configuration.

**Comment by cromain** [comment]
i don't understand the problem

**Comment by badlop** [comment]
> I am able to login to the admin page 

This means that the JID and password you provided in the WebAdmin page are correct, in the sense that they correspond to an existing account, registered in ejabberd. Of course, as you recently registered that account, that account exists :)

> but only Virtual Host is available for configuration.

That account can not see any of the administrative pages in WebAdmin because that account does NOT have admin rights set in ejabberd.yml. Search in that configuration file, what you are missing is something like this:
```yaml
    acl:
      admin:
        - user: "admin@localhost"
```

**Comment by irvingwa** [comment]
@badlop That was it thank you!
