### ISSUE TITLE
muc_register_nick/muc_unregister_nic argument name incorrect 

### ISSUE THREAD

**Issue by smpgallagher** [processone/ejabberd#2908]
Argument for nickname api command is incorrect in the documentation. the "serverhost" argument name should show "host"

**Comment by mremond** [comment]
@badlop we probably need to check consistency of use of host / serverhost.
Maybe we need alias to be backward compliant ?

**Comment by badlop** [comment]
There are two topics here.

First, the argument consistency for those commands was fixed in January in https://github.com/processone/ejabberd/commit/9577fe3ba8b00797816cc1243a8e22ed59096d86 but as @smpgallagher noticed, the online documentation in https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#muc-register-nick is not yet updated. I think @cromain updates that page from time to time.

Second, there may still be some commands using as arguments "server" or "serverhost" instead of "host". I'll look into this tomorrow morning.

**Comment by badlop** [comment]
There are still eight commands that use "server" argument instead of "host":
-    add_rosteritem localuser localserver user server nick group subs 
-    bookmarks_to_pep user server 
-    delete_rosteritem localuser localserver user server 
-    get_offline_count user server 
-    get_presence user server 
-    get_roster user server 
-    remove_mam_for_user user server 
-    remove_mam_for_user_with_peer user server with 

I'm checking if it's possible to provide backwards compatibility once changed.

**Comment by badlop** [comment]
The online documentation will be updated with the next ejabberd release. In the meantime, it is always possible to check the available commands and their arguments running the command line "ejabberdctl help"
