### ISSUE TITLE
Embedded Ejabberd in Elixir app - logger error

### ISSUE THREAD

**Issue by sarsonj** [processone/ejabberd#3020]
## Environment

- ejabberd version: 19.8.0
- Erlang version: Erlang/OTP 22
- Elixir version: Elixir 1.9.1 (compiled with Erlang/OTP 22)
- OS: Linux (Debian)
- Installed from: elixir mix

## Bug description
I followed tutorial on https://docs.ejabberd.im/developer/extending-ejabberd/elixir/.

ejabber writes, that it will use elixir logger:

14:43:24.485 [info]  Ignoring ejabberd logger options, using Elixir Logger.

However, then  I got many errors like:

```
14:43:25.987 [error] :gen_event handler :elixir_logger_backend installed in :lager_event terminating
** (UndefinedFunctionError) function Logger.Config.__data__/0 is undefined or private
    (logger) Logger.Config.__data__()
    (ejabberd) src/elixir_logger_backend.erl:43: :elixir_logger_backend.handle_event/2
    (stdlib) gen_event.erl:577: :gen_event.server_update/4
    (stdlib) gen_event.erl:559: :gen_event.server_notify/4
    (stdlib) gen_event.erl:300: :gen_event.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I have configured logger in confix.exs:
```
config :logger,
  backends: [:console]
```

And also tried to start logger in mix.exs:

```
def application do
    [
       extra_applications: [:logger]
    ]
  end
```

**Comment by sarsonj** [comment]
Looks like elixir 1.9 removed Logger.Config.__data__/0 function, it is no available anymore.

**Comment by walkerbrown** [comment]
If embedding in Elixir, take a look at `deps/ejabberd/lib/src/ejabberd_logger.erl`. Also here: [ejabberd_logger.erl#L106](https://github.com/processone/ejabberd/blob/2e1e128833723c08447a538a248f86f603fea195/src/ejabberd_logger.erl#L106).

Short-circuiting the case, to always call `do_start/1` rather than `do_start_for_logger/1`, allowed me to compile my application and avoids the call to `__data__/0` in Elixir (>= v1.8). However, I'm not sure if this quick-fix is causing a loss of log info. Use with caution!

A stronger solution might be to change [elixir_logger_backend.erl#L43](https://github.com/processone/ejabberd/blob/2e1e128833723c08447a538a248f86f603fea195/src/elixir_logger_backend.erl#L43), but I'm not familiar enough with erlang to suggest the _right_ way.

Hope this helps!

**Comment by anildigital** [comment]
This issue might be related to https://github.com/processone/ejabberd/issues/3297
