### ISSUE TITLE
Wrong FORM_TYPE for IBR form with CAPTCHA

### ISSUE THREAD

**Issue by linkmauve** [processone/ejabberd#3045]
## Environment

- ejabberd version: unknown
- Erlang version: unknown
- OS: unknown
- Installed from: unknown

## Errors from error.log/crash.log

No errors

## Bug description

When doing in-band registration with some Ejabberd server with a CAPTCHA, such as creep.im or patchcord.be, the FORM_TYPE is `urn:xmpp:captcha` instead of `jabber:iq:registration` like it should be as defined by XEP-0077 and extended by XEP-0158.

**Comment by badlop** [comment]
Maybe I'm missing something... What you consider a bug is in fact described in example 11 from https://xmpp.org/extensions/xep-0158.html#register , and is similarly provided by ejabberd 19.09:

```xml
<iq xmlns="jabber:client"
    to="localhost"
    type="get"
    id="4620ac0b-09a7-4c02-92bf-573652f5cdb5">
  <query xmlns="jabber:iq:register" />
</iq>

<iq xml:lang='ca'
    from='localhost'
    type='result'
    id='4620ac0b-09a7-4c02-92bf-573652f5cdb5'>
  <query xmlns='jabber:iq:register'>
    <x type='form'
       xmlns='jabber:x:data'>
      <instructions>Tria nom d'usuari i contrasenya per a
      registrar-te en aquest servidor</instructions>
      <field var='FORM_TYPE'
             type='hidden'>
        <value>urn:xmpp:captcha</value>
      </field>
      <field var='username'
             type='text-single'
             label='Usuari'>
        <required />
      </field>
      ...
    </x>
  </query>
</iq>
```

**Comment by zinid** [comment]
I close the ticket because ejabberd respects namespace requirements from XEP-0158. If there are any discrepancies in the XEPs, this should be addressed at the XSF.

**Comment by linkmauve** [comment]
This is being addressed in https://github.com/xsf/xeps/pull/852.

**Comment by Neustradamus** [comment]
@processone, @mremond, @zinid: Can you reopen it?

**Comment by badlop** [comment]
Oh, now that XEP-0158 changed, ejabberd no longer respects it. And I wonder how this change should be implemented:
- Should xmpp's captcha_form encoding be parametrized some way? I doubt that
- Or it's https://github.com/processone/ejabberd/blob/master/src/ejabberd_captcha.erl#L121 the one that should be parametrized to ammend the FORM_TYPE value.
- Or https://github.com/processone/ejabberd/blob/master/src/mod_register.erl#L227 should find the FORM_TYPE and replace its value?

**Comment by zinid** [comment]
I don't see CAPTCHA related fields registered in 'jabber:iq:register' form type: https://xmpp.org/extensions/xep-0077.html#registrar-formtypes
So putting 'jabber:iq:register' in 'FORM_TYPE' is also wrong.

**Comment by lovetox** [comment]
i think this XEP is a bit confusing, the registrated fields are not the fields for the dataform, these are the fields we can expect within the jabber:iq:register namespace, means

<query xmlns="jabber:iq:register">
  <username/>
  <password/>
</query>

The only rules which apply to dataforms are written down under https://xmpp.org/extensions/xep-0077.html#extensibility

Reading this, we can extend the dataform anyway we like.
To be fair the FORM_TYPE is only mentioned in examples, *but* its obvious that this should be a well known value, otherwise there would be no way to discover if a form is a register form or not.

There is another ejabberd specific component to this.
Ejabberd includes captcha fallback fields for clients who dont support captcha.
Now you cant expect clients that don't support captcha to search for a form of type `urn:xmpp:captcha`,  rather they will always look for `jabber:iq:register` as 0077 shows in its examples

**Comment by lovetox** [comment]
Any chance this can be looked at? the current impl needs clients to specifically support ejabberds impl

**Comment by badlop** [comment]
The easiest solution that I could find is the third option that I mentioned in https://github.com/processone/ejabberd/issues/3045#issuecomment-554311685

That proposed patch is in https://github.com/badlop/ejabberd/commit/49431b5d5bbf501d4cf35a4b14eb0d146c884c17
