### ISSUE TITLE
Ejabberd - join to cluster in plugin - ejabberd crash

### ISSUE THREAD

**Issue by sarsonj** [processone/ejabberd#3049]
I wrote simple auto join cluster pluging, that looks for other nodes running and if any available, the plugin join founs node into cluster.

The plugin is written in Elixir. When the `:ejabberd_cluster.join()` function is called, the node is starting to restart (same way, when I call `:ejabberd_cluster.join()` from console, so that is probably right behaviour), however, it fails with error and ejabberd doesn't restart:
```
23:43:43.169 [debug] Stopping mod_shared_roster at xmpp.testing.barkio.com

23:43:43.170 [debug] Route unregistered: xmpp.testing.barkio.com

23:43:43.204 [info]  ejabberd 19.9.0 is stopped in the node 'ejapp@ejabberd-1.xmpp-internal-svc.ttmonitor.svc.cluster.local'

23:43:43.207 [info]  Application ejabberd exited: :stopped

23:43:43.318 [error] :gen_event handler :ejabberd_system_monitor installed in :alarm_handler terminating
** (ArgumentError) argument error
    (stdlib) :ets.lookup_element(:ejabberd_options, {:oom_queue, :global}, 2)
    (ejabberd) src/ejabberd_config.erl:157: :ejabberd_config.get_option/1
    (ejabberd) src/ejabberd_system_monitor.erl:137: :ejabberd_system_monitor.handle_overload/2
    (ejabberd) src/ejabberd_system_monitor.erl:114: :ejabberd_system_monitor.handle_info/2
    (stdlib) gen_event.erl:577: :gen_event.server_update/4
    (stdlib) gen_event.erl:559: :gen_event.server_notify/4
    (stdlib) gen_event.erl:347: :gen_event.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:timeout, #Reference<0.2673757326.4237295617.33203>, :handle_overload}
State: {:state, #Reference<0.2673757326.4237295617.33203>, :undefined}
```

As I wrote, when I call :ejabberd_cluster.join() with the same parameters from the console, it works, ejabberd restarts and both nodes are joined into cluster. Any idea, what is the reason for this problem?

## Environment

- ejabberd version: 19.9
- Erlang version: Erlang/OTP 21 [erts-10.3.5.4], Elixir (1.8.2)
- OS: Linux (Debian)
- Installed from: as Elixir app using mix

**Comment by rbobrovnikov** [comment]
Experiencing the same behaviour with 19.09.1 and 20.04 versions if API endpoint `/api/join_cluster` called. Ejabberd just crashes.
If node joined via `ejabberdctl` all is fine.

**Comment by badlop** [comment]
Right, this is reproducible. And looking at the source code in https://github.com/processone/ejabberd/blob/master/src/ejabberd_cluster_mnesia.erl#L53

```erlang
            application:stop(ejabberd),
            application:stop(mnesia),
            mnesia:delete_schema([node()]),
            application:start(mnesia),
            case mnesia:change_config(extra_db_nodes, [Node]) of
                {ok, _} ->
                    replicate_database(Node),
                    wait_for_sync(infinity),
                    application:stop(mnesia),
                    application:start(ejabberd);
                {error, Reason} ->
                    {error, Reason}
            end;
```

In order to join a cluster, the ejabberd application that runs inside an erlang node must be stopped, so mnesia is reconfigured, and then the application is started again.

However, notice that _mod_http_api_ (or _ejabberd_xmlrpc_, or any other listener that runs API queries) are processes that run inside the ejabberd application. So, when ejabberd is stopped, those processes get stopped too, and the procedure stops abruptly.

Why does this work with ejabberdctl? Because that script starts a small erlang node, connects to the node that runs ejabberd, and then starts the joining procedure. When the ejabberd application is stopped, that doesn't affect the procedure because it is run by a process outside ejabberd itself.

Right now I see no way for a process that was started by ejabberd (like a mod_http_api query) to keep alive when ejabberd is stopped. In summary, join_cluster can only be run with ejabberdctl, and this will have to be documented in the command documentation.
