### ISSUE TITLE
get_room_affiliation error  member/owner

### ISSUE THREAD

**Issue by laurohen** [processone/ejabberd#3061]
version: ejabberd-18.12.1

I am trying to use get_room_affiliation to know affiliate status but any user I pass as API parameter returns affiliation = onwer.

How can I solve this?

**Comment by abbasidaniyal** [comment]
I am facing the same issue. I am using version 20.04.
```
$ ejabberdctl set_room_affiliation group1 conference.192.168.29.190 user2@192.168.29.190 owner
$ ejabberdctl set_room_affiliation group1 conference.192.168.29.190 user1@192.168.29.190 member
$ ejabberdctl get_room_affiliation group1 conference.192.168.29.190 user1@192.168.29.190 
owner
$ ejabberdctl get_room_affiliation group1 conference.192.168.29.190 user2@192.168.29.190 
owner
$ ejabberdctl get_room_affiliations group1 conference.192.168.29.190 
user1   192.168.29.190  member
user2   192.168.29.190  owner
```

**Comment by badlop** [comment]
Is user1 a system or MUC administrator? In that case, user1 will always be room owner of all rooms, it cannot be downgraded.

```yaml
acl:
  admin:
    user:
      - user1@localhost
```

**Comment by abbasidaniyal** [comment]
No. User one was registered using the web interface.

**Comment by abbasidaniyal** [comment]
The part I don't understand is how is get_room_affiliation and get_room_affiliations not giving a consistent response?

**Comment by badlop** [comment]
> The part I don't understand is how is get_room_affiliation and get_room_affiliations not giving a consistent response?

get_room_affiliations prints the information as stored in the room process data.
https://github.com/processone/ejabberd/blob/21312c79aa1c1c319f2b1859184a5ef3126c7ac9/src/mod_muc_admin.erl#L1112

get_room_affiliation, instead, asks the room about the affiliation of the account.
https://github.com/processone/ejabberd/blob/21312c79aa1c1c319f2b1859184a5ef3126c7ac9/src/mod_muc_admin.erl#L1137

In this case, if the account is administrator of the MUC service or the virtual host, then it is declared 'owner' regardless of its stored room affiliation, because in fact it will get 'owner' rights in practice:
https://github.com/processone/ejabberd/blob/21312c79aa1c1c319f2b1859184a5ef3126c7ac9/src/mod_muc_room.erl#L1536
