### ISSUE TITLE
Ejabberd bosh reports '400 Bad Request' with incorrect stanza format to the bosh client

### ISSUE THREAD

**Issue by cmeng-git** [processone/ejabberd#3073]
## Environment

- ejabberd version: 18.09
- Erlang version: `erl +V`
- OS: Linux (Debian)
- Installed from: source | distro package | official deb/rpm | official binary installer | other

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

`2019-10-28 10:06:51.053 [debug] <0.7362.0>@mod_bosh:process:63 Bad Request: no data`

## Bug description

Please, give us a precise description (what does not work, what is expected, etc.)
On received a bad request from bosh client, found that ejabberd reports the error incorrectly i.e.

```
2019-10-28 11:14:19.049 32334-1522/org.atalk.android V/aTalk: [20365] org.igniterealtime.jbosh.BOSHClient.processExchange() Could not obtain response
    org.igniterealtime.jbosh.BOSHException: Could not parse body:
    <?xml version='1.0'?>
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <h1>400 Bad Request</h1>
```

it should be per
[17.2 Terminal Binding Conditions](https://xmpp.org/extensions/xep-0124.html#errorstatus-terminal) i.e.

`<body type='terminate' condition='bad-request' xmlns='http://jabber.org/protocol/httpbind'/>`

Please see below link for more info
[Smack 4.4.0: Smack BOSH receives “400 Bad Request’ from server when sending large amount of data via mobile network ](https://discourse.igniterealtime.org/t/smack-4-4-0-smack-bosh-receives-400-bad-request-from-server-when-sending-large-amount-of-data-via-mobile-network/86481)

**Comment by zinid** [comment]
Well this is actually a classical problem when one is trying to encapsulate some protocol into an HTTP transport: it's not guaranteed at all that all HTTP responses will contain the valid protocol body (due to proxies, load balancers, and so on). Since there is no data (body) in the request, ejabberd rejects it at HTTP layer, without passing it to the BOSH manager. Also, point 17.2 says "MAY" and not "MUST", so I see no problems here: a client must be prepared to process HTTP-layer errors.
