### ISSUE TITLE
mod_offline with auth_method jwt

### ISSUE THREAD

**Issue by djha-effendi** [processone/ejabberd#3155]
Hi,

When I use "jwt" as aut_method, mod_offline not working until I create an account for this user.
On sending message to a offline user "johndoe@localhost", I got "service unavailable" error.

But, if I create an account 
`ejabberdctl register johndoe localhost passw0rd`

Then the message is stored.

I need to create an account for all my "jwt" users ?
The issue #1721 suggest to implement "is_user_exists" ...  but how to fit that in jwt ?

I expected to use JWT to manage users account and enjoy IM with ejabberd ...

Thanks,

**Comment by prefiks** [comment]
Hello,

Yes there is a problem with jwt in this case because "account creation" is handled completely outside ejabberd, so server don't really know if that user exist or not, and can't give correct answer to that.

We can really do only two things here, forward that check to another authentication method (what is currently done), or assume that all account that all possible account exists (with all problems that this causes, like storing offline messages for not existing users, not being able to use anonymous auth or register account with other method, and i think couple other problems). Both methods have drawbacks, but at least in first case there is workaround that can mitigate that issue.

We could probably add option that switches that behaviour.

**Comment by djha-effendi** [comment]
Thanks for your answer.
On my first "offline message" attempts, I did not understand why that's not work ...
But after got it, I understand the logic of "account creation".

I think it's not really a problem, may be a limit.
I decided to create an account for each new user by catching RabbitMQ message.
Then, I force json auth for all users except admin like mentioned in doc.

> admins can use both JWT and plain passwords, while the rest of users can use only JWT 
https://docs.ejabberd.im/admin/configuration/#jwt-authentication

**Comment by djha-effendi** [comment]
Hi Prefiks,

Are you going to publish a new tag 20.1 on hub.docker.com ?
I think the option "jwt_jid_field" will be avalaible on this version ...

Thanks

**Comment by mremond** [comment]
> Are you going to publish a new tag 20.1 on hub.docker.com ?

Yes

**Comment by djha-effendi** [comment]
Thanks you :)
It's interested feature, that's allow to not regenerate existing tokens !

**Comment by mremond** [comment]
I think the issue is solved.
