### ISSUE TITLE
Add support for SHA-256/512 and/or SHA-3 for password based authentication

### ISSUE THREAD

**Issue by bowlofeggs** [processone/ejabberd#3159]
Greetings!

Is it possible to use SHA-256/512 or SHA-3 for password based authentication, in lieu of SHA-1 or MD5? When reading the docs here, it seems like SHA-256/512 are not supported:

https://docs.ejabberd.im/admin/configuration/#internal

If that is the case, I recommend adding a stronger hash to the list of supported authentication algorithms. SHA-1 is known to be weak, and it is thus not recommended to use it anymore.

**Comment by licaon-kter** [comment]
/close as duplicate https://github.com/processone/ejabberd/issues/2742

Also, are you sure SCRAM-SHA1 really has the same weaknesses like SHA1? 
eg. https://www.gnu.org/software/gsasl/manual/html_node/SCRAM_002dSHA_002d1.html

**Comment by bowlofeggs** [comment]
Hi @licaon-kter, I honestly don't know the difference between SHA-1 and SCRAM-SHA-1.

**Comment by Neustradamus** [comment]
@ProcessOne: Can you reopen #2742, it is always closed...

@bowlofeggs: RFC5208 -> https://tools.ietf.org/html/rfc5802

**Comment by Neustradamus** [comment]
Good news, there are new informations:
- SCRAM-SHA-512(-PLUS): https://tools.ietf.org/html/draft-melnikov-scram-sha-512
- SCRAM-SHA3-512(-PLUS): https://tools.ietf.org/html/draft-melnikov-scram-sha3-512
- Extensions to Salted Challenge Response (SCRAM) for 2 factor authentication: https://tools.ietf.org/html/draft-melnikov-scram-2fa

- gsasl supports SCRAM-SHA-256(-PLUS) since 1.9.1: http://git.savannah.gnu.org/gitweb/?p=gsasl.git;a=blob;f=NEWS;hb=HEAD
I have informed about missing informations in website/manual/docs.
- Dovecot 2.3.10 supports: https://doc.dovecot.org/configuration_manual/authentication/authentication_mechanisms/
- Cyrus SASL/IMAP 2.1.27 supports: https://www.cyrusimap.org/sasl/sasl/authentication_mechanisms.html

**Comment by Neustradamus** [comment]
@bowlofeggs: @prefiks has done a lot of work about SCRAM-SHA-1(-PLUS) + SCRAM-SHA-256(-PLUS) + SCRAM-SHA-512(-PLUS).

SCRAM-SHA3-512(-PLUS) will be added, I think, when the RFC will be here, draft link in the previous comment.

**Comment by Neustradamus** [comment]
@bowlofeggs: New improvements have been added recently!
- https://github.com/processone/xmpp/issues/69
