### ISSUE TITLE
Failed to build ejabberd from source using Vagrant/Virtual box base OS Ubuntu/Trusty

### ISSUE THREAD

**Issue by byteshiva** [processone/ejabberd#3197]
## Environment

- ejabberd version: current git source 
- Erlang version: `vagrant@vagrant-ubuntu-trusty-64:~/ejabberd$ erl +V
Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 10.7
vagrant@vagrant-ubuntu-trusty-64:~/ejabberd$`
- OS: Linux (Debian) - Ubuntu Trusty via vagrant / virtualbox
- Installed from: source 

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

No errors

## Bug description

Please, give us a precise description (what does not work, what is expected, etc.)
I'm trying to build the latest ejabberd to build some module using elixir. But it fails to build. I'm using vagrant ubuntu/trusty as the base os.

```
chmod +x autogen
vagrant@vagrant-ubuntu-trusty-64:~/ejabberd$ ./configure --enable-user=ejabberd
   --enable-elixir
vagrant@vagrant-ubuntu-trusty-64:~/ejabberd$ make test 
```
Here is the make test error.
https://gist.github.com/byteshiva/9e39884308ee925dfb6d10e70e48fc92

**Comment by badlop** [comment]
Hi, I noticed that the file `logs/raw.log` contains valuable information to know what is going wrong

For example, all those calls:
```
make test 
./rebar skip_deps=true ct
./rebar skip_deps=true ct suites=ejabberd
CT_BACKENDS=redis ./rebar skip_deps=true ct suites=ejabberd
```
... crash with this in raw.log:
```
2020-03-20 12:44:55.037886+01:00 [error] Redis connection #1 at localhost:6379 has failed: {connection_error,
                                                   {connection_error,
                                                    econnrefused}}; reconnecting in 5 seconds
```
Similarly, when I enable as BACKENDS mysql or pgsql, it also crashes because I haven't configured the test databases.

So, I followed the instructions mentioned in "make test" to install Redis, MySQL, PgSQL, and setup databases as explained... And now finally this command works. It takes 20 minutes to run, but performs all 1317 test cases, ends without crash and all 1317 are correct:
`CT_BACKENDS=extauth,mnesia,redis,mysql,pgsql,sqlite,ldap ./rebar skip_deps=true ct suites=ejabberd`

So, going back to your setup: check raw.log, it should provide details about your problem.

**Comment by byteshiva** [comment]
> Hi, I noticed that the file `logs/raw.log` contains valuable information to know what is going wrong
> 
> For example, all those calls:
> 
> ```
> make test 
> ./rebar skip_deps=true ct
> ./rebar skip_deps=true ct suites=ejabberd
> CT_BACKENDS=redis ./rebar skip_deps=true ct suites=ejabberd
> ```
> 
> ... crash with this in raw.log:
> 
> ```
> 2020-03-20 12:44:55.037886+01:00 [error] Redis connection #1 at localhost:6379 has failed: {connection_error,
>                                                    {connection_error,
>                                                     econnrefused}}; reconnecting in 5 seconds
> ```
> 
> Similarly, when I enable as BACKENDS mysql or pgsql, it also crashes because I haven't configured the test databases.
> 
> So, I followed the instructions mentioned in "make test" to install Redis, MySQL, PgSQL, and setup databases as explained... And now finally this command works. It takes 20 minutes to run, but performs all 1317 test cases, ends without crash and all 1317 are correct:
> `CT_BACKENDS=extauth,mnesia,redis,mysql,pgsql,sqlite,ldap ./rebar skip_deps=true ct suites=ejabberd`
> 
> So, going back to your setup: check raw.log, it should provide details about your problem.

Thanks for the lead. I'll check it.
