### ISSUE TITLE
Message loss when client is online on server for sometime even after connection loss.

### ISSUE THREAD

**Issue by mailtosagar** [processone/ejabberd#3228]
HI Guys,
I have asked this  before in this [issue](https://github.com/processone/ejabberd/issues/3225) and also read the [old FAQ](https://www.ejabberd.im/faq/tcp/) .  But still the problem remains the same .

resend_on_timeout

1. true: If true, the message will be send again when receiver resume session after becoming online again. But even disconnected receiver is online on server for a short while, server send s the message and deletes it.

2.  Since message once send by server gets deleted. If receiver told server that it has not received some messages (Stream resumption or restart) from where server will bring them back.
 
3.  If senders sends back when the error bounce back received. The message order will get changed.  
 
4.  if_offline: this will work only when all client of a user are offline. So it won't work in this case.

The functionality i offer is (considering no other stanza type except message is not transferring between clients ) :

1. Every Message that come to server should be sent to storage and must be deleted only when server gets the ack for that stanza.

2. when user becomes online again, the stored messages which were not  received by the receiver  will be sent back to the receiver and deleted when acknowledgment received. (They may or may not be treated as the part of the new stream).

Also if bug points can have a solution in the existing architecture. I will gratefull to know them point wise .

Thank you,

**Comment by weiss** [comment]
> `resend_on_timeout: true` If true, the message will be send again when receiver resume session after becoming online again.

We're _not_ talking about the case where the client [resumes the session][1].  The client will simply receive all unacknowledged messages on resumption.  We're talking about the case where the client _fails_ to resume the session and the session therefore times out.  In _this_ case, `resend_on_timeout` determines the behavior.

> But even disconnected receiver is online on server for a short while, server send s the message and deletes it.

I don't understand what you're saying here.  If you set `resend_on_timeout: true`, any unacknowledged messages are "resent" when the session times out.  Which means they end up in offline storage (unless another device is online, in which case that device will receive them).  How, exactly, is this different from the behavior you'd like to see?

[1]: https://xmpp.org/extensions/xep-0198.html#resumption

**Comment by shaggi7** [comment]
is there any way that i can redirect all unacknowledge messages to the offline storage not any other stanza. ??

**Comment by shaggi7** [comment]
Here something i found out.
1. I connect the device(android using smack) , login and enable stream management. 
2. Stream management enables successfully. 
3. then i close the internet(turn off phone net/wifi) . After sometime i reconnect but i see the error
```
Stream closed by local host: Replaced by new connection (conflict)
``` 
i know this error tells us that a different client is logged in with same resource. But i have never changed the device. When I uses a web client to login , it shows this error on everytime i refresh the page . I have kept the resource at the same everytime i connect the server.

So i think what actually happens when we disconnecrt and reconnect,  the server sees us a different client but with the same resource name. As if i do not reset the resource manually, resource name changes everytime i connect. and hence i am unable to resume the session .

What is i am missing so that i can bind my resource to the device and everytime i refresh the server sees me as single client with the same resource name.

**Comment by weiss** [comment]
Where exactly do you see that error?  It would be perfectly normal to see it in the ejabberd logs for example, as it's sent to the _old_ connection (of the same client) in the following case:

1. The old XMPP stream wasn't closed cleanly.
2. ejabberd didn't (yet) notice the TCP stream is dead.
3. The client didn't [resume][1] the session but open a new one.

(You could configure ejabberd to reject the _new_ connection with the same error message instead of closing the old one, but that's not the default behavior.)

> What is i am missing so that i can bind my resource to the device and everytime i refresh the server sees me as single client with the same resource name.

It's [suggested][2] that clients stick to a fixed resource name, and almost all clients I'm aware of do that.

[1]: https://xmpp.org/extensions/xep-0198.html#resumption
[2]: https://wiki.xmpp.org/web/XMPP_IM_Client_Design_Guidelines#Description_6

**Comment by weiss** [comment]
> is there any way that i can redirect all unacknowledge messages to the offline storage after the stream has not been resumed in a specified time??

Set the `mod_stream_mgmt` option `resend_on_timeout: true`.

I'm now closing this issue because it's neither about an ejabberd bug nor about a feature wish.  I understand it's not trivial to build an XMPP client that implements [stream management][1] (and optionally [MAM][2]) correctly to avoid message loss, but ejabberd's bug tracker is not the right place to ask for help with these question.

[1]: https://xmpp.org/extensions/xep-0198.html
[2]: https://xmpp.org/extensions/xep-0313.html
