### ISSUE TITLE
Harmonization of the code: "	" vs "    "

### ISSUE THREAD

**Issue by Neustradamus** [processone/ejabberd#3244]
Currently there are several differences in and between files:
- "    " (normal spaces)
- "	" (tab key)

It will be nice to harmonize the code with same "technical".

Of course, this ticket is about all ProcessOne projects/repositories.

**Comment by badlop** [comment]
Why four spaces? Erlang guidelines recommend two spaces: https://github.com/inaka/erlang_guidelines/blob/master/README.md#spaces-over-tabs

**Comment by weiss** [comment]
I'm not necessarily a fan of our indentation either.  We do four-space indentation and replace 8 spaces with tabs.  Which I personally don't like too much, but I _think_ that's the default setting of Emacs' Erlang support?  Plus, there are places in the code where 8 spaces are _not_ replaced with tabs, so it's not consistent.

It would of course be trivial to make things consistent, at least the tabs vs. spaces thing.  However the big downside of changing large amounts of whitespace is that it makes it much harder to look up changes in the Git history.  When you try to figure out when/we a specific piece of code was added, you'll keep stumbling over that monster whitespace change commit.

**Comment by Neustradamus** [comment]
I have done this ticket because I have seen in a same file:
- 4 normal-spaces
and
- 1 key-tab-space

In a function, there are mixed "spaces", the alignment are not same...
Not easy to read the code...

**Comment by mremond** [comment]
The standard should be the Emacs format of the Erlang mode.

**Comment by badlop** [comment]
> Currently there are several differences in and between files

Yes, this is well known.

> It will be nice to harmonize the code

Yes, it would be nice. I already tried a massive indentation change in November 2010.

The code looked nice, but it was very very difficult to investigate source code changes, because the massive commit blocked it, like a big wall that was impossible to jump to see old changes. It was hell. So, I didn't commit this massive change, nobody else that I asked wanted it, and today nobody wants that massive change.

But there are good news, there is a good way to solve this: in every new commit, use the proper indentation, as explained in the documentation:
```
there is still a lot of poorly written legacy code
(which is being leisurely rewritten),
but the new code should be written with keeping these rules in mind.
```
https://docs.ejabberd.im/developer/guide/#coding-style-convention

> In a function, there are mixed "spaces", the alignment are not same...  Not easy to read the code...

Because you have badly configured text editor. Use good text editors, and configure them correctly.

In Emacs:
```
(setq erlang-mode-hook
    (function (lambda ()
                (setq indent-tabs-mode nil)
                (setq erlang-indent-level 4))))
```

In Vim:
```
set tabstop=8
set expandtab
set shiftwidth=4
set softtabstop=4
```

Instead of proposing to break ejabberd git commit history, you should fix your editor configuration.

**Comment by Neustradamus** [comment]
@badlop: It has been closed without changes ;)

**Comment by Neustradamus** [comment]
@badlop: It is possible to harmonize the code?
To have same in all files?

Thanks in advance.
