### ISSUE TITLE
Invalid YAML in example config

### ISSUE THREAD

**Issue by htgoebel** [processone/ejabberd#3301]
The example config contains invalid YAML, e.g.
https://github.com/processone/ejabberd/blob/16645a3c0ad76ca09e3f18626efe51e0ecfd2244/ejabberd.yml.example#L112-L114
This is invalid YAML both in YAML 1.0 (see https://yaml.org/spec/1.0/#id2564813Inha):
> It is an error for two equal key entries to appear in the same mapping node

and YAML 1.2 https://yaml.org/spec/1.2/spec.html#mapping// 
> with the restriction that each of the keys is unique

Introduced in a02cff0e780bb7355315.

**Comment by badlop** [comment]
In fact, it seems only the second definition takes effect in practice in ejabberd, in my tests.

For the option to be valid and take effect properly, it would require a change like this, right?
```diff
diff --git a/ejabberd.yml.example b/ejabberd.yml.example
index 7082dab98..21f78eb31 100644
--- a/ejabberd.yml.example
+++ b/ejabberd.yml.example
@@ -89,6 +89,9 @@ access_rules:
   c2s:
     deny: blocked
     allow: all
+  api-admin:
+    - allow: admin
+    - allow: loopback
   announce:
     allow: admin
   configure:
@@ -108,16 +111,10 @@ api_permissions:
     what: "*"
   "admin access":
     who:
-      access:
-        allow:
-          acl: loopback
-          acl: admin
+      access: api-admin
       oauth:
         scope: "ejabberd:admin"
-        access:
-          allow:
-            acl: loopback
-            acl: admin
+        access: api-admin
     what:
       - "*"
       - "!stop"
```

**Comment by htgoebel** [comment]
@badlop The example, prior to a02cff0, did have a list of entries *in place*. The `-` in front of each entry have erroneously been removed in a02cff0, as you can easily see at
https://github.com/processone/ejabberd/commit/a02cff0e780bb735531594c4ece81e8628f79782#diff-19e0c10699732f76181f70cfbec95d38L90-R93  (and above and below).

Your proposed solution does not actually fix this, but works around the issue by defining a new acl. I suggest restore the old *in place* list, as IMHO it is important to show this possibility.

And as you can see in the [second example of the access_rights documentation](https://docs.ejabberd.im/admin/configuration/basic/#access-rights), using a list here is still valid. So the example config should keep this example.

**Comment by weiss** [comment]
_(Wrote this before @htgoebel's response and forgot to press the green button ...)_

Yes, the error was that the `acl`s weren't specified as a list, and yes, moving this into an explicit access rule for deduplication makes sense (I'm just not entirely sure the `-` in `api-admin` is valid, I'd use an underscore for consistency either way).

I think it's problematic how our access rule parsing is non-strict about enforcing this to be a list rather than a map.  Our example config and our docs are inconsistent about this as well.  I'd prefer `- access: api_admin` and `oauth: [...]` even if it happens to work in this case.  Just as I'd prefer `- ip: [...]` [in the `"public commands" section][1], and so on.  The fact that we even got this wrong in our own example configuration shows how being non-strict about this just adds confusion.

[1]: https://github.com/processone/ejabberd/blob/20.04/ejabberd.yml.example#L123-L124

**Comment by badlop** [comment]
Aha, now I start to understand what you mean.

This YAML example uses correctly a **sequence**, and is correctly parsed by ejabberd (xmlrpc can only be used by loopback clients that provide admin rights):
```yaml
api_permissions:
  "admin access":
    from: ejabberd_xmlrpc
    who:
      access:
        allow:
          - acl: loopback
          - acl: admin
    what:
      - registered_users
```

Three lines were replaced with this *incorrect* **map**, as you first mentioned. Nobody cared, because it's accepted by ejabberd:
```yaml
        allow:
          acl: loopback
          acl: admin
```

Surprisingly, both YAML examples are converted into exactly the same erlang representation by yconf:
```erlang
{{api_permissions,global},
 [{<<"admin access">>,
   {[ejabberd_xmlrpc],
    [{access,[{allow,[{acl,loopback},{acl,admin}]}]}],
    {[registered_users],none}}}]}
```
I imagine @zinid implemented it that way to allow admins reduce the amount of syntax characters in the configuration file. And this was not a noticeable problem for most of the file... except this wrong map.

So yes, as you mentioned, the example config (and any other examples out there that show wrong yaml) should be fixed.

**Comment by htgoebel** [comment]
> Three lines were replaced with this incorrect map, as you first mentioned. Nobody cared, because it's accepted by ejabberd:

Exactly this is the point!

If this is parsed correctly by this parser, the parser doesn't parse "YAML" but only a "YAML-like" format. Shall I file a separate bug report for this?

**Comment by badlop** [comment]
I suspect that behaviour in the YAML parser was not a mistake in design or bug in implementation. I think it was done on purpose, following the Robustness principle https://en.wikipedia.org/wiki/Robustness_principle
> Be strict in what you provide, be relaxed in what you accept

In this sense, ejabberd.yml and other example configurations should be fixed to be strictly YAML valid. But the yaml parser should still accept this relaxed YAML-like syntax.

**Comment by htgoebel** [comment]
@badlop THansk for fixing the examples.
Still the parser needs to be fixed, too, as the Robustness principle is not applicable here for several reasons:
1. Postel's Law was about messages received from others. aiming to enable communication. Here config files are parsed, which can be corrected easily.
2. What entity the parser to convert the invalid format into a list? Why not accept the first value, why not the last? Any of these would be pure guessing.
3. In this very case the config is about acls and permissions. Accepting invalid format here can lead to unintended permissions granted or denied.

There have been some infamous bugs in systemd, based on a wrong application of Postel's Law. One Bug was as follows: If a systemd .service file contains a `User=` entry, but the user does not exists, systemd did take this entry as "invalid", invalid entries are ignored, and the program was executed as root. These are a lot of discussion until Poettering accepted that from an administrators POV the option was valid, but the missing (or mistyped) user is the issue and systemd should bail out.

Shall I file a separate issue for this?

**Comment by weiss** [comment]
@htgoebel, I would strongly agree with all of that.  If we were writing a new piece of software.  But we're talking about configuration settings of an Internet server widely deployed in production, and we usually try hard not to break existing configurations.  I.e., my own reason for accepting this configuration (for the time being) would not be the Robustness principle but backwards compatibility.  I think it would be nice if the parser would log a `[warning]`, though.

BTW:

> invalid entries are ignored [by systemd]

Which I think is a problematic decision, for the same reason.

**Comment by badlop** [comment]
> If this is parsed correctly by this parser, the parser doesn't parse "YAML" but only a "YAML-like" format. Shall I file a separate bug report for this?

The YAML parser and Yconf correctly detect (and complain) a map with duplicate keys:

https://github.com/processone/yconf/blob/aba6e0bb5d274482caf5447c77d71b50c9418026/test/yconf_test.erl#L916-L921

```erlang
bad_unique_map_test() ->
    File = file(["a: {c: 2, b: 1, c: 3}"]),
    ?checkError(
       {duplicated_key, c},
       yconf:parse(File, #{a => yconf:map(yconf:atom(), yconf:any(),
					  [unique])})).
```

It is ejabberd in acl.erl who treats the ACL rules as an erlang list instead of an erlang map, to support this YAML-like relaxed syntax, for the sake of administration simplicity.
