### ISSUE TITLE
Web Admin missing Menu Information 

### ISSUE THREAD

**Issue by jeremiasdsa** [processone/ejabberd#3337]
## Environment

- ejabberd version: 20.04
- OS: Linux on AWS EC2 instance
- Installed from: $wget https://www.process-one.net/downloads/downloads-action.php?file=/20.04/ejabberd-20.04-linux-x64.run

## Errors from error.log/crash.log

No errors

## Bug description

My server is missing some information. The screen I got is different from official docs, can you help me to solve it? 

<img width="617" alt="Screen Shot 2020-07-22 at 10 15 53" src="https://user-images.githubusercontent.com/9071775/88180877-671b4f80-cc04-11ea-8e9b-928021879481.png">

**Comment by badlop** [comment]
I guess you mean two unknown sections "Access Control Lists" and "Access Rules". shown in the image at: https://docs.ejabberd.im/admin/guide/managing/#web-admin

Those two sections were removed from WebAdmin in ejabberd 19.08, more precisely in https://github.com/processone/ejabberd/commit/a02cff0e780bb735531594c4ece81e8628f79782

But that screenshow was not updated since 2017! I've taken a recent screenshot and uploaded it to the documentation website.

Thanks for reporting this!
