### ISSUE TITLE
Bad value of attribute 'to' in tag <presence/> qualified by namespace 'jabber:client'

### ISSUE THREAD

**Issue by relbraun** [processone/ejabberd#3347]
## Environment

- ejabberd version: 19.09.1
- Erlang version: 19
- OS: Linux (Debian)
- Installed from: source 

No errors

## Bug description

When I try to be occupied in MUC room and the "nick" that I send is combination of latin and Hebrew letters I get a 400 error response:

This is the stanza I sent:

```
<presence from="myjid@myxmpp.com/converse.js-120538695" to="gjbjsbeeed_13@conference.myxmpp.com/name חיבה" xmlns="jabber:client"><x xmlns="http://jabber.org/protocol/muc"><history maxstanzas="2"/></x></presence>
```
and this is the response:
```
<presence xmlns='jabber:client' from='gjbjsbeeed_13@conference.myxmpp.com/name חיבה' to='myjid@myxmpp.com/converse.js-120538695' type='error'><x xmlns='http://jabber.org/protocol/muc'><history maxstanzas='2'/></x><error code='400' type='modify'><bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Bad value of attribute &apos;to&apos; in tag &lt;presence/&gt; qualified by namespace &apos;jabber:client&apos;</text></error></presence>
```

**Comment by prefiks** [comment]
Hello,

So you are getting this error because this is really forbidden by xmpp spec (mixing bidirection characters that are aligning to left and right are not permitted, presumably because there can be ambiguities where different combination may lead to output that is displayed in same way). If you are interested in checking rules that our code check, you can read about them here: https://tools.ietf.org/html/rfc3454#section-6.
