### ISSUE TITLE
How to mark presence on a specific MUC room?

### ISSUE THREAD

**Issue by jnmayur** [processone/ejabberd#3405]
Hi

Here is a case we're struggling to find a solution for:
User A subscribes to room1 & room2. We're using MUC & subscriptions.
User A connects to xmpp using js client in our app. As soon as he connects and opens up a room, he receives all messages from room1 & room2(after marking presence). Is there a way we can mark presence on specific rooms after connecting to XMPP, so that we can avoid receving live & offline messages for all other rooms?

P.S: We're using the same jid for User A for both rooms. One way could be to create different Jid for User A for room1 & room2 but we're trying to avoid this to make it consistent with our data model.

Please suggest if there are ways to acheive this.

**Comment by licaon-kter** [comment]
`autojoin` flag for bookmarks, don't set it maybe ?!

https://xmpp.org/extensions/xep-0048.html#format-conference

or 

https://xmpp.org/extensions/xep-0402.html#sect-idm45128499026272

**Comment by prefiks** [comment]
Are you storing muc jid addresses in your roster? Usually you need to explicitly send direct presence to room to join it, but if you store jid to room in roster, then sending general presence would send presence to roster members, and will join room for you. If you don't want that don't keep rooms in roster.

**Comment by badlop** [comment]
I assume this scenario:

1. User A *subscribes* to room1 & room2
2. User A connects to xmpp by **setting a positive priority in XMPP session**
3. Automatically, he receives all mucsub notifications from room1 & room2

> Is there a way ... we can avoid receving live & offline messages...?

If you were asking this, then there's a solution: In step 2, instead of positive priority in XMPP session, the client can set negative priority (-1, -2 or whatever). That way, ejabberd will NOT send offline messages or any mucsub notifications. 

Later, if the client switches priority to positive (0, 1, 2, whatever positive), then ejabberd will send the offline messages and the mucsub notifications that are awaiting to be sent.

> Is there a way we can mark presence on specific rooms after connecting to XMPP, so that we can avoid receving live & offline messages for all other rooms?

For mucsub notifications, not possible.

If you join rooms and receive live messages, yes! As other people explained, it's simple: don't join those rooms if you don't want to receive live messages!

**Comment by jnmayur** [comment]
> Are you storing muc jid addresses in your roster? Usually you need to explicitly send direct presence to room to join it, but if you store jid to room in roster, then sending general presence would send presence to roster members, and will join room for you. If you don't want that don't keep rooms in roster.

No my rosterusers table is empty. Not storing anything in rosters. Using ejabberd only with muc.

**Comment by jnmayur** [comment]
@badlop Let me explain it further. We're not using muc in a single view. What I mean is unlike whatsapp where you can see all your groups together, our chats(rooms) are splitted across screens in our app for the same user. Ex: For UserA, there'll be one muc room for marketplace and another muc room for talking to contact center. So effectively we want these to be isolated. So if UserA comes to our app and we initiate a xmpp session for marketplace room this should not impact live/offline messages for contact center room. 
Here is what happens now
1. We open the marketplace view
2. We connect to xmpp without any priority.
3. We mark presence by just sending <presence xmlns="jabber:client"/>
4. We receive all live and offline messages for all subscribed rooms. (marketplace & contact center)
5. We discard all messages received other than those received on the current room. More like a hack.

So user has to be there in all rooms at all times but live/offline messages should get delivered to relevant(presence marked or online) room only.

**Comment by badlop** [comment]
> For UserA, there'll be one muc room for marketplace and another muc room for talking to contact center. So effectively we want these to be isolated. So if UserA comes to our app and we initiate a xmpp session for marketplace room this should not impact live/offline messages for contact center room.

If I understand your explanation correctly, I think there may be at least two ways that it could be implemented.

**A) MUCSub + MAM**

Subscribe to the rooms, but later login to XMPP session with negative priority, so new live messages are not received.

Each time the user switches to a _chatroom view_, your client explicitely requests to ejabberd (using MAM protocol) the room messages since date X. In this case, new live messages are not received. Your client has to request them explicitely for the room.

https://docs.ejabberd.im/developer/xmpp-clients-bots/extensions/muc-sub/#synchronization-of-muc-messages-leveraging-mam-support

**B) MUC + MUC recent history**

In this case, forget about Mucsub and MAM at all.

Each time the user switches to a chatroom view, your client joins the room as defined in XEP-0045, and ejabberd will send the recent discussion history. Those messages have the timestamp, so it's your client's task to show to the user only the messages since date X.

https://xmpp.org/extensions/xep-0045.html#enter-history

**Comment by jnmayur** [comment]
@badlop I believe I don't have option B as MUC doesn't solve offline messages well, and we use offline_message_hook to send push notifications to all offline users. Please correct me if I'm wrong here.

On option A - We're already using MucSub + MAM. We load history of messages from archive table and while doing so we exclude messages from spool. And rely on presence to receive offline messages.

I get your point of setting negative priority and not get offline messages but does that mean I'll have them forever in my spool table? Also what do you mean by 'new live messages are not received'?

**Comment by badlop** [comment]
> I get your point of setting negative priority and not get offline messages but does that mean I'll have them forever in my spool table?

In the default configuration there's a limit of 100 messages in the account's offline spool. Search for max_user_offline_messages in
https://docs.ejabberd.im/admin/configuration/modules/#mod-offline

An admin can also run this query to delete them:
https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#delete-old-messages

> Also what do you mean by 'new live messages are not received'?

I mean that, when the client starts a XMPP session with a negative presence priority, ejabberd will not deliver new messages to that session. For example, new room messages are not delivered to the client.

```
   For a message stanza of type "chat":

   o  If the only available resource has a negative presence priority
      then the server SHOULD either (a) store the message offline for
      later delivery or (b) return a stanza error to the sender, which
      SHOULD be <service-unavailable/>.

```
https://www.rfc-editor.org/rfc/rfc6121.html#section-8.5.2.1.1
