### ISSUE TITLE
Is it a good idea to alter core ejabberd tables like archive?

### ISSUE THREAD

**Issue by jnmayur** [processone/ejabberd#3440]
So our use case is that we want to support media upload, location sharing and much more within chat in the product.
For this what we essentially do is manage uploads at our own infrastructure and pass references(say cdn file path) <filePath> in xml stanzas along with custom fields like <messageType> which are recevied by the client and we have written logic to render elements based on the message type. While our logic works perfectly fine, what we need is an ability to query on the data, say for example how many messages have images, location etc. For this to happen, we have two options.
1. Alter the archive table schema and add a field called as message_type, this would be populated by listening to incoming message hook and parsing the xml sent by the client.
2. Shoot an event or call an API on incoming message hook and save this information(message_type, message_id, username) in an extended table which helps us query later.

Which of the approaches is recommeded? I'm not sure if it's a good idea to alter schema of core tables. Please suggest.

**Comment by badlop** [comment]
Considering that this is a custom development, for some custom requirement that only you (and your users of course) will benefit, for a server that will run for years... And considering this is not an experiment or school project... 

I think you will get more satisfied in the long term by writting your custom ejabberd module, and store that information in a custom table. Use hook-events if possible, otherwise add small calls in ejabberd to your module.

This path will require some more code than altering ejabberd, as you have to manage your specific table.

But probably the benefits will pay: that way you can update your ejabberd version with minimum problems, and you have your custom code and data encapsulated and under your control.

**Comment by jnmayur** [comment]
@badlop Makes total sense. I had a similar view to keep the core infra and modules as separated as possible to avoid merge conflicts. Thanks for the suggestion. It helps.
P.S: Yeah it's not a small scale project. We've close to 3 million users who'll use chat.
