### ISSUE TITLE
how to deal with mnesia:wait_for_tables is blocking all the time.

### ISSUE THREAD

**Issue by yanyiwu** [processone/ejabberd#349]
My ejabberd node is ok in the past days,  my when i restart my machine, 
i found ejabberd cannot start as usual ,  and it blocking in code `mnesia:wait_for_tables(mnesia:system_info(local_tables), infinity)` when starting.

This mnesia node contain many registered account , i do not want to abandon it.

Is there a good way to deal with that? Thanks very much.

**Comment by mremond** [comment]
Mnesia database is intended only for moderate volumes. Passed a certain volume, you should use a relational database to store persistent data. Otherwise indeed, you have to wait for Mnesia recovery process to complete (That's a bit like FSCK).

... And you are right, it is better not to interrupt it.
