### ISSUE TITLE
The tools build option is inconsistent

### ISSUE THREAD

**Issue by darix** [processone/ejabberd#3508]
## Environment

- ejabberd version:  21.01 (also affects older versions)

## Bug description

the --enable-tools option gives the impression that it is for developers only. so far I always built our rpm with the option. because it seems also the tools for the prosody import are guarded with that conditional (for luerl).

now with 21.01 we get a new build dep which seems is only needed at development time 
(ejabber-po) also other tools like xml_compress_gen.beam doesnt seems to be needed at runtime. 

can we split this in --enable-tools and --enable-development-tools?

**Comment by weiss** [comment]
> it seems also the tools for the prosody import are guarded with that conditional (for luerl).

Yes, since commit 121d12f4d1a2deee59bf22c15081d2204d303625.  Good example of why commit messages should explain _why_ something is done, rather than _what_ is done (the latter is obvious from the diff, the former isn't).

Anyway, I think that's wrong, and we should add a separate `--enable-lua` (or whatever) indeed.
