### ISSUE TITLE
DNS lookup failed: non-existing domain

### ISSUE THREAD

**Issue by kpbg** [processone/ejabberd#3636]
## Environment

- ejabberd version: 21.04
- Erlang version: 11.1.7
- OS: Ubuntu 18.04 / running on AWS
- Installed from: ejabberd_21.04-0_amd64.deb

## Errors from ejabberd.log
2021-07-05 06:04:24.658 [info] <0.9346.97>@ejabberd_s2s_out:init:289 Outbound s2s connection started: my.synthesisvr.com -> system
2021-07-05 06:04:24.662 [debug] <0.9346.97>@ejabberd_hooks:safe_apply:231 Running hook s2s_out_closed: ejabberd_s2s_out:process_closed/2
2021-07-05 06:04:24.662 [warning] <0.9346.97>@ejabberd_s2s_out:process_closed:157 Failed to establish outbound s2s connection my.synthesisvr.com -> system: DNS lookup failed: non-existing domain; bouncing for 275 seconds

## Bug description
I see this has been raised before, but from a guy not using an up-to-date version. I just found my server doing the same and I got it fixed by restarting ejabberd.

For comparison, here is the log after the restart:
2021-07-05 06:06:53.441 [debug] <0.9465.97>@ejabberd_s2s:start_connection:385 Finding connection for {<<"my.synthesisvr.com">>,<<"system">>}
2021-07-05 06:06:53.441 [debug] <0.9465.97>@ejabberd_s2s:choose_pid:435 Using ejabberd_s2s_out <0.9346.97>
2021-07-05 06:06:53.441 [debug] <0.9465.97>@ejabberd_s2s:route:352 Sending to process <0.9346.97>

Any advice on what could have caused this?

**Comment by badlop** [comment]
I guess nobody have any advice. Did you find any other clues? Can this issue be closed?

**Comment by Millesimus** [comment]
@badlop Could we re-open this? I have the same issue with several remote servers but, I could not find any pattern to the servers (tried with xmpp-dns).

The most severe consequences of this are that some users on remote systems lose connection with MUCs hosted on my server and, consequently, do not receive any messages from these MUCs.

Maybe it would help already if you could clarify the log message for me. When it reads:

> Failed to establish outbound s2s connection conference.example.org -> exbmple.org : DNS lookup failed: non-existing domain; bouncing for 275 seconds

Does that mean that my server (conference.example.org) did not perform a successful DNS lookup for exbmple.org (a)? Or does it mean that my server tried to contact exbmple.org but then exbmple.org performed a DNS lookup for conference.example.org, which then failed so that exbmple.org answered to my server: "DNS lookup failed: non-existing domain"?

**Comment by licaon-kter** [comment]
As of a few hours ago some conversations.im related domains are offline, this is what you are seeing?

**Comment by Millesimus** [comment]
> As of a few hours ago some conversations.im related domains are offline, this is what you are seeing?

Unfortunately not, since this problem had already been going on since a long time (and I see it with unaffected services as well). I guess there is something wrong with my setup. I noticed that – while generally all vhosts seem to be subject to this problem from time to time–, it can even happen that one (MUC) vhost is no longer connected to exbmple.org while another one is (re-inviting the account on exbmple.org to the affected MUC works without any problem).

**Comment by licaon-kter** [comment]
Then add your gist of the config, maybe more detailed logs, cross check dns, etc

**Comment by prefiks** [comment]
That error means that our server was not able to establish connection to that exbmple.org, my guess would be that you have mucsub subscriber that using jid from that server in one of rooms.

**Comment by Millesimus** [comment]
@prefiks Thanks! I'm still puzzled as I don't yet understand why it happens in such irregular intervals, but I'll keep investigating.
