### ISSUE TITLE
Ejabberd 21.07 Mnesia backup error

### ISSUE THREAD

**Issue by member7me** [processone/ejabberd#3704]
Hello

## Environment

- ejabberd version: 21.07
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 12.1.1
- OS: Debian 11
- Installed from: distro package

After upgrading to ejabberd 21.07, I can't do backup of DB. Receive such errors:

**Web interface**

 - node/ejabberd@localhost/backup/
Store binary backup: `Error: {'EXIT',{error,undef}}`
Store plain text backup:: OK, it's doing well.

**System console:** 

> `ejabberdctl backup ejabberd.backup`

Receive:
```
Error: cannot_backup
Can't store backup in "/var/lib/ejabberd/ejabberd.backup" at node ejabberd@localhost: {'EXIT',{error,undef}}
```

Configuration is default, it hadn't changed by years. It's the same as on ejabberd 21.04 before upgrade, where everything working fine.

What is the problem?
How to fix it? 

Thanks for answers.

**Comment by badlop** [comment]
18.07? That version does not exist

**Comment by member7me** [comment]
I'm sorry. I made a typo.
version is 21.07 - last one.

**Comment by badlop** [comment]
It's a strange problem. I think ejabberd.yml is not involved at all.

The command works correctly for me using ejabberd 21.07 installed from source code. I can't try the debian package of 21.07 because it requires a recent system that I don't have access.

> {'EXIT',{error,undef}}

This is erlang complaining that a function called is not defined, usually because it's for an older erlang version, or because the required beam file cannot be found.

In fact, the ejabberdctl backup command just calls this Erlang/OTP function, which is included in erlang and surely you already have installed and available:  `mnesia:backup(Path)`

You can try that function yourself, in a small erlang system:
```
❯ erl
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Eshell V11.1.8  (abort with ^G)
1> mnesia:start().               
ok
2> mnesia:backup("/tmp/asd.txt").
ok
3> 
```

You can also try that in your ejabberd node manually:
1. Start ejabberd in live mode, or attach an erlang console to your running ejabberd
2. Now execute in that erlang shell:
```
(ejabberd@localhost)1> 
(ejabberd@localhost)1> mnesia:backup("/tmp/asd.txt").
ok
```

You probably have mnesia.beam installed, as it's included in erlang-mnesia debian package: https://packages.debian.org/sid/erlang-mnesia

And the corresponding function has not changed in many years, so it should work in whatever erlang version you have installed
https://www.erlang.org/doc/man/mnesia.html#backup-1
