### ISSUE TITLE
Wrong encoding in send_stanza command from NodeJS child_process

### ISSUE THREAD

**Issue by haithngn** [processone/ejabberd#3739]
## Environment

- ejabberd version: 21.07
- Erlang version: Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe] Eshell V10.3.4
- OS: Linux (CentOS 7)
- Installed from: official rpm

No errors

### Send stanza from terminal bash:
```bash
ejabberdctl send_stanza 611273cb363d4a8bada7cbb9@localhost 60fa3a4292d099fa7fcad220@localhost "<message to='60fa3a4292d099fa7fcad220@localhost' from='611273cb363d4a8bada7cbb9@localhost/611273cb363d4a8bada7cbb9' type='chat' id='61c2a5c2e5eacd26ca41fa440984170947467' xmlns='jabber:client'><header xmlns='urn:xmpp:header' user_id='611273cb363d4a8bada7cbb9' name='trần châu toàn mỹ' avatar=''/><content_type xmlns='urn:xmpp:content_type' type='content_type/text'/><request xmlns='urn:xmpp:receipts'/><origin-id xmlns='urn:xmpp:sid:0' id='YBLZ-RRTC-ZS3K-L'/><body>trần châu toàn mỹ</body></message>"
```

The message inserted to MySQL is correct encoding: **trần châu toàn mỹ**

### Send stanza from NodeJS child_process:
```js
let send_msg_cmd= `ejabberdctl send_stanza 611273cb363d4a8bada7cbb9@localhost 60fa3a4292d099fa7fcad220@localhost "<message to='60fa3a4292d099fa7fcad220@localhost' from='611273cb363d4a8bada7cbb9@localhost/611273cb363d4a8bada7cbb9' type='chat' id='${message_id}0984170947467' xmlns='jabber:client'><header xmlns='urn:xmpp:header' user_id='611273cb363d4a8bada7cbb9' name='trần châu toàn mỹ' avatar=''/><content_type xmlns='urn:xmpp:content_type' type='content_type/text'/><request xmlns='urn:xmpp:receipts'/><origin-id xmlns='urn:xmpp:sid:0' id='YBLZ-RRTC-ZS3K-L'/><body>trần châu toàn mỹ</body></message>"`;
    console.log(send_msg_cmd);
    let send_result = await execSync(send_msg_cmd);
```

The message was inserted to MySQL is wrong endcoding: **tráº§n chÃ¢u toÃ n má»¹**
```xml
<message to='60fa3a4292d099fa7fcad220@localhost' from='611273cb363d4a8bada7cbb9@localhost' type='chat' id='61c2ab37e5eacd26ca4209b90984170947467' xmlns='jabber:client'><header xmlns='urn:xmpp:header' user_id='611273cb363d4a8bada7cbb9' name='tráº§n chÃ¢u toÃ n má»¹' avatar=''/><content_type xmlns='urn:xmpp:content_type' type='content_type/text'/><request xmlns='urn:xmpp:receipts'/><origin-id xmlns='urn:xmpp:sid:0' id='YBLZ-RRTC-ZS3K-L'/><body>tráº§n chÃ¢u toÃ n má»¹</body></message>
```

On the local server (Mac OS) this bug does not happen.
I'm not sure is this a bug from ejabberd, I just hope you can take a look or give me any advice

**Comment by badlop** [comment]
What did you find? When you send the query directly in the shell, the encoding is correct. When you write a file in a programming language, and tell this to open a shell and send the query... the encoding is wrong.

That client didn't handle the encoding correctly before sending the shell query.

```
❯ file api.perl
api.perl: UTF-8 Unicode text, with very long lines

```

Some ideas:
A) check the file encoding. I guess it should be UTF-8
B) Instead of using ejabberdctl to perform the send_stanza, use other method (XMLRPC, ReST... see https://docs.ejabberd.im/developer/ejabberd-api/#understanding-ejabberd-commands ). But I guess you may have the same file encoding problem as A)
C) Instead of using the send_stanza ejabberd API to send the stanza... write a small XMPP client that logins to that account and sends the stanza itself. Obviously, if problem A is still present, this will fail too.

**Comment by haithngn** [comment]
@badlop thank you for the answer, you are correct, my issue is encoding ASCII.
I changed the encoding to UTF-8 but no luck. But, from your reply, we have another way to deal with these kinds of XML messages. The client-side will decode ASCII to UTF-8 during parsing them.

The message should be sent from the back-end side so we cannot apply #B or C, I think they are possible to solve the encoding issue.

Thanks, @badlop again :+1:
