### ISSUE TITLE
USER STATUS ISSUE 

### ISSUE THREAD

**Issue by Yogesh-Dubey-0804** [processone/ejabberd#3785]
i have launhed my ejjaberd server on aws ami instance at client side im using react native with xmppjs library now i wanted to show online offlie in order to do so i used to send presence with unavailable stanza but at my ejabberd console im seeing the user still online , now i how can i appear him to be online and close the connection properly well sending unavailable to show offline works fine with openfire but not sure what to do here ?

i can offer buy me a coffee its

**Comment by licaon-kter** [comment]
ejabberd version? config?

**Comment by Yogesh-Dubey-0804** [comment]
Ejabberd version 16.09
Deployed on linux 2 AMI

**Comment by licaon-kter** [comment]
That's like 5-6 years old, do try to use a newer, supported version instead. Latest is 21.12.

**Comment by badlop** [comment]
> at client side im using react native with xmppjs library

So, you wrote a custom client yourself.

> i wanted to show online offlie in order to do so i used to send presence with unavailable stanza but at my ejabberd console im seeing the user still online

So, you are having a problem with your custom client... Surprise!

Try with well-known XMPP clients like Gajim, Psi, ... Do they they work correctly?

Those clients have a "XMPP console",  or "XML window" that shows what stanzas they send and receive. Compare what those clients send and what your client sends... you may find where the problem is.
