### ISSUE TITLE
<status>Replaced by new connection</status>

### ISSUE THREAD

**Issue by praveenoms** [processone/ejabberd#380]
Hi ,
The ping stanza get failed on client  after receiving below presence ,what is the reason behind this is this something related to Ejabberd Config?.
<b><presence from='XXXXX@XXX.com/3059ED855FFD4159A63335BE400C900D' to='XXXX@XXXX.com/Smack' type='unavailable'><status>Replaced by new connection</status></presence></b></b>

 Do we need to reconnect the client again after receiving it, to bind with correct resource?

Those are current settings:
 ## XEP-0198
    stream_management: true
    resend_on_timeout: true
    resume_timeout: 30
    max_ack_queue: 1000

  mod_ping:
    send_pings: true
    ping_interval: 30
    timeout_action: kill

**Comment by szymonpk** [comment]
@praveenoms Did you figured this out?

**Comment by mckaygerhard** [comment]
this is a old but since yesterday i xperience similar behavior:

if i used pidgin (that was working perfectly with same resource identifier) with a custon resource identifier, same as i used in my chat mail, connection failed.. 

if i used pidgin with ramdon resource and/or in chat a ramdom chat resource identifier, every works!

this its used ejabberd 2.1.13 from debian and stable compiled manually

**Comment by mckaygerhard** [comment]
related to #1164

**Comment by mremond** [comment]
No, does not seem related at all to #1164.
