### ISSUE TITLE
Probable typo in path when building rpm

### ISSUE THREAD

**Issue by FathiBenNasr** [processone/ejabberd#3825]
Before creating a ticket, please consider if this should fit the discussion forum better:
https://github.com/processone/ejabberd/discussions

## Environment

- ejabberd version: 22.05
- Erlang version: `erl +V`: -bash: erl: command not found
- OS: Linux (Debian)
- Installed from: official rpm

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```yaml
loglevel: 4
...
```

## Errors from error.log/crash.log

```
[critical] <0.172.0>@ejabberd_app:start/2:72
 Failed to start ejabberd application:
 Invalid value of option captcha_cmd:
 Failed to read file '/opt/ejabberd-22.05/lib/ejabberd-22.05/priv/bin/captcha.sh':
 no such file or directory
```

## Bug description

I think there was a typo when building rpm package as captcha.sh path
in version 22.05 is `/opt/ejabberd-22.05/lib/ejabberd-22.5.0/priv/bin/captcha.sh`
 while in 21.12 it was `/opt/ejabberd-21.12/lib/ejabberd-21.12/priv/bin/captcha.sh`

I think some path needs to be changed
 from `opt/ejabberd-22.05/lib/ejabberd-22.5.0`
 to `opt/ejabberd-22.05/lib/ejabberd-22.05`

**Comment by badlop** [comment]
> some path needs to be changed

Right, you need to change the path in your configuration file.

The new installers since ejabberd 22.05 are built using a different method. The new method uses OTP releases, as built by Elixir's mix. And those OTP releases use version numbers formatted as `X.Y.Z`. You can see all the libraries in `opt/ejabberd-22.05/lib` follow that versioning schema.

We humans call this release `ejabberd 22.05`, and internally its formatted version number is "22.5.0", and that's the path.
