### ISSUE TITLE
High CPU usage with new docker image

### ISSUE THREAD

**Issue by marzzzello** [processone/ejabberd#3826]
## Environment

- ejabberd version: 22.5.3
- Erlang version: `erl +V`
- OS: Linux (Ubuntu)
- Installed from: ghcr.io/processone/ejabberd:22.05
- CPU: Intel Xeon Gold 6140 (2 cores) @ 2.294GHz
- Docker version: 20.10.16

## Errors from error.log/crash.log

No errors

## Bug description

![ejabberd](https://user-images.githubusercontent.com/15198431/170008293-811fa1d9-3416-4ebc-8982-a1230bb71638.png)
[grafana snapshot](https://grafana.07f.de/dashboard/snapshot/2FCCo1WC1zT0vhOtEgOiu7pfdVHQg5RQ)

In the graph you can see the old docker image `ejabberd/ecs:21:12` until the 21.05. Then I switched to `ghcr.io/processone/ejabberd:22.05` until 23.05 23:00. After that I used `ejabberd/ecs:22.05` image.
So it is not the new version that causes the high CPU usage but the different image.
The old image has a CPU usage of 1-5% while the new one uses 10-15% for the exactly same configuration.

**Comment by badlop** [comment]
Interesting! I try ghcr 22.05 image and doesn't show that problem, it's at 0% CPU. Of course, I have an almost empty server. The only noticeable CPU peaks for me are the healthcheck (runs `ejabberdctl status` every 5 seconds).

Can you offer any other details about the CPU usage?
- What system process exactly has that peak? Is it `beam`, the erlang virtual machine that runs ejabberd?
- Does it have some periodicity? every minute, every 10 minutes, some time pattern?
- Can you disable healthcheck in the image somehow? Maybe it malfunctions, or a check every 5 seconds is too much...
- If you try with default configuration, does it show the same problem? If not, then what of your customizations triggers that CPU usage?

**Comment by badlop** [comment]
Aha! `ejabberdctl status` starts a minimal erlang virtual machine, this is known to consume some resources. Using that command every five seconds can be noticeable in an almost idle server...

I was thinking other possible health checks:
- check if `ejabberd.pid` file exists (would require configuration in ejabberdctl.cfg)
- check if port 5222 is listening (would fail if user changes the default port)
- check if `epmd` shows the ejabberd node (would require setting link to epmd)
- check if `beam.smp` process is running

I prefer `ejabberdctl status` because it shows the version number and a human readable descriptive message.

Maybe the simplest solution is to set a less aggressive health check interval, for example:

```diff
diff --git a/.github/container/Dockerfile b/.github/container/Dockerfile
index d3537b23d..5fffdb613 100644
--- a/.github/container/Dockerfile
+++ b/.github/container/Dockerfile
@@ -101,10 +101,10 @@ RUN addgroup ejabberd -g 9000 \
     && chown -R ejabberd:ejabberd $HOME
 
 HEALTHCHECK \
-    --interval=5s \
+    --interval=1m \
     --timeout=5s \
     --start-period=5s \
-    --retries=120 \
+    --retries=10 \
     CMD /usr/local/bin/ejabberdctl status
 
 WORKDIR $HOME
```

**Comment by marzzzello** [comment]
Other suggestions:
Use an http api endpoint like /health or an ejabberdctl command health that just returns OK by using minimal resources.
Human readable doesn't seem necessary.
