### ISSUE TITLE
Messages not written to spool table when there is user session in server

### ISSUE THREAD

**Issue by logicwonder** [processone/ejabberd#3829]
## Environment

- ejabberd version: 21.12
- Erlang version: 9.2
- OS: Linux (Debian)
- Installed from: source 

## Configuration (only if needed): grep -Ev '^$|^\s*#' ejabberd.yml

```
  mod_mam:
    default: always
    assume_mam_usage: false
    db_type: sql
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_push: 
    include_sender: true
  mod_push_keepalive: {}
  mod_stream_mgmt: 
    resend_on_timeout: if_offline
...
```

## Errors from error.log/crash.log
No errors

## Bug description

When the mobile app client (SMACK 4.4.5) goes offline, the user session remains in the server for 5 mins (resume_timeout). During this period, any messages sent to the user is never gets stored to spool table.

If the user session is resumed within this window of resume_timeout, all offline messages are received by the user.

Once the user presence is removed from server, the messages received thereafter starts geting saved to spool table in DB and the user gets those messages on reconnect.

I have upgraded recently from ejabberd 21.12. Previously (in eJabberd 20.04), this issue was not observed. I am stll relying on spool for offline message retrieval. I am able to consistently reproduce this issue using the following steps:

1. Turn off mobile network in device
2. Check the user presence in server is online
3. Send message1 to the user
4. Wait of the user session to become offline 
5. Check the spool table - no data
6. Send message2  - this gets inserted to spool table
7. Reconnect the app to server - Only the message2 is received. 

Can anyone help me with the message drop issue.

PS:- Earlier I had referred issue #3086 and configured eJabberd with the recommended configuration for mod_stream_mgmt and mod_mam

**Comment by licaon-kter** [comment]
Do any other clients like Conversations or Gajim have this issues? (both send and receive I mean)

**Comment by logicwonder** [comment]
We are yet to test with other clients. Will update you soon

Meanwhile we tested with our client app in iOS (XMPP Framework) and we were able to simulate the same issue. But in iOS simulating abrupt disconnection of network was difficult. If I just turn off the wifi in iPhone, somehow eJabberd gets to know that connection is closed. And the offline messages are geting inserted into spool table. 

To exactly reproduce this issue with iOS client we had to turn off the wifi access point instead. Then we observed that all messages during the resume_timeout window were lost.

**Comment by licaon-kter** [comment]
You only want offline messages stored but not MAM?

How do you setup MAM for these accounts? `assume_mam_usage: false` https://docs.ejabberd.im/admin/configuration/modules/#mod-mam

**Comment by logicwonder** [comment]
I am using both offline messages and mam. But currently messages in MAM are not used for offline message delivery. Only offline message (spool) is used for that. Message records from archive are used for statistical purposes.
 
By setting assume_mam_usage to true would disable spool right? But my clients currrently does not support offline message retrieval from archive.

**Comment by weiss** [comment]
The recommended setup depends on whether you support multi-device usage.  If you do, ejabberd's default configuration is fine, and MAM support is _required_ for reliable message delivery.  If you _don't_ (i.e., there's _never_ more than a single client online for a given account), you could use the following configuration:

```yaml
modules:
  mod_stream_mgmt:
    resend_on_timeout: true
  mod_mam:
    assume_mam_usage: false
```

The `resend_on_timeout: true` setting makes sure all queued messages are stored to the spool table once a pending stream management session times out.  This guarantees reliable message delivery (but might yield duplicates in corner cases, so you need to deduplicate those on the receiving client).  You may still need MAM support for groupchat messages though, at least if you don't use the custom [MUC/Sub][1] extension.

[1]: https://docs.ejabberd.im/developer/xmpp-clients-bots/extensions/muc-sub/

**Comment by logicwonder** [comment]
@weiss We do not support multi device usage. I have modified the configuration according to your suggestion.

I also found that the message loss is only there when our client app runs on certain mobile devices. For example in iOS, stock android, there is no issue. But in Android device with custom ROM, the disconnection seems to result in a dirty connection at server side. And this seems to be the reason for message loss (messges are not getting written to spool). Does my observation make any sense?

Also before the upgrade to 21.12, this issue was never observed. Now I am able to consistently finding this issue in certain Android devices. I need to study more to get some clarity. Any suggestions from your end would be helpful.

Thanks @weiss @licaon-kter

**Comment by weiss** [comment]
> in Android device with custom ROM, the disconnection seems to result in a dirty connection at server side. And this seems to be the reason for message loss (messges are not getting written to spool). Does my observation make any sense?

With my settings above, I would not expect any message loss for 1:1 chats.  If you keep observing issues, I'd suggest watching closely what happens with `ejabberdctl set-loglevel debug`.

One detail: You want to make sure to keep the resource string stable when binding a new session, to make sure the new session doesn't appear like a new device to the server.

**Comment by weiss** [comment]
> I would not expect any message loss for 1:1 chats.

Assuming you have a correct [stream management][1] implementation.

[1]: https://xmpp.org/extensions/xep-0198.html

**Comment by badlop** [comment]
Another investigation path you can follow: install ejabberd 20.04 in a testing machine, confirm it works correctly with your client... and then use "git bisect" (or manual "git checkout ...") to test versions between good 20.04 and problematic 21.12.

**Comment by logicwonder** [comment]
I have setup a separate testing instance of eJabberd 21.12 and was able to reproduce the issue. Then I upgraded the testing eJabberd instance to 22.05 and I am no longer able to reproduce the issue in it.

**Comment by logicwonder** [comment]
Does this from change log had anything to do with the fix?

"C2S: Don't expect that socket will be available in `c2s_terminated` hook"

**Comment by prefiks** [comment]
It possibly could be fix for that problem (but i never was able to reproduce it with just mod_stream_mgmt, but possibly interactions with some other consumer of c2s_terminated hook did lead to this).

**Comment by logicwonder** [comment]
It is a hard to reproduce issue in an perfect environment. The trick is to create a dirty disconnection (possible in some 3G/4G networks). Or use tethered Wifi from a mobile device (host) and disconnect 4G/3G from the tethering host to create this dirty disconnect.

Something is expected from client end to server in the event of c2s termination event. If that fails to happen, messages are lost. My knowledge is limited to understand the reason behind this behaviour. Anyways thanks @prefiks for confirming a possible cause.

Will update more on this issue after detailed testing in the new test environment.

**Comment by JohnYepthomi** [comment]
This happens when a client suddenly disconnects.
Assume Client A and Client B are in a 1:1 conversation. Let's say Client A's network suddenly goes offline, due to the timeout, Client A will still appear as online to the server until the timer runs out. During this phase, any messages sent by Client B will be lost, meaning it's not stored in mod_offline which can be referred to as dead messages. So, if Client A comes back online , it won't receive any messages that were sent to it when it disconnected.  

Observations:
1. Disabling stream management works as expected. Where if a client disconnects, the server doesn't wait for any timeout and notices a client going offline and any messages sent is stored in the offline storage. This is the ideal behaviour we all expect. I do understand the benefit of stream management but it brings up this inevitable issue of dead messages as stated above. 
2. With session management `enabled` and `resend_on_timeout` set to `true` it does prevent dead messages but order of the message flow is disrupted. And the resend_on_timeout sends messages that were acknowledged too and that too it keeps resending those same messages again and again everytime the resend timeout expires even though I've already received it. I thought this will solve the problem but the ordering issue (because the sender keeps sending messages and the ordering on his side is a challenge even though we can resolve the ordering for the offline client) and multiple duplicates (not just two but more than there's duplicates of each messages ) on timeout and resending messages that were acknowledged too. 
3. The only way I can see a proper way of ensuring the ordering on both ends in cases stated above is to use MAM but I'm not sure how scalable that is and also not sure how to use it to solve the ordering and reliability of the messages. I know how to query the MAM but what if I want to delete messages from the MAM if both parties received those messages and not wait or rely for MAM module to remove old messages when it hits Max allotment. I want to use MA solely as an alternate way to retrieve messages for reliable ordering and remove those messages on e both parties have those messages. 

The third approch seems to be the most viable way to go about it where you can have stream management and also reliable message delivery with proper ordering on both parties. But I don't know how to implement it at the moment and I would appreciate if someone can point me to a clear explanation of how to use MAM for the purpose as stated on point number 3 above.

**Comment by weiss** [comment]
> Disabling stream management works as expected. Where if a client disconnects, the server doesn't wait for any timeout and notices a client going offline and any messages sent is stored in the offline storage. This is the ideal behaviour we all expect.

I don't think so.  If the TCP connection is lost without it being closed properly, as happens all day long with mobile connections, it may take a long time until the operating system's TCP stack times the connection out.  During this window, ejabberd will happily continue sending stanzas.  If neither stream management nor MAM are used, these stanzas are _silently lost_.  This was a [major PITA in the past](https://www.ejabberd.im/faq/tcp/), and is the main reason the community came up with solutions such as stream management and MAM when mobile became a thing.

> With `session management` `enabled` and `resend_on_timeout` set to `true` it does prevent dead messages but order of the message flow is disrupted.

With a multi-device setup, this can happen, yes.  I strongly recommended against this configuration except for environments that don't support multiple online devices.  I don't see how you'd run into ordering issues with a single client, though.

> And the `resend_on_timeout` sends messages that were acknowledged too

Only if the acknowledgement never reached the server.  Which can happen if the connection was lost.  Due to this issue, there's no way to guarantee message delivery and avoid duplicates at the same time, if you don't use MAM.

As you said, the proper solution is using MAM.  If all your clients support that, you can omit `mod_offline` altogether in order to avoid duplicates.

> what if I want to delete messages from the MAM

That would require a custom extension on your side.  ejabberd doesn't provide that functionality, similarly to how IMAP servers typically don't implement auto-removal of email once a recipient received it.

**Comment by JohnYepthomi** [comment]
I see. Thanks for taking the time to respond really appreciate it.

**Comment by peterchaula** [comment]
> I have setup a separate testing instance of eJabberd 21.12 and was able to reproduce the issue. Then I upgraded the testing eJabberd instance to 22.05 and I am no longer able to reproduce the issue in it.

I was having the same issue as @logicwonder on v21.12 of ejabberd. I haven't had the issue on v22.05 after upgrading. The messages are getting spooled as they should when the session times out.

**Comment by logicwonder** [comment]
Thanks @peterchaula for confirming the issue. I have upgraded to 22.05 and the issue does not exist. However, I had switched from spool to MAM for offline message delivery thereafter.
