### ISSUE TITLE
ejabberd ACME unexpected content type when it receives certificate

### ISSUE THREAD

**Issue by lukewarms** [processone/ejabberd#3938]
### Discussed in https://github.com/processone/ejabberd/discussions/3937

<div type='discussions-op-text'>

<sup>Originally posted by **lukewarms** November  8, 2022</sup>
Hi,
Thought i would get some opinion if this may be a bug.
I am running a processone/ejabberd container that i am trying to get to request a certificate via ACME to a smallstep ca container. The request fails with this error:

```

           #{<<"kid">> =>
                                <<"https://ca.mydomain.local:8000/acme/acme/account/svUkT7QwXD4pBqyrVdys94VMeVCeeo0D">>,
                            <<"nonce">> =>
                                <<"..">>,
                            <<"url">> =>
                                <<"https://ca.mydomain.local:8000/acme/acme/certificate/Jks2zJjdJwqDzE7VSsLM0TOaAzzYUB2P">>}}
2022-11-07 08:30:28.355858+00:00 [debug] HTTP request: {post,{"https://ca.mydomain.local:8000/acme/acme/certificate/Jks2zJjdJwqDzE7VSsLM0TOaAzzYUB2P",
                     [],"application/jose+json",
                     <<"{\"signature\":\"....\",\"protected\":\"......\",\"payload\":\"\"}">>}}
2022-11-07 08:30:28.608072+00:00 [debug] HTTP response: {{"HTTP/1.1",200,"OK"},
                [{"cache-control","no-store"},
                 {"date","Mon, 07 Nov 2022 08:30:28 GMT"},
                 {"content-length","2108"},
                 {"content-type",
                  "application/pem-certificate-chain; charset=utf-8"},
                 {"link",
                  "<https://ca.mydomain.local:8000/acme/acme/directory>;rel=\"index\""},
                 {"replay-nonce",
                  ".."}],
                <<"-----BEGIN CERTIFICATE-----........\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----........\n-----END CERTIFICATE-----\n">>}
2022-11-07 08:30:28.609162+00:00 [error] Failed to request certificate for jabber-gw.mydomain.me: HTTP error: unexpected content type: application/pem-certificate-chain; charset=utf-8
2022-11-07 08:30:28.609456+00:00 [debug] Unregistering ACME challenge #Ref<0.1802325958.1657798659.124306>
2022-11-07 08:35:26.914567+00:00 [debug] Error when retrieving http headers gen_tcp: timeout 
```

It's seems as if ejabberd wasn't expecting the cert?!?

Prior to the error, logs show the ACME challenge looking healthy where the content type is application/json:

                          ```
   <<"https://ca.mydomain.local:8000/acme/acme/order/IKXRHjiqqRhSjlvSUExtaZjI89swHOYV">>}}
2022-11-07 08:30:27.007780+00:00 [debug] HTTP request: {post,{"https://ca.mydomain.local:8000/acme/acme/order/IKXRHjiqqRhSjlvSUExtaZjI89swHOYV",
                     [],"application/jose+json",
                     <<"{\"signature\":\"_...\",\"payload\":\"\"}">>}}
2022-11-07 08:30:27.428351+00:00 [debug] HTTP response: {{"HTTP/1.1",200,"OK"},
                [{"cache-control","no-store"},
                 {"date","Mon, 07 Nov 2022 08:30:27 GMT"},
                 {"location",
                  "https://ca.mydomain.local:8000/acme/acme/order/IKXRHjiqqRhSjlvSUExtaZjI89swHOYV"},
                 {"content-length","424"},
                 {"content-type","application/json"},
                 {"link",
                  "<https://ca.mydomain.local:8000/acme/acme/directory>;rel=\"index\""},
                 {"replay-nonce",
                  "..."}],
```

Any thoughts?
</div>

**Comment by hslatman** [comment]
I believe it's due to these lines in the ACME client lib that's in use: https://github.com/processone/p1_acme/blob/cf35462b8df39f7b60277184f6baf13493c7772f/src/p1_acme.erl#L683-L689. I don't read Erlang often, but I think it's matching on the exact `application/pem-certificate-chain` string, whereas `step-ca` returns `application/pem-certificate-chain; charset=utf-8`, and thus results in the `unexpected_content_type` error.

The `charset` is optional in the `Content-Type` in general, so maybe it should be ignored by the client implementation. In the ACME RFC there's [an example ](https://datatracker.ietf.org/doc/html/rfc8555#section-7.4.2)that shows an `application/pem-certificate-chain` response without the charset. And in section 9.1 it describes this [specific media type to not have a `charset`](https://datatracker.ietf.org/doc/html/rfc8555#section-9.1). `step-ca` works with a lot of ACME clients already, and thus they seem to ignore the `charset`, but maybe we should remove it from our ACME responses.

**Comment by lukewarms** [comment]
Thanks @hslatman! I take it there is no work around and i'll need to wait for the next release if it is agreed to remove `charset` in the ACME response?

**Comment by hslatman** [comment]
We'll have to discuss if we're going to change this. I don't think it's going to affect existing ACME clients, so we can probably patch our implementation.

I've opened https://github.com/smallstep/certificates/issues/1171, so that it'll come up in our triage meeting.

**Comment by hslatman** [comment]
The change for this has been merged in https://github.com/smallstep/certificates/pull/1172. So `ejabberd` can now be used with `step-ca` to get a cert.

**Comment by badlop** [comment]
@lukewarms Was the problem finally get solved, or is there yet something to do in ejabberd/Erlang source code?

**Comment by lukewarms** [comment]
@badlop the changed solved the problem for me, smallstep cert requests are now successful.

**Comment by hslatman** [comment]
@badlop the ACME client in use could perhaps be made a little bit more forgiving in terms of the charset as it was returned from step-ca before our changes. We removed it, because the spec wasn't fully conclusive about it, but there may be other ACME servers that return a different value resulting in the same error. Don't know from the top of my head, though.
