### ISSUE TITLE
Service-not-available error on message with no-store element

### ISSUE THREAD

**Issue by sawantuday** [processone/ejabberd#398]
Sending message with `<no-store xmlns="url:xmpp:hints"/>` results in service-not-available error.

**Comment by weiss** [comment]
From looking at the code, I don't see how a `<no-store/>` tag could trigger an error stanza; and I can't reproduce the issue even if the receiving contact is offline.  In the latter case, you might actually _expect_ such an error message, but ejabberd [won't generate it][1].  I'll add that to my TODO list.

So, I don't think you got that error stanza *because* of the `<no-store/>` tag if the recipient is using ejabberd.  Can you reproduce the issue?  If so, could you generate a dump of the (relevant part of the) XMPP stream?  What ejabberd version is the recipient using?

[1]: https://github.com/processone/ejabberd/blob/master/src/mod_offline.erl#L320

**Comment by sawantuday** [comment]
I can reproduce the same on my local dev machine. I am using ejabberd v 14.07 built from source. 
1. exchange messages when both users are online - everything works well 
2. send message to offline user - message is stored in offline storage
3. send message with `<no-store/>` to offline user - message is not stored and error is returned 

error details 
type = cancel
code = 503
child = <service-unavailable/>


Following is the transcript 

R:<message type="chat" to="uday@localhost" id="aae9a">
    <body>asd</body>
    <active xmlns="http://jabber.org/protocol/chatstates"/>
</message>


S:<message type="chat" to="uday@localhost" id="aaeaa">
    <body>a</body>
    <active xmlns="http://jabber.org/protocol/chatstates"/>
</message>


S:<message type="chat" to="uday@localhost" id="aae9a">
    <body>asd</body>
    <no-store xmlns="urn:xmpp:hints"/>
    <active xmlns="http://jabber.org/protocol/chatstates"/>
</message>

R:<message from="uday@localhost" type="error" xml:lang="en" to="admin@localhost/Udays-iMac" id="aae9a">
    <body>asd</body>
    <no-store xmlns="urn:xmpp:hints"/>
    <active xmlns="http://jabber.org/protocol/chatstates"/>
    <error type="cancel" code="503">
        <service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
    </error>
</message>

I am using PSI as my xmpp client.

PS: I am total noob in erlang but little experimentation solved the problem. 
I changed the `ok` on the line pointed by you to `stop` and now its working as expected.

**Comment by weiss** [comment]
What you describe sounds like

1. the recipient is offline indeed (right?), as otherwise that line wouldn't be executed, and
2. you have some other module that's subscribed to the `offline_message_hook` and generates the error stanza (unless you `stop` hook execution before that other module is called).  I have no idea what module that might be.  Are you running any custom stuff?

Either way, wouldn't you expect that error stanza if the recipient is offline and `<no-store/>` is specified?

**Comment by sawantuday** [comment]
Yes, you are right. I checked with XEP and it says the server should return `<service-unavailable/>` when the user is offline and server is unable to store message for later delivery (in this case because of `<no-store>` element).

Thanks for your time and quick response.

**Comment by weiss** [comment]
Okay, thanks for the feedback.

I now understood why I wasn't able to reproduce the (correct) behavior, by the way: I copied your `<no-store/>` tag when generating a test `<message/>`, and that tag has a typo in the `xmlns` attribute ([`url` instead of `urn`][1]) :-P  Apart from that, I've overlooked that `ejabberd_sm` [subscribes][2] to the `offline_message_hook` itself to [generate that error stanza][3].

So everything is fine.

[1]: https://github.com/processone/ejabberd/issues/398#issue-53755547
[2]: https://github.com/processone/ejabberd/blob/4ef2d08456f3e5a535273152fe47b78529647981/src/ejabberd_sm.erl#L363
[3]: https://github.com/processone/ejabberd/blob/4ef2d08456f3e5a535273152fe47b78529647981/src/ejabberd_sm.erl#L156
