### ISSUE TITLE
Messages lost even after using SM

### ISSUE THREAD

**Issue by sawantuday** [processone/ejabberd#417]
Scenario: Client looses connectivity and leaves the TCP connection open till it times out.

Now messages that are sent to this client but not delivered are lost. These messages never reach to client nor get stored in offline storage for later delivery. Instead the server returns (after around 20 mins) the same message (to sender) with `type` set to `error` with code `503 - service-unavailable`. 

After expiration of session timeout, the server should store any unacknowledged messages in offline storage.

PS. I have SM enabled and it works well if client resumes within timeout.

**Comment by mremond** [comment]
Are you sure you have mod_offline enabled ?

**Comment by sawantuday** [comment]
Yes. If I properly close the connection by sending `</stream:stream>` then all messages gets stored in offline storage.

**Comment by weiss** [comment]
Please look up the `ejabberd_c2s` listener variable `resend_on_timeout` in the [guide][1], and be sure to understand the [consequences][2] before setting it to a value other than `false`.

[1]: http://www.process-one.net/docs/ejabberd/guide_en.html#listened-options
[2]: http://lists.jabber.ru/pipermail/ejabberd/2014-November/008433.html

**Comment by sawantuday** [comment]
Thanks @weiss

**Comment by amperesoft** [comment]
Hi, I am using the following:
Smack 4.1.2,
ejabberd 15.06
 
I have enabled Stream management.
On ejabberd server:
stream_management: true
resend_on_timeout: true
resume_timeout: 300
max_ack_queue: 1000
 
I have also used mod_mam in 15.06 and configured it to save message in mysql db.
mod_mam:
    iqdisc: one_queue
    db_type: odbc
    default: always

I also have mod_offline enabled.

Mostly it works fine but a few times when facing network issues on mobile, we do get an event for a message in addStanzaAcknowledgedListener : processPacket but neither the message is there in the db nor it is delivered to receiver. Are we missing something? It is really hard to reproduce.
 
This issue came on 4.1.0 of smack as well as ejabberd 14.12. With or without mod_mam.
 
Thanks!
Gaurav

**Comment by weiss** [comment]
> Are we missing something?

I commented on #648, let's not scatter the discussion across multiple issues.

**Comment by Nitin3588** [comment]
i am also having the same issue described by sawantuday mentionedabove , have you checked this scenario or do we need to resend all the messages received as error 503 with type error with code 503 - service-unavailable ?

**Comment by weiss** [comment]
> i am also having the same issue described by sawantuday

Then my [response][1] applies to your case as well.

[1]: https://github.com/processone/ejabberd/issues/417#issuecomment-71640745
