### ISSUE TITLE
swap_handler fails

### ISSUE THREAD

**Issue by list-processing** [processone/ejabberd#4233]
## Environment

- ejabberd version: master
- Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 14.2.5
- OS: Mac
- Installed from: source

## Bug description

https://github.com/processone/ejabberd/blob/master/src/ejabberd_system_monitor.erl#L62

this line just successfully deletes the {alarm_handler, swap} , but fails to adds {?MODULE, []} .

```
{error,
             {'EXIT',
                 {function_clause,
                     [{ejabberd_system_monitor,init,
                          [{[],{alarm_handler,[]}}],
                          [{file,"src/ejabberd_system_monitor.erl"},
                           {line,86}]},
                      {gen_event,server_add_handler,4,
                          [{file,"gen_event.erl"},{line,710}]},
                      {gen_event,server_swap_handler,6,
                          [{file,"gen_event.erl"},{line,754}]},
                      {gen_event,handle_msg,6,
                          [{file,"gen_event.erl"},{line,565}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,241}]}]}}}
```

why not use gen_event:delete_handler/3?

**Comment by badlop** [comment]
I've added handling of swap_handler call; this fixes the error message that was thrown in that case.

I don't know the exact reason why add_handler is called just to later call swap_handler, but it is surely a good reason because it was explicitly added in commit https://github.com/processone/ejabberd/commit/a0607f67403af763b4ebdf015769b9811cfb281c
