### ISSUE TITLE
how to send presence from ejabberd component.

### ISSUE THREAD

**Issue by hackrole** [processone/ejabberd#432]
I write a ejabberd component which wait for http request and then send a presence stanza fro users.
so the client can use a single-http-request to add friends or login in my app.
for example:
```xml
<presence from="13222222222@etest.pengqiao.me" />
<presence to="18502131478@etest.pengqiao.me" type="subscribe" from="13222222222@etest.pengqiao.me" />
```
but I got this errors in the logging file
```
<presence to="13222222222@etest.pengqiao.me" type="error"><error code="400" type="modify"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error></presence>
```
and the subscribe-presence stanza not send to the client.

I search the web, it seems like the openfire works well, but the ejbbaerd not allow component to send presence stanza.

but I really need this feature, does there any config can help me?

**Comment by mremond** [comment]
Are you talking about an external component as per XEP-0114 ?
http://xmpp.org/extensions/xep-0114.html

Component do not have the right to send arbitrary packets on behalf of the server. So what you are trying to achieve does not look conform to XMPP.

**Comment by hackrole** [comment]
yes, I mean the xep-0144 component.
I can send message and iq stanza. but not presence stanza.
what I need is to provide a http interface to make subscribe/unsubscribe others for the client and store something in my database.
I will move this to the discuss-forum

**Comment by alexpetroaica** [comment]
Hello, have you found a solution to this? I am trying to enable my component to update a user's presence but the presence packages that the component sends are not broadcast to the contacts in my user's roster...

**Comment by mremond** [comment]
There is no solution for this with XEP-0114. As per specification in that XEP, a component cannot act on a behalf of a user. It can only provide services to that user.

**Comment by alexpetroaica** [comment]
Thanks for your reply, Mickaël! I have disabled the "check_from" flag in Ejabberd which should allow the component to send packets on behalf of a user.

I can confirm this works because the component does deliver the presence packet on behalf of the user if I specify a "to" address.

However, if no "to" field is specified when sending the presence packet, a 400 error is returned.

My intention is to provide a REST API which allows callers to set the "status" and "show" presence fields for any user. Of course the API will only be secured and only called by trusted services, so I need a way to send presence packets on behalf of any user.

Does any other solution come to mind that could help me accomplish this?

Many thanks!
