### ISSUE TITLE
mod_irc crashes when channel starts with '#'

### ISSUE THREAD

**Issue by ehuelsmann** [processone/ejabberd#453]
Hi,

As per mikl's request, filing a ticket.

When I try to connect to "#rex%irc.freenode.net", mod_irc crashes and I find this in the logs:

the error is: 2015-03-03 14:15:02.181 [error] <0.7126.0> gen_fsm <0.7126.0> in state wait_for_registration terminated with reason: bad record state in mod_irc_connection:term
inate/3 line 700
2015-03-03 14:15:02.182 [error] <0.7126.0> CRASH REPORT Process <0.7126.0> with
0 neighbours exited with reason: bad record state in mod_irc_connection:terminat
e/3 line 700 in gen_fsm:terminate/7 line 589

After that, the mod_irc service doesn't respond anymore. After restarting the server, connecting to "rex%irc.freenode.net" works without problems.

mod_irc configuration:
[{default_encoding, "utf-8"},
 {access, all},
 {host, "irc.j.@HOST@"}]

**Comment by mremond** [comment]
As discussed on chat, we cannot just strip the leading '#' as channel can start with '##'

Moreover, there is a crash on bad record. I think I found why the crash happens and will commit a fix in a moment.

**Comment by badlop** [comment]
mod_irc is not maintaned anymore. The code was moved to ejabberd-contrib in June (3a5d2dbed8f089b112eba7998e2ad0d2508f01cb), so that it doesn't get lost. If this problem is still present and somebody wants to fix it, a new ticket in [ejabberd-contrib](https://github.com/processone/ejabberd-contrib) can be created, referencing this old one.
