### ISSUE TITLE
mod_irc improperly handles nick conflicts during connection setup

### ISSUE THREAD

**Issue by ehuelsmann** [processone/ejabberd#455]
When connecting to freenode with the nick "erik", the server responds with:

":wilhelm.freenode.net 433 \* erik :Nickname is already in use."

When that happens, mod_irc crashes with this line in the logs:

2015-03-04 12:19:59.292 [error] <0.491.0> CRASH REPORT Process <0.491.0> with 0
neighbours exited with reason: bad record state in mod_irc_connection:terminate/
3 line 700 in gen_fsm:terminate/7 line 589

Where I think the problem is in https://github.com/processone/ejabberd/blob/14.12/src/mod_irc_connection.erl#L700 which tries to write to a socket already closed: since mod_irc doesn't quickly enough choose another nick, the server hangs up on the connection which is the entire reason for the terminate/3 to be triggered.

**Comment by badlop** [comment]
mod_irc is not maintaned anymore. The code was moved to ejabberd-contrib in June (3a5d2dbed8f089b112eba7998e2ad0d2508f01cb), so that it doesn't get lost. If this problem is still present and somebody wants to fix it, a new ticket in [ejabberd-contrib](https://github.com/processone/ejabberd-contrib) can be created, referencing this old one.
