### ISSUE TITLE
mod_irc doesn't get restarted after a crash

### ISSUE THREAD

**Issue by ehuelsmann** [processone/ejabberd#456]
After a single failure (crash), the service becomes completely unavailable. Holger says the service isn't configured to be restarted. Maybe it's an idea to restart the service after a delay?

**Comment by mremond** [comment]
The IRC components should be put in proper Erlang supervision tree. I am proposing this tasks as teaser tasks for Google Summer of code.

**Comment by mremond** [comment]
There is a tentative patch attached on Pull Request #475

**Comment by badlop** [comment]
mod_irc is not maintaned anymore. The code was moved to ejabberd-contrib in June (3a5d2dbed8f089b112eba7998e2ad0d2508f01cb), so that it doesn't get lost. If this problem is still present and somebody wants to fix it, a new ticket in [ejabberd-contrib](https://github.com/processone/ejabberd-contrib) can be created, referencing this old one.
