### ISSUE TITLE
Better error message for Yaml indentation issue

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#472]
At the moment, when Yaml config file syntax is incorrect, we can sometime refuse to start with cryptic error:

```
2015-03-12 15:48:04.204 [error] <0.36.0> CRASH REPORT Process <0.36.0> with 0 neighbours exited with reason: {undefined_macro,''} in application_master:init/4 line 133
```

Let's provide a more helpful message.

**Comment by tnull** [comment]
Hello! 
As I'm interested in doing the GSoC project concerning the configuration DSL, I want to have a look at this to get a first impression of ejabberd configuration code.

However I so far could not reproduce the cryptic error you described. I located the corresponding code in `replace` / `replace_term` in the `ejabberd_config` module, but I fail to find an example of incorrect syntax ejabberd.yml where this cryptic message occurs. 
Normally ejabberd refuses to start with something along the lines of:

```
[error] Cannot load /tmp/ejabberd/etc/ejabberd/ejabberd.yml: Syntax error on line 466 at position 1: did not find expected key
```

Can you provide an example configuration for which this error occurs?

**Comment by mremond** [comment]
Such example: add a space then a on line 1:

```
16:28:38.872 [error] Cannot load /Users/mremond/devel/p1/ejabberd/ejabberd/ejabberd.yml: Syntax error on line 40 at position 1: did not find expected <document start>

Crash dump is being written to: erl_crash.dump...done
```

**Comment by tnull** [comment]
Ah, sorry. Misunderstood the issue to be for this specific case ("{undefined_macro,''}").
So the goal would be to improve on the provided error messages while parsing the config file in general.

**Comment by tnull** [comment]
I had a deeper look into this and I'm still kind of confused about the scope of this issue. Just improving on some of the error messages (and handling cases like the `undefined_macro`) is trivial, e.g. like https://github.com/tnull/ejabberd/commit/b0c3efc70d2d64aa2f4ca41cdf78e118cf1d311. If this issue is indeed about this I'll gladly put some more work in prettifying the Error outputs and hand in a pull request for this. 

However, am I wrong to think, that to handle indentation issues in the config file more generally and to explain to the user what kind of syntax errors there are in her config file, changes would need to be made 'upstream' aka to fast_yaml or even libyaml to deliver more descriptive `Err` tuples?

**Comment by cromain** [comment]
better error report around yaml configuration has been added in 17.x
