### ISSUE TITLE
Rewrite XML RPC integration documentation

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd#520]
With new unified API for commands, the documentation on this page need to be update:
https://www.ejabberd.im/ejabberd+integration+with+XMLRPC+API

**Comment by badlop** [comment]
Having a static list of commands was useful in the primitive ejabberd 1 because there wasn't commands, so there wasn't live documentation of xmlrpc calls and their arguments. Nowadays a static list is not necessary.

We keep a static list in the documentation, but only for the core commands. I've improved your disclaimer in the old xmlrpc page.
