### ISSUE TITLE
mod_muc: Kicking/banning self should cause <conflict/>

### ISSUE THREAD

**Issue by cburschka** [processone/ejabberd#574]
http://xmpp.org/extensions/xep-0045.html#example-93

> If a moderator attempts to kick himself, the service MAY deny the request and return a `<conflict/>` error to the sender.

http://xmpp.org/extensions/xep-0045.html#example-115

> If an admin or owner attempts to ban himself, the service MUST deny the request and return a `<conflict/>` error to the sender.

Instead, both of these cases cause a `<not-allowed/>` error to be sent.

**Comment by badlop** [comment]
As you noticed, when there is an error attempting to change room roles and affiliations, ejabberd returns 'not-allowed' for all cases. This makes the code as simple as possible.

The XEP has a few special cases that require to return 'conflict' error, but ejabberd does not differentiate those error cases from the general ones.

I agree that in those cases ejabberd isn't strictly XEP-compliant, and should be improved to detect them and report the correct error type. But I'd prefer to keep it as it is now, for code simplicity and because it already returns an error, even if not the exact error type defined by the XEP.

**Comment by axcl** [comment]
I think sell affiliation should also be denied, also author of room can not be demoted to any lower rank that means affiliation of author / creator of room should not be changed.
