### ISSUE TITLE
Messages sent to unconnected full jid are delivered to all that matches bare jid

### ISSUE THREAD

**Issue by RobertLarsen** [processone/ejabberd#594]
If I have two connections with jids robert@komogvind.dk/blim and robert@komogvind.dk/blam, then a message to robert@komogvind.dk/dont_exist is delivered to both of them unless I also have a third connection with full jid robert@komogvind.dk/dont_exist.

The way I read rfc 3920 section 10.5 the delivery should fail.

**Comment by mremond** [comment]
Yes, we know but we have been discussing with @weiss this part of the spec and we are not sure it is relevant.
It seems that for client developer it is very surprising and unexpected to have that delivery fail.

After a conversion has been started, you are supposed to send message to full jid.
When that session gets offline, it message the next messages send will be lost even if there is other session online.
Why is this simply needed ?
It seems to put a big burden on client developer to resend, etc.

**Comment by RobertLarsen** [comment]
We develop web based games and use the XMPP server for routing both chat and game events. You typically have multiple connections (one per browser window) and some games send lots of updates. When you close a window these updates are (with ejabberd) sent to all the remaining connections so we will now have to filter away the crud...which the server should not have sent in the first place accodring to the spec.

**Comment by mremond** [comment]
Yes, build filtering when needed seems to be a better behaviour than losing messages, no ?

**Comment by rraptorr** [comment]
Anyway, RFC3920 is obsolete. Current XMPP RFC describes it in a way ejabberd implements it, at least for 'chat' messages: https://tools.ietf.org/html/rfc6121#section-8.5.3.2

**Comment by mremond** [comment]
FYI, as we discuss the behaviour, here is the patch making the change:
https://github.com/processone/ejabberd/commit/3b267eaa61c3659e51be69aac47ef2efbf1f8958

It may help if you want to enable that behaviour.

**Comment by RobertLarsen** [comment]
I'd personally rather code up my client to be able to show "Bob is no longer here" than having messages routed somewhere where they aren't handled. And I'd expect both client and server to follow the spec even when the spec is an idiot :-)

**Comment by mremond** [comment]
@rraptorr Yes, but with the patch I refer we are not bouncing normal message either.
We made that exception to RFC because:
- "normal" is the default type when nothing is specified.
- As it is default type, most client developers use it for chat.
- Developers do not understand why they thus lose chat message and end up saying XMPP is "crap".

So my comment on the spec is specifically relating to "normal" type message. I think the same behaviour should be applied to both "normal" and "chat" messages.

@RobertLarsen Well, my personal goal is to make XMPP more developer friendly. Discussing specification is good as that's what help make progress.
Anyway, if you send messages that are game events, it seems the type on your message should be "headline", no ?

That way that message:
- Is not stored for offline delivery so does not add cruft to client that reconnect later.
- Is bounced so that the behaviour is the one you want.

This will have the added benefit to properly allow you to sort out chat and game event messages.

**Comment by RobertLarsen** [comment]
You know stuff that I don't. Thanks for pointing that out. I'll shut up now. :-)

**Comment by mremond** [comment]
@RobertLarsen No, not at all, please. We need your feedback :)

I am trying to please as much people as possible, but we can only find the best approach by discussing. Maybe I am wrong and we should apply the spec. I am never sure :)

So it is good to first help you learn new features, and then try to find a good middleground in default behaviour. I think in your case headline type (even if the name is confusing) will be helpful :)

**Comment by RobertLarsen** [comment]
I've implemented 'if stanza == message && type == undefined then type = headline' in our servers. Hopefully this will do the trick.
