### ISSUE TITLE
ejabberd must be run under what user?

### ISSUE THREAD

**Issue by reztarter** [processone/ejabberd#629]
ejabberd-15.06 installed from deb-package, so why after running
myhost# ejabberdctl start
empd and beam.smp are running under user root? it's normal?

myhost# ps aux | grep jabberd
root     23394  0.0  0.0  10840   332 ?        S    Jun26   0:01 /opt/ejabberd-15.06/bin/epmd -daemon
root     23948 48.3  0.3 360744 49968 ?        Sl   09:06   0:01 /opt/ejabberd-15.06/bin/beam.smp -K true -P 250000 -- -root /opt/ejabberd-15.06 -progname /opt/ejabberd-15.06/bin/erl 
-- -home /root -- -sname ejabberd@localhost -noshell -noinput -noshell -noinput -pa /opt/ejabberd-15.06/lib/ejabberd-15.06/ebin -mnesia dir "/opt/ejabberd-15.06/database/ejabberd@localhost" 
-kernel inet_dist_use_interface {127,0,0,1} -ejabberd log_rate_limit 100 log_rotate_size 10485760 log_rotate_count 1 log_rotate_date "" -s ejabberd -sasl sasl_error_logger 
{file,"/opt/ejabberd-15.06/logs/erlang.log"} -smp auto start

**Comment by cromain** [comment]
rpm and deb packages are new, and generated from our binary installer. while our binary installer is not supposed to be run by root, rpm and deb are installed by root, so INSTALLUSER is set to root in ejabberdctl. that's why epmd and beams are running as root.
we have to improve this.
for both rpm and deb, we need an extra postinstall stage that would create an ejabberd user, and give it rights to database conf and logs directories, so ejabberd could be run by ejabberd used.

until packages are improved, you can still create an ejabberd user and chown -R ejabberd /opt/ejabberd-15.06/{database,conf,logs}
then edit bin/ejabberdctl and change INSTALLUSER=ejabberd

this should be enough to get ejabberd running as ejabberd user.

**Comment by reztarter** [comment]
thx! and user ejabberd must be created with home directory /opt/ejabberd-15.06/ and without shell (/bin/false) ?
# useradd -d  /opt/ejabberd-15.06 ejabberd

**Comment by cromain** [comment]
i don't think so. it would be best to let ejabberd home be /var/lib/ejabberd so we store database conf and logs here instead, and let /opt/ejabberd only contain application.

**Comment by cromain** [comment]
as packages are generic, it's finally not good idea to let home be /var/lib/ejabberd
so here is summary of next steps for deb and rpm package, to be run as post_install
- create ejabberd user if it does not exists
- change ejabberd home to /opt/ejabberd-XX.YY
- chown -R ejabberd /opt/ejabberd-XX.YY/{database,conf,logs}
- set INSTALLUSER=ejabberd in ejabberdctl

**Comment by cromain** [comment]
this procedure is now done at postinstall
checked on CentOS now ejabberd run with created ejabberd user
