### ISSUE TITLE
muc_filter_message causes room to stop working

### ISSUE THREAD

**Issue by nunohorta** [processone/ejabberd#728]
I'm using this module https://github.com/nunohorta/ejabberd_mod/blob/master/mod_muc_chat.erl to post all group messages to a script. What's happening is every time I send a message to a chat room is causes a crash and that room stops executing. Here's the log after sending a message:

https://gist.github.com/nunohorta/5361eea7d43eedae3e8b

For now I've disabled the module. I also tried to remove everything inside the method that sends the post, and it still crashes. So I believe it's related with the new muc_filter_message

**Comment by badlop** [comment]
I think the problem is in that module that you installed: it doesn't use correctly the muc_filter_message hook. The function should return a packet, instead it returns 'ok'.

And that 'ok' gets stored by mod_mam, and then crashes. Remove the contents of the archive_msg  Mnesia table (use WebAdmin -> Nodes -> your node -> Database), and fix the module if you want to use it again.

**Comment by nunohorta** [comment]
you're right, I totally missed that detail. It's working now..thanks!

**Comment by omerholz** [comment]
I'm having issues with adding the muc_filter_mssage hook. I'd love to see the code in mod_muc_chat.erl blo, but it is no longer available. @nunohorta would you be willing to repost it?

**Comment by nunohorta** [comment]
hey @omerholz please have a look at the module that I'm using. https://github.com/nunohorta/ejabberd_mod/blob/master/mod_post_muc.erl
