### ISSUE TITLE
why not use https://github.com/chadillac/ejabberd-easy_cluster to realize multy master

### ISSUE THREAD

**Issue by zhuoyikang** [processone/ejabberd#734]
what  easy_cluster do is  just copy 的master's mnesia table to other node . when maste crash ,there are still some node to hold all the mnesia table to make the ejabberd cluster continue work.

why not accept this easy cluster to processone/ejabberd. ?

**Comment by mremond** [comment]
Currently since ejabberd 15.03, you just need to do ejabberdctl join_cluster to add a node to the cluster.
We already integrated our simple way to create ejabberd cluster, so we do not need anything else.

This is already show in ejabberd documentation: http://docs.ejabberd.im/admin/guide/clustering/#clustering-setup

Can't be simpler ;)
