### ISSUE TITLE
Problem with define_macros

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#758]
After update to ejabberd 15.09 I have problem with start the server. In error.log I see some problem with macro that I have defined in separate config file (by using include_config_file). I moved macros to main config file and problem disapper but macros still don't work in others separate config files where I use macros from main config file. I think problem lies in this commit https://github.com/processone/ejabberd/commit/5593ebbbca5bd64ae564fd97e58ed826b2a22e7a My config files is like https://github.com/jabber-at/config/

**Comment by beherit** [comment]
I build ejabberd without commit https://github.com/processone/ejabberd/commit/5593ebbbca5bd64ae564fd97e58ed826b2a22e7a and everything is okay.

**Comment by prefiks** [comment]
Hello, this problem is known, in this version i added ability to override main config with values from configs loaded from include_config_file or extmod config, unfortunately this required change to how macros are handled. I will try to restore some intra file macros resolving (macros from main file would in included files, but not the other way), but i don't have code for this yet

**Comment by mathiasertl** [comment]
This **seriously** breaks our configuration as well. We use macros defined in the main configuration file in included files, and macros from included files in the main file and in other included files. 

We use the latter because we have our configuration [on github](https://github.com/jabber-at/config)  (so other admins can reference it - which quite a few do) and of course do not want to have any e.g. database secrets there. So they are included in a file named in `.gitignore`.

So we too need a fix on this. 

PS: I realize sometimes there are known issues with releases or even the config file format has to be changed, but I would definitely have appreciated a "known issues" chapter in the release announcement.

**Comment by prefiks** [comment]
This should be fixed by commit 67d3b50598897bcdf7982580baa99dab968e20bb.

**Comment by beherit** [comment]
Seems that everything is working :) Thanks!

**Comment by mathiasertl** [comment]
Just to be clear: it is no longer possible (even with 67d3b50) to have define_macro in an included file and use those macros in the main file and/or another included file?

If this is no longer possible, we can no longer share our config on github :-(

**Comment by prefiks** [comment]
It should work with latest version from git

**Comment by mathiasertl** [comment]
I just tested this with a test configuration and it seems it works - thank you!
