### ISSUE TITLE
Use homogeneous s2s connections stats

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#761]
In webadmin I have:

http://i.imgur.com/cwigJOr.png

And in SHH:
```
xxx@yyy:~# ejabberdctl outgoing_s2s_number
34
xxx@yyy:~# ejabberdctl incoming_s2s_number
32
```

Which data is correct?

**Comment by badlop** [comment]
Both are correct, notice they measure different connections. Usually for each incoming s2s connection there is an outgoing one, but that doesn't happen when there are connectivity problems, when the remote server doesn't exist, or when traffic is only sent in one direction.

For example, in my test server (not connected to internet), I login a client and try to discover jabber.org. Then I'll have an outgoing connection, but not incoming:


```
11:27:02.284 [info] New s2s connection started <0.491.0>
11:27:02.284 [info] Trying to open s2s connection: localhost -> jabberes.org with TLS=true

$ ejabberdctl outgoing_s2s_number
1
$ ejabberdctl incoming_s2s_number
0
```

Sometime later, when my ejabberd closes that outgoing connection due to timeout, both numbers are the same:

```
11:30:02.893 [info] wait_for_validation: localhost -> jabberes.org (connect timeout)

$ ejabberdctl outgoing_s2s_number
0
$ ejabberdctl incoming_s2s_number
0
```

**Comment by beherit** [comment]
So what exactly different are incoming_s2s_number/outgoing_s2s_number from informations in webadmin and values from commands in mod_statsdx getstatsdx s2sconnections/s2sservers?

**Comment by badlop** [comment]
They are gotten from the number of s2s processes. On the other hand, webadmin (and statsdx which use the same code) get the values from the mnesia table.

**Comment by mremond** [comment]
@badlop Shouldn't we be more homogeneous and make sure the value is taken from the same place from command-line and web interface ?
