### ISSUE TITLE
Online status

### ISSUE THREAD

**Issue by hassanzreik** [processone/ejabberd#802]
Hello,

Is there a way to get online or last seen time for the users?

Thanks,

**Comment by bangarharshit** [comment]
You can use ejabberdctl connected_users to see if the users are online - http://docs.ejabberd.im/admin/guide/managing/#ejabberdctl-commands. Remeber that it may not be in sync with client since ejabberd waits for some time before dropping connection. You can use LastActivity (table last in mysql) to find the last connection time. I have written a very simple admin console over xml rpc to consistently monitor it. It's a good idea to monitor it on client side also.

**Comment by badlop** [comment]
Right, some examples:
```
$ ejabberdctl connected_users
user2@localhost/tka1

$ ejabberdctl connected_users_info
user2@localhost/tka1    c2s     127.0.0.1       35904   8       ejabberd@localhost      10

$ ejabberdctl get_last user1 localhost
2015-11-02 12:26:25 
```
