### ISSUE TITLE
question about mod_multicast

### ISSUE THREAD

**Issue by Tracywang890810** [processone/ejabberd#913]
Hi, I am using the mod_multicast(XEP-0033) of ejabberd, but I got this error 
```
>@mod_multicast:handle_info:176 Error when processing IQ stanza:
 {{case_clause,<<"jabber:iq:roster">>},
[{mod_multicast,process_iqreply_result,4,[{file,"src/mod_multicast.erl"},{line,738}]},
 {mod_multicast,handle_info,2,[{file,"src/mod_multicast.erl"},{line,174}]},
 {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},
 {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
```
who can tell me why?

**Comment by badlop** [comment]
What ejabberd version? What stanza do you send to provoke that error? What Jabber client are you using? Does the client support XEP-0033, or are you sending the queries manually?

**Comment by mremond** [comment]
I think the issue is that the client is broken and send reply with bad namespace. I think we should prevent the crash and log warning.

Maybe we should send a stream error back to client as well ?

However, the client will need to be fixed anyway.

For the record, the issue was crossposted on Stackoverflow: http://stackoverflow.com/questions/34869457/ejabberd-mod-multicast-error/34907425#34907425

**Comment by mremond** [comment]
@badlop Any update ?

**Comment by badlop** [comment]
In its Staroverflow page, he says this is the config he uses:
```
mod_multicast:
 host: "tracywang.com"
 access: multicast
 limits: "> [ {local,message,infinite}, {local,presence,infinite}, {remote,message,infinite} ]."
```
That is obviously wrong, as host should be "multicast.server", not simply "server".
