### ISSUE TITLE
Issue with PubSub whitelist

### ISSUE THREAD

**Issue by mithunraman** [processone/ejabberd#947]
Scenario:
1. Created a pubsub with accessmodel whitelist.
2. Successfully added a user 'u1' as with a affiliation member.
3. Changed the affiliation of u1 to none. After affiliation update, u1 continues to receive updates from pubsub.
4. Tried changing the affiliation to outcast. u1 still continues to receive published items from pubsub.

I have verified the changes in DB and i can see the affiliation getting updated to n(none) & c(outcast). Are there any other additional configuration that needs to be set to remove an member from the whitelist ?

Thanks,
Mithun

**Comment by cromain** [comment]
receiving updates from the node is due to subscriptions. in your example user u1 should have been subscribed somehow.
if not, please give more details:
- how do set u1 affiliation, then unset affiliation
- list all affiliations and subscriptions of that node
- paste packet u1 receives (what you call "updates from pubsub")

**Comment by mithunraman** [comment]
Hi @cromain ,

Sorry for the delay in response. I have been very busy lately but i will post all the necessary details within a week.

Thanks,
Mithun
