### ISSUE TITLE
ejabberdctl reload doesn't pick up redis_server change

### ISSUE THREAD

**Issue by stevenlivz** [processone/ejabberd#950]
`ejabberdctl restart` works but if i make a change to the redis_server (new Master host for example) in the ejabberd.yml and reload the change doesn't get picked up ... if i restart the process it does. I'm guessing the reload should pick this up.

**Comment by badlop** [comment]
Your explanation is a little confusing. Is this what you want to say?

1. First of all i make a change to the redis_server (new Master host for example) in the ejabberd.yml
2. if i restart the process with ejabberdctl restart, it works
3. but if I call reload_config, the change doesn't get picked up ...
4. I think this is a bug, because I'm guessing the reload_config should pick up this config change

**Comment by stevenlivz** [comment]
That's it.

**Comment by badlop** [comment]
The reload_config description says it:
> Reload config file in memory (only affects ACL and Access)

So, the behaviour you see is not a bug: reload_config just reloads the configuration file, it doesn't touch any running element. In practice this reload only affects ACL and Access, which are static options. Almost everything else in ejabberd is dynamic, handled by processes, like modules, listeners... and database connections. All them read the configuration at server start, go alive, and never again stop. You'll have to restart the server for config changes to take effect on them.
