### ISSUE TITLE
Ejabberd with Mysql connectivity

### ISSUE THREAD

**Issue by AmitShrivastav** [processone/ejabberd#956]
Hi,
Can anyone please help me to connect mysql db with ejabberd. I have gone through multiple document and pages but not have concrete solution for latest ejabberd server version(13-16)

Ejabbert -Server version- 13- 16
Mysql -5.X

**Comment by badlop** [comment]
I don't know any ejabberd version with number 13-16, and surely it isn't the latest version.

**Comment by AmitShrivastav** [comment]
ejabberd version -16

**Comment by badlop** [comment]
The method is to:
1. Install ejabberd
2. Try it works correctly with internal database
3. Create a MySQL database, and create tables using sql/mysql.sql
4. Configure in ejabberd.yml the odbc database
5. Configure in ejabberd.yml to use odbc for authentication, or db_type in some modules
6. Restart ejabberd and check the config changes work correctly

**Comment by saeed-rz** [comment]
@AmitShrivastav  try ./configure with --enable-mysql option if sql folder not exist in root folder

**Comment by piyush-singhal** [comment]
I was also facing the same problem. you can use following steps to fix this issue.
First run below commands in the directory of your ejabberd source code.
./configure --enable-odbc --enable-mysql 
./rebar get-deps
./rebar compile 
sudo make install

then do following changes in your /etc/ejabberd/ejabberd.yml
1. change auth_method: external to ##auth_method: external
2. auth_method: odbc
3. 
odbc_type: mysql
odbc_server: "localhost"
odbc_database: "ejabberd"
odbc_username: "root"
odbc_password: "password"
## If you want to specify the port:
odbc_port: 3306
odbc_pool_size: 5


It should work for you.

**Comment by teadur** [comment]
backend mysql, tryng to register user from console.
Get error:  User test@my.domain already registered at node ejabberd@localhost

2016-03-06 20:23:58.632 [debug] <0.366.0>@ejabberd_odbc:sql_query_internal:474 SQL: "select password from users where username='test';"
2016-03-06 20:23:58.648 [debug] <0.369.0>@ejabberd_odbc:sql_query_internal:474 SQL: "insert into users(username, password, serverkey, salt, iterationcount) values ('test', 'REMOVED', 'REMOVED', 'REMOVED', '4096');"

Actualy the db is empty, looking at user table structure it seems to be:

CREATE TABLE users (
    username varchar(191) PRIMARY KEY,
    password text NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

https://github.com/processone/ejabberd/blob/04b3efd14c2eaee7819e6714737a0b8a1856def2/sql/mysql.sql

so it seems that atleast registration is broken because the insert query is broken.....

**Comment by piyush-singhal** [comment]
There is a possibility that you are connected properly with mysql. Otherwise you can't login in ejabberd backend without creating a new admin account. Once you connect with mysql it forget old account. 

Have you commented  **##auth_method: internal** and **##auth_method: external** 

I am attaching my sample yml file I renamed it with .txt because github file attachment don't support yml extension, you can compare it with yours. It may help you.
[ejabberd.yml.txt](https://github.com/processone/ejabberd/files/160948/ejabberd.yml.txt)

**Comment by teadur** [comment]
Actualy my problem was that by default in the sql structure file the scram auth lines are commented, and i was using scrammed passwords.

I think it would be better to uncomment the modification in default sql file to add the columns needed by scram auth, because in theory it shouldnot brake anything for people not using it...
