### ISSUE TITLE
mod_irc doesn't allow joining channels with prefixes other than #

### ISSUE THREAD

**Issue by zzottel** [processone/ejabberd#962]
As the channel name must be given without the "#" prefix, there's no possibility to join channels with other prefixes.

The prefixes "&" (channel local to server), "!" (channel secured against takeovers during netsplits), and "+" (modeless, unmoderated channel) are supported by many, though not all IRC networks. See RFC 2811: http://tools.ietf.org/html/rfc2811

Other prefixes like "." and "~" seem to be used nowadays, too (see https://www.alien.net.au/irc/chantypes.html ).

The available prefixes are usually sent by the server during connect in the 005 RPL_ISUPPORT message as CHANTYPES, see http://www.irc.org/tech_docs/005.html

My personal use case is that I'd like to join a modeless channel (+ prefix) on IRCnet.

**Comment by badlop** [comment]
mod_irc is not maintaned anymore. The code was moved to ejabberd-contrib in June (3a5d2dbed8f089b112eba7998e2ad0d2508f01cb), so that it doesn't get lost. If this problem is still present and somebody wants to fix it, a new ticket in [ejabberd-contrib](https://github.com/processone/ejabberd-contrib) can be created, referencing this old one.
