### ISSUE TITLE
[mod_register] option missing: limit registration `count` in `interval`

### ISSUE THREAD

**Issue by gblazex** [processone/ejabberd#983]
Similarly to how `mod_pres_counter` defines both `count` and `interval`, you can specify that you want to allow max 5 presence subscriptions during a 60 seconds interval.

`mod_register` currently only allows a timeout on a per IP basis. But that is _waaay too restrictive_ (think shared networks).
It's generally OK to receive a couple of registrations from the same IP, you only need to worry about registration storms.

count + interval setting is more suited for that.

Then you could say e.g. max 6 registrations from the same IP in 1 hour.
So 3 people registering at the same time is fine.

(that's the same rate as allowing 1 registration from an IP per 10 minutes, but is much more friendly to people trying to register close in time on the same network)

**Comment by galambalazs** [comment]
Also looking at the implementation of `mod_pres_counter` you'd be better off with a *token bucket* strategy instead of reseting a counter every X seconds. 

http://stackoverflow.com/questions/667508/whats-a-good-rate-limiting-algorithm

Didn't look for all the other rate limiting cases inside ejabberd but `mod_pres_counter` and `mod_register` seem like ideal candidates.
