### ISSUE TITLE
Persistent room was stopped  because it's temporary and empty

### ISSUE THREAD

**Issue by Suvitruf** [processone/ejabberd#999]
I've created persistent room. But it was stopped by ejabberd with log message:

> mod_muc_room:close_room_if_temporary_and_empty because it's temporary and empty

ejabberd_version: 16.01

**Comment by mremond** [comment]
How did you create persistent room. What is your backend ?

**Comment by Suvitruf** [comment]
Riak 

I've created it via Smack lib for Java where we set up submit form.

For persistence I've used `muc#roomconfig_persistentroom` in `submitForm.setAnswer(Constants.MUC_RM_CNFG_PERSISTENT, true);`

**Comment by badlop** [comment]
Make sure it is really configured as persistent:
1. Create and set persistent with your Smack client
2. Login to the server with that account and a typical desktop client (like Psi, Gajim...)
3. Join the room, configure it, and see if it's configured as persistent already.

Because I think ejabberd doesn't support create&configure in the same step. Only first create, and later configure.

**Comment by cromain** [comment]
i think this is due to possible bug in room creation test (see mod_muc_room:add_new_user)
if some limit is reached, room may be instantly stopped, not reaching the correct switch.
i guess client receives service unavailable.
the case test is not clear anyway, we should check this.

**Comment by badlop** [comment]
I reviewed the case test, and there wasn't any problem. Just in case, I added some parenthesis to make it more readable in https://github.com/processone/ejabberd/commit/ca329826cbf751cb87e8d6b79791457e4890b910
